# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry

logger = logging.getLogger(__name__)

_SIGN_BIT_I64 = tl.constexpr(-9223372036854775808)  # 0x8000000000000000

# Tuned on DCU (sweep at 8MiB-2GiB working sets, torch copy_ roofline =
# 1381 GB/s). 512 int64 lanes per block with 8 warps saturates the stream
# bandwidth (1379 GB/s) for large tensors; below ~512MiB of u64 lanes the
# launch geometry favors 1024 lanes per block (1353 vs 1335 GB/s at 128MiB).
# Eviction-policy/cache-modifier hints and multi-tile grids were also
# measured and do not beat the plain single-tile kernel.
BLOCK_SIZE_LARGE = 512
BLOCK_SIZE_SMALL = 1024
LARGE_THRESHOLD = 1 << 26  # u64 lanes, i.e. a 512MiB read+write stream
NUM_WARPS = 8


def _block_size(n_i64: int) -> int:
    return BLOCK_SIZE_LARGE if n_i64 >= LARGE_THRESHOLD else BLOCK_SIZE_SMALL


@libentry()
@triton.jit
def _conj_kernel_u64(
    in_ptr,
    out_ptr,
    n_i64,
    FLIP: tl.constexpr,  # 0 = pure copy, 1 = flip every lane, 2 = flip odd lanes
    BLOCK_SIZE: tl.constexpr,
):
    # Conjugate = flip the sign bit of the imaginary lane. Treating the data as
    # uint64 lanes gives perfectly coalesced wide accesses:
    #   complex64  -> one u64 per element, flip the high 32 bits (imag lane)
    #   complex128 -> two u64 per element, flip the odd lanes only
    pid = tl.program_id(0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_i64
    v = tl.load(in_ptr + offsets, mask=mask)
    if FLIP == 1:
        v = v ^ _SIGN_BIT_I64
    elif FLIP == 2:
        v = v ^ tl.where(offsets % 2 == 1, _SIGN_BIT_I64, 0)
    tl.store(out_ptr + offsets, v, mask=mask)


@libentry()
@triton.jit
def _conj_kernel(in_ptr, out_ptr, n_elements, BLOCK_SIZE: tl.constexpr):
    pid = tl.program_id(0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    # Complex numbers are stored as interleaved real/imaginary (real, imag, real, imag, ...)
    # Each complex element takes 2 float32 slots
    base = offsets * 2

    # Load real and imaginary parts
    real = tl.load(in_ptr + base, mask=mask)
    imag = tl.load(in_ptr + base + 1, mask=mask)

    # Store: real unchanged, imaginary negated (conjugate)
    tl.store(out_ptr + base, real, mask=mask)
    tl.store(out_ptr + base + 1, -imag, mask=mask)


def _u64_view(t: torch.Tensor) -> torch.Tensor:
    """Reinterpret a complex tensor's storage as int64 lanes.

    Works even when the conj bit is set (dtype-reinterpret views are rejected
    on conj views) by aliasing the untyped storage directly. Requires
    contiguous layout.
    """
    if not t.is_conj():
        return t.view(torch.int64)
    n_i64 = t.numel() * t.element_size() // 8
    u64 = torch.empty(0, dtype=torch.int64, device=t.device)
    u64.set_(t.untyped_storage(), t.storage_offset() * t.element_size() // 8, (n_i64,))
    return u64


def _conj(input: torch.Tensor) -> torch.Tensor:
    logger.debug("GEMS_HYGON CONJ")
    if not input.is_complex():
        raise RuntimeError("_conj only supports complex tensors")

    # If input already has the conjugate bit set, conj(conj(x)) = x: the
    # result is a plain physical copy of the storage bytes -- one streaming
    # pass instead of resolve_conj + conj_physical (two passes).
    if input.is_conj():
        if input.is_contiguous() and (input.numel() * input.element_size()) % 8 == 0:
            output = torch.empty(input.shape, dtype=input.dtype, device=input.device)
            in_u64 = _u64_view(input)
            out_u64 = output.view(torch.int64)
            n = in_u64.numel()
            block = _block_size(n)
            grid = (triton.cdiv(n, block),)
            _conj_kernel_u64[grid](
                in_u64,
                out_u64,
                n,
                FLIP=0,
                BLOCK_SIZE=block,
                num_warps=NUM_WARPS,
            )
            return output
        # Rare corner (non-contiguous conj view): resolve, then conjugate the
        # materialized values physically.
        return torch.conj_physical(input.resolve_conj())

    n_elements = input.numel()
    # Ensure contiguous memory layout for efficient loading
    src = input if input.is_contiguous() else input.contiguous()
    output = torch.empty_like(src)
    if src.dtype == torch.complex64:
        in_u64 = src.view(torch.int64)
        out_u64 = output.view(torch.int64)
        n = in_u64.numel()
        block = _block_size(n)
        grid = (triton.cdiv(n, block),)
        _conj_kernel_u64[grid](
            in_u64,
            out_u64,
            n,
            FLIP=1,
            BLOCK_SIZE=block,
            num_warps=NUM_WARPS,
        )
    elif src.dtype == torch.complex128:
        in_u64 = src.view(torch.int64)
        out_u64 = output.view(torch.int64)
        n = in_u64.numel()
        block = _block_size(n)
        grid = (triton.cdiv(n, block),)
        _conj_kernel_u64[grid](
            in_u64,
            out_u64,
            n,
            FLIP=2,
            BLOCK_SIZE=block,
            num_warps=NUM_WARPS,
        )
    else:
        in_real_ptr = torch.view_as_real(src)
        out_real_ptr = torch.view_as_real(output)
        grid = (triton.cdiv(n_elements, 4096),)
        _conj_kernel[grid](
            in_real_ptr, out_real_ptr, n_elements, BLOCK_SIZE=4096, num_warps=8
        )

    return output
