# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import math

import pytest
import torch

import flag_gems

from . import accuracy_utils as utils


def _fused_overrideable_attn_forward_math(
    Q,
    K,
    V,
    attn_bias=None,
    is_causal=False,
    dropout_p=0.0,
    softmax_scale=None,
):
    """Dense-BHSD math forward used to build overrideable backward inputs.

    Returns (out_bhsd, lse) where lse follows the (B, H, S_q) layout of the
    forward's meta registration.
    """
    scale = (
        softmax_scale if softmax_scale is not None else (1.0 / math.sqrt(Q.shape[-1]))
    )
    Qf = Q.float()
    Kf = K.float()
    Vf = V.float()
    scores = Qf @ Kf.transpose(-1, -2) * scale
    if attn_bias is not None:
        scores = scores + attn_bias.float()
    if is_causal:
        S_q, S_kv = Q.shape[2], K.shape[2]
        causal_mask = torch.ones(S_q, S_kv, dtype=torch.bool, device=Q.device).tril()
        scores = scores.masked_fill(~causal_mask, float("-inf"))
    lse = torch.logsumexp(scores, dim=-1)
    p = torch.exp(scores - lse.unsqueeze(-1))
    if dropout_p > 0.0:
        torch.manual_seed(42)
        drop_mask = torch.rand(p.shape, device=p.device) >= dropout_p
        p = p * drop_mask / (1.0 - dropout_p)
    out = p @ Vf
    return out.to(Q.dtype), lse, p


def _fused_overrideable_attn_backward_math(
    dOut,
    Q,
    K,
    V,
    out,
    p,
    softmax_scale=None,
):
    scale = (
        softmax_scale if softmax_scale is not None else (1.0 / math.sqrt(Q.shape[-1]))
    )
    dOf = dOut.float()
    Qf = Q.float()
    Kf = K.float()
    Vf = V.float()
    Outf = out.float()

    dV = p.transpose(-1, -2) @ dOf
    dP = dOf @ Vf.transpose(-1, -2)
    dS = p * (dP - (dOf * Outf).sum(-1, keepdim=True))
    dQ = dS @ Kf * scale
    dK = dS.transpose(-1, -2) @ Qf * scale
    return dQ, dK, dV, dS


@pytest.mark.scaled_dot_product_fused_attention_overrideable_backward
@pytest.mark.parametrize(
    "batch, num_head, q_seq_len, kv_seq_len",
    [
        (1, 1, 64, 64),
        (2, 4, 128, 128),
        (1, 2, 128, 256),
        (2, 4, 384, 384),
    ],
)
@pytest.mark.parametrize("head_size", [64, 128])
@pytest.mark.parametrize("is_causal", [False, True])
@pytest.mark.parametrize("has_attn_bias", [False, True])
# The overrideable fused attention kernels only accept float16/bfloat16
# operands, so this dtype set is intentionally restricted.
@pytest.mark.parametrize("dtype", [torch.float16, torch.bfloat16])
def test_scaled_dot_product_fused_attention_overrideable_backward(
    batch,
    num_head,
    q_seq_len,
    kv_seq_len,
    head_size,
    is_causal,
    has_attn_bias,
    dtype,
):
    if is_causal and has_attn_bias:
        pytest.skip("causal + attn_bias: skip")

    scale = float(1.0 / math.sqrt(head_size))

    Q_bhsd = torch.empty(
        batch, num_head, q_seq_len, head_size, dtype=dtype, device=flag_gems.device
    ).uniform_(-0.05, 0.05)
    K_bhsd = torch.empty(
        batch, num_head, kv_seq_len, head_size, dtype=dtype, device=flag_gems.device
    ).uniform_(-0.05, 0.05)
    V_bhsd = torch.empty(
        batch, num_head, kv_seq_len, head_size, dtype=dtype, device=flag_gems.device
    ).uniform_(-0.05, 0.05)
    dOut_bhsd = torch.randn(
        batch, num_head, q_seq_len, head_size, dtype=dtype, device=flag_gems.device
    )
    attn_bias = None
    if has_attn_bias:
        attn_bias = (
            torch.randn(
                batch,
                num_head,
                q_seq_len,
                kv_seq_len,
                dtype=dtype,
                device=flag_gems.device,
            )
            * 0.1
        )

    out_bhsd, lse, p = _fused_overrideable_attn_forward_math(
        Q_bhsd,
        K_bhsd,
        V_bhsd,
        attn_bias=attn_bias,
        is_causal=is_causal,
        softmax_scale=scale,
    )
    # The reference math runs on the reference device (CPU under --ref cpu),
    # while the flag_gems call always takes the original device tensors.
    ref_dOut_bhsd = utils.to_reference(dOut_bhsd)
    ref_Q_bhsd = utils.to_reference(Q_bhsd)
    ref_K_bhsd = utils.to_reference(K_bhsd)
    ref_V_bhsd = utils.to_reference(V_bhsd)
    ref_out_bhsd = utils.to_reference(out_bhsd)

    ref_dQ, ref_dK, ref_dV, _ = _fused_overrideable_attn_backward_math(
        ref_dOut_bhsd,
        ref_Q_bhsd,
        ref_K_bhsd,
        ref_V_bhsd,
        ref_out_bhsd,
        utils.to_reference(p),
        softmax_scale=scale,
    )

    (
        dQ_bhsd,
        dK_bhsd,
        dV_bhsd,
        dBias,
    ) = flag_gems.scaled_dot_product_fused_attention_overrideable_backward(
        dOut_bhsd,
        Q_bhsd,
        K_bhsd,
        V_bhsd,
        attn_bias,
        [True, True, True, has_attn_bias],
        out_bhsd,
        lse,
        None,
        None,
        q_seq_len,
        kv_seq_len,
        0.0,
        is_causal,
        None,
        None,
        scale=scale,
    )

    utils.gems_assert_close(dQ_bhsd, ref_dQ, dtype, equal_nan=True)
    utils.gems_assert_close(dK_bhsd, ref_dK, dtype, equal_nan=True)
    # dV is more sensitive to softmax recomputation errors in flash attention
    # backward because it lacks the centering term (dP - D); bf16 has the
    # largest recomputation error.
    v_atol = 5e-3 if dtype == torch.bfloat16 else 2e-3
    utils.gems_assert_close(dV_bhsd, ref_dV, dtype, equal_nan=True, atol=v_atol)
    if has_attn_bias:
        assert dBias is not None, "dBias should not be None when bias requires grad"
        _, _, _, ref_dS = _fused_overrideable_attn_backward_math(
            utils.to_reference(dOut_bhsd),
            utils.to_reference(Q_bhsd),
            utils.to_reference(K_bhsd),
            utils.to_reference(V_bhsd),
            utils.to_reference(out_bhsd),
            utils.to_reference(p),
            softmax_scale=scale,
        )
        utils.gems_assert_close(dBias, ref_dS, dtype, equal_nan=True)
    else:
        assert dBias is None, f"dBias should be None, got type={type(dBias)}"


@pytest.mark.scaled_dot_product_fused_attention_overrideable_backward
@pytest.mark.parametrize(
    "grad_input_mask",
    [
        (True, True, True, False),
        (False, True, False, False),
        (True, False, True, False),
    ],
)
# The overrideable fused attention kernels only accept float16/bfloat16;
# this mask test pins float16 to keep the grad_input_mask comparison exact.
@pytest.mark.parametrize("dtype", [torch.float16])
def test_scaled_dot_product_fused_attention_overrideable_backward_mask(
    grad_input_mask,
    dtype,
):
    batch, num_head, seq_len, head_size = 2, 4, 128, 64
    need_dq, need_dk, need_dv, need_dbias = grad_input_mask
    scale = float(1.0 / math.sqrt(head_size))

    Q_bhsd = torch.empty(
        batch, num_head, seq_len, head_size, dtype=dtype, device=flag_gems.device
    ).uniform_(-0.05, 0.05)
    K_bhsd = torch.empty_like(Q_bhsd).uniform_(-0.05, 0.05)
    V_bhsd = torch.empty_like(Q_bhsd).uniform_(-0.05, 0.05)
    dOut_bhsd = torch.randn(
        batch, num_head, seq_len, head_size, dtype=dtype, device=flag_gems.device
    )
    # need_dbias=True requires an attn_bias; keep bias path out of this test.
    assert not need_dbias

    out_bhsd, lse, p = _fused_overrideable_attn_forward_math(
        Q_bhsd, K_bhsd, V_bhsd, attn_bias=None, is_causal=False, softmax_scale=scale
    )
    ref_dQ, ref_dK, ref_dV, _ = _fused_overrideable_attn_backward_math(
        utils.to_reference(dOut_bhsd),
        utils.to_reference(Q_bhsd),
        utils.to_reference(K_bhsd),
        utils.to_reference(V_bhsd),
        utils.to_reference(out_bhsd),
        utils.to_reference(p),
        softmax_scale=scale,
    )

    (
        dQ_bhsd,
        dK_bhsd,
        dV_bhsd,
        dBias,
    ) = flag_gems.scaled_dot_product_fused_attention_overrideable_backward(
        dOut_bhsd,
        Q_bhsd,
        K_bhsd,
        V_bhsd,
        None,
        list(grad_input_mask),
        out_bhsd,
        lse,
        None,
        None,
        seq_len,
        seq_len,
        0.0,
        False,
        None,
        None,
        scale=scale,
    )

    if need_dq:
        utils.gems_assert_close(dQ_bhsd, ref_dQ, dtype, equal_nan=True)
    else:
        assert torch.all(dQ_bhsd == 0), "dQ should be zero when need_dq=False"
    if need_dk:
        utils.gems_assert_close(dK_bhsd, ref_dK, dtype, equal_nan=True)
    else:
        assert torch.all(dK_bhsd == 0), "dK should be zero when need_dk=False"
    if need_dv:
        utils.gems_assert_close(dV_bhsd, ref_dV, dtype, equal_nan=True)
    else:
        assert torch.all(dV_bhsd == 0), "dV should be zero when need_dv=False"
    assert dBias is None
