# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import pytest
import torch

import flag_gems

from . import accuracy_utils as utils

# LU decomposition requires high precision; float16/bfloat16 lack mantissa bits for pivoting
SOLVE_EX_DTYPES = [torch.float32]
if flag_gems.runtime.device.support_fp64:
    SOLVE_EX_DTYPES.append(torch.float64)

# Test shapes: (n, nrhs) - cover small to medium matrices for correctness
SOLVE_EX_SHAPES = [(4, 4), (8, 8), (16, 16), (32, 32)]


def _make_solve_ex_inputs(shape, k, dtype, device):
    """Create well-conditioned A and random B for solve_ex test."""
    n = shape[-1]
    A = torch.randn(*shape, dtype=dtype, device=device)
    eye = torch.eye(n, dtype=dtype, device=device)
    batch_dims = [1] * (A.ndim - 2)
    if batch_dims:
        eye = eye.view(*batch_dims, n, n)
    A = A @ A.mT + eye * n
    B_shape = shape[:-1] + (k,)
    B = torch.randn(*B_shape, dtype=dtype, device=device)
    return A, B


@pytest.mark.linalg_solve_ex
@pytest.mark.parametrize("shape", SOLVE_EX_SHAPES)
@pytest.mark.parametrize("dtype", SOLVE_EX_DTYPES)
def test_linalg_solve_ex(shape, dtype):
    n, k = shape
    A, B = _make_solve_ex_inputs((n, n), k, dtype, flag_gems.device)

    ref_A = utils.to_reference(A)
    ref_B = utils.to_reference(B)
    ref_out, ref_info = torch.linalg.solve_ex(ref_A, ref_B)
    res_out, res_info = flag_gems.linalg_solve_ex(A, B)

    utils.gems_assert_close(res_out, ref_out, dtype)
    assert torch.equal(res_info, ref_info.to(res_info.device))


@pytest.mark.linalg_solve_ex
@pytest.mark.parametrize("batch_shape", [(1,), (3,), (4,), (2, 4)])
@pytest.mark.parametrize("n", [4, 8, 16])
@pytest.mark.parametrize("k", [1, 4])
@pytest.mark.parametrize("dtype", SOLVE_EX_DTYPES)
def test_linalg_solve_ex_batched(batch_shape, n, k, dtype):
    shape_A = batch_shape + (n, n)
    A, B = _make_solve_ex_inputs(shape_A, k, dtype, flag_gems.device)

    ref_A = utils.to_reference(A)
    ref_B = utils.to_reference(B)
    ref_out, ref_info = torch.linalg.solve_ex(ref_A, ref_B)
    res_out, res_info = flag_gems.linalg_solve_ex(A, B)

    utils.gems_assert_close(res_out, ref_out, dtype)
    assert torch.equal(res_info, ref_info.to(res_info.device))
