# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import pytest
import torch

import flag_gems

from . import accuracy_utils as utils

LOWER = 0.125
UPPER = 1.0 / 3.0


@pytest.mark.rrelu_
@pytest.mark.parametrize("shape", utils.POINTWISE_SHAPES)
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_rrelu_(shape, dtype):
    inp = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    ref_inp = utils.to_reference(inp, True)

    ref_out = torch.rrelu_(ref_inp, training=False)
    res_out = flag_gems.rrelu_(inp, training=False)

    utils.gems_assert_close(res_out, ref_out, dtype)


@pytest.mark.rrelu_
@pytest.mark.parametrize("shape", utils.POINTWISE_SHAPES)
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_rrelu__custom_bounds(shape, dtype):
    inp = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    ref_inp = utils.to_reference(inp, True)

    lower, upper = 0.05, 0.5
    ref_out = torch.ops.aten.rrelu_(ref_inp, lower, upper, False, None)
    res_out = flag_gems.rrelu_(inp, lower, upper, False, None)

    utils.gems_assert_close(res_out, ref_out, dtype)


@pytest.mark.rrelu_
@pytest.mark.parametrize("shape", utils.POINTWISE_SHAPES)
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_rrelu__inplace(shape, dtype):
    inp = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    ref_inp = utils.to_reference(inp.clone(), True)

    ref_out = torch.rrelu_(ref_inp, training=False)
    res_out = flag_gems.rrelu_(inp, training=False)

    # The operator must mutate its input in place.
    utils.gems_assert_close(inp, ref_out, dtype)
    utils.gems_assert_close(res_out, ref_out, dtype)


@pytest.mark.rrelu_
@pytest.mark.parametrize("shape", [(2, 19, 7), (1024, 1024), (16, 128, 64, 60)])
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_rrelu__training(shape, dtype):
    # In training mode the slope is sampled uniformly from [lower, upper] per
    # element. The random stream differs between PyTorch and FlagGems, so the
    # outputs cannot be compared elementwise; instead we verify every element
    # of the output matches the RReLU semantics with a slope inside the bounds.
    lower, upper = LOWER, UPPER

    inp = -torch.rand(shape, dtype=dtype, device=flag_gems.device) - 0.5
    # The operator mutates `inp` in place, so keep an untouched copy for the
    # comparison. Under --ref cpu that copy must live on the reference device
    # (CPU), otherwise to_cpu()'s device assertion in gems_assert_equal fails.
    ref_inp = inp.clone() if not utils.TO_CPU else inp.cpu().clone()

    res_out = flag_gems.rrelu_(inp, lower, upper, True, None)

    # Positive inputs are passed through untouched. Under --ref cpu the
    # untouched copy lives on the reference device, so compare both operands
    # there (gems_assert_equal's to_cpu() then sees a CPU reference).
    cmp_res = res_out.to(ref_inp.device)
    pos = ref_inp >= 0
    utils.gems_assert_equal(cmp_res[pos], ref_inp[pos])

    # Negative inputs are scaled by a slope sampled from [lower, upper].
    slope = cmp_res[~pos] / ref_inp[~pos]
    assert torch.all(slope >= lower - 1e-3), slope.min().item()
    assert torch.all(slope <= upper + 1e-3), slope.max().item()
    # The slope must actually vary across elements (i.e. not the eval constant).
    avg_slope = (lower + upper) * 0.5
    assert not torch.allclose(slope.float(), torch.full_like(slope.float(), avg_slope))


@pytest.mark.rrelu_
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_rrelu__non_contiguous(dtype):
    inp = torch.randn((64, 128), dtype=dtype, device=flag_gems.device).t()

    ref_inp = utils.to_reference(inp.clone(), True)
    ref_out = torch.rrelu_(ref_inp, training=False)
    res_out = flag_gems.rrelu_(inp, training=False)

    utils.gems_assert_close(res_out, ref_out, dtype)
