# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

"""Accuracy tests for ``aten::_philox_normal_``.

``_philox_normal_`` is a stateless Philox RNG operator whose result is a pure
function of the ``(seed, offset)`` pair carried in ``key``. torch builds that
ship the operator can be compared against directly; for builds that predate it
(no schema in the installed torch) the reference is computed here from the same
ATen algorithm: Philox-4x32 counter values fed through the Box-Muller
transforms in ``aten/src/ATen/native/cuda/PhiloxDistribution.cu``.

The reference re-implements that file step for step (word rounding included) so
the comparison is deterministic rather than statistical.
"""

import numpy as np
import pytest
import torch

import flag_gems

from . import accuracy_utils as utils

# 32-bit Philox-4x32 constants, as used by ATen's StatelessPhilox4x32.cuh.
_PHILOX_KEY_A = np.uint32(0x9E3779B9)
_PHILOX_KEY_B = np.uint32(0xBB67AE85)
_PHILOX_ROUND_A = np.uint32(0xD2511F53)
_PHILOX_ROUND_B = np.uint32(0xCD9E8D57)
_U32_MAX = np.uint64(0xFFFFFFFF)

# Shapes beyond the shared distribution set: a single element, sizes that are
# not multiples of the 4 elements a Philox call yields (exercising the tail
# loop), and a couple of multi-dimensional cases.
_EXTRA_SHAPES = [(1,), (1024,), (997,), (16, 33), (2, 3, 5, 7)]
SHAPES = utils.DISTRIBUTION_SHAPES + _EXTRA_SHAPES


def _mulhilo32(a, b):
    p = a.astype(np.uint64) * b.astype(np.uint64)
    return (p & _U32_MAX).astype(np.uint32), (p >> np.uint64(32)).astype(np.uint32)


def _philox_round(ctr, key):
    c0, c1, c2, c3 = ctr
    k0, k1 = key
    r0_lo, r0_hi = _mulhilo32(_PHILOX_ROUND_A, c0)
    r1_lo, r1_hi = _mulhilo32(_PHILOX_ROUND_B, c2)
    return (
        np.uint32(r1_hi ^ c1 ^ k0),
        r1_lo,
        np.uint32(r0_hi ^ c3 ^ k1),
        r0_lo,
    )


def _philox_4x32(seed, offsets, rounds=10):
    """Stateless Philox-4x32 with subsequence fixed to 0, over a block."""
    seed = np.uint64(seed)
    key = (
        np.uint32(int(seed) & 0xFFFFFFFF),
        np.uint32(int(seed) >> 32),
    )
    offsets = np.asarray(offsets).astype(np.uint64)
    ctr = (
        (offsets & _U32_MAX).astype(np.uint32),
        (offsets >> np.uint64(32)).astype(np.uint32),
        np.zeros(offsets.shape, dtype=np.uint32),
        np.zeros(offsets.shape, dtype=np.uint32),
    )
    for _ in range(rounds - 1):
        ctr = _philox_round(ctr, key)
        key = (
            np.uint32((int(key[0]) + int(_PHILOX_KEY_A)) & 0xFFFFFFFF),
            np.uint32((int(key[1]) + int(_PHILOX_KEY_B)) & 0xFFFFFFFF),
        )
    return _philox_round(ctr, key)


def _fma_to_f32(word):
    """Reproduce ``fmaf(static_cast<float>(word), 2**-32, 2**-33)``.

    ``static_cast<float>`` rounds the uint32 word before the fused
    multiply-add, and both constants are powers of two, so evaluating the
    expression in float64 and rounding once matches the device result exactly.
    """
    return (
        word.astype(np.float32).astype(np.float64) * 2.3283064365386963e-10
        + 1.1641532182693481e-10
    ).astype(np.float32)


def _affine_f32(values, mean, std):
    """``values * sigma + mu`` in float32, contracted to a fused multiply-add."""
    mu = np.float32(mean)
    sigma = np.float32(std)
    return (values.astype(np.float64) * float(sigma) + float(mu)).astype(np.float32)


def _reference_normal(numel, seed, offset, mean, std, torch_dtype, device=None):
    """Compute the expected ``_philox_normal_`` output from the ATen algorithm.

    Arithmetics follow ``_philox_normal_cuda_``: 8-byte outputs accumulate in
    double and pair two Philox words per sample, everything else accumulates in
    float and consumes one word per sample, and the result is cast back to the
    storage dtype before storing.
    """
    if torch_dtype == torch.float64:
        per_call = 2
    else:
        per_call = 4
    num_chunks = -(-numel // per_call)
    counters = np.uint64(offset) + np.arange(num_chunks, dtype=np.uint64)
    r0, r1, r2, r3 = _philox_4x32(seed, counters)

    if torch_dtype == torch.float64:
        m = 2.3283064365386963e-10  # 2**-32, exact, so the sums are exact too
        u1 = r0.astype(np.float64) * m + (r1.astype(np.float64) * m * m + m * m * 0.5)
        u2 = r2.astype(np.float64) * m + (r3.astype(np.float64) * m * m + m * m * 0.5)
        radius = np.sqrt(-2.0 * np.log(u1))
        theta = 6.2831853071795864 * u2
        vals = np.stack([radius * np.cos(theta), radius * np.sin(theta)])
        out = (vals.T.reshape(-1)[:numel] * np.float64(std) + np.float64(mean)).astype(
            np.float64
        )
    else:
        u = np.stack(
            [_fma_to_f32(r0), _fma_to_f32(r1), _fma_to_f32(r2), _fma_to_f32(r3)]
        )
        radius = np.sqrt(np.float32(-2.0) * np.log(u))
        theta = np.float32(6.2831853071795864) * u
        # Words 0/1 and 2/3 each form a (cosine, sine) pair; the angle comes
        # from the odd-indexed word and the radius from the even-indexed one.
        vals = np.stack(
            [
                radius[0] * np.cos(theta[1]),
                radius[0] * np.sin(theta[1]),
                radius[2] * np.cos(theta[3]),
                radius[2] * np.sin(theta[3]),
            ]
        )
        out = _affine_f32(vals.T.reshape(-1)[:numel], mean, std)

    result = torch.from_numpy(np.ascontiguousarray(out)).to(torch_dtype)
    # Keep the reference on the caller's device, but on CPU under --ref cpu
    # so to_cpu()'s device assertion in gems_assert_close holds.
    if device is not None and not utils.TO_CPU:
        result = result.to(device)
    return result


def _make_key(seed, offset, device):
    return torch.tensor([seed, offset], dtype=torch.uint64, device=device)


@pytest.mark.philox_normal_
@pytest.mark.parametrize("shape", SHAPES)
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_philox_normal_(shape, dtype):
    seed, offset = 12345, 64
    mean, std = 2.0, 3.0
    key = _make_key(seed, offset, flag_gems.device)
    numel = torch.Size(shape).numel()

    res_out = flag_gems._philox_normal_(
        torch.empty(shape, dtype=dtype, device=flag_gems.device), key, mean, std
    )

    ref_out = _reference_normal(
        numel, seed, offset, mean, std, dtype, flag_gems.device
    ).reshape(shape)
    utils.gems_assert_close(res_out, ref_out, dtype)


@pytest.mark.philox_normal_
@pytest.mark.parametrize("shape", SHAPES)
@pytest.mark.parametrize("dtype", utils.ALL_FLOAT_DTYPES)
def test_philox_normal_default_params(shape, dtype):
    seed, offset = 7, 0
    key = _make_key(seed, offset, flag_gems.device)
    numel = torch.Size(shape).numel()

    res_out = flag_gems._philox_normal_(
        torch.empty(shape, dtype=dtype, device=flag_gems.device), key
    )

    ref_out = _reference_normal(
        numel, seed, offset, 0.0, 1.0, dtype, flag_gems.device
    ).reshape(shape)
    utils.gems_assert_close(res_out, ref_out, dtype)


@pytest.mark.philox_normal_
@pytest.mark.parametrize("dtype", utils.ALL_FLOAT_DTYPES)
@pytest.mark.parametrize("mean,std", [(0.0, 1.0), (-1.5, 0.5), (10.0, 0.25)])
def test_philox_normal_mean_std(dtype, mean, std):
    """``mean``/``std`` scale the standard normal stream in the accumulator
    type, so unusual values must survive the cast into the kernel."""
    seed, offset = 2024, 1 << 20
    key = _make_key(seed, offset, flag_gems.device)
    numel = 4096

    res_out = flag_gems._philox_normal_(
        torch.empty(numel, dtype=dtype, device=flag_gems.device), key, mean, std
    )

    ref_out = _reference_normal(numel, seed, offset, mean, std, dtype, flag_gems.device)
    utils.gems_assert_close(res_out, ref_out, dtype)


@pytest.mark.philox_normal_
def test_philox_normal_inplace_semantics():
    """The operator mutates ``self`` in place and returns that same tensor."""
    key = _make_key(99, 0, flag_gems.device)
    inp = torch.empty(128, dtype=torch.float32, device=flag_gems.device)
    original_ptr = inp.data_ptr()

    res_out = flag_gems._philox_normal_(inp, key, 1.0, 2.0)

    assert res_out.data_ptr() == original_ptr
    ref_out = _reference_normal(128, 99, 0, 1.0, 2.0, torch.float32, flag_gems.device)
    utils.gems_assert_close(inp, ref_out, torch.float32)


@pytest.mark.philox_normal_
def test_philox_normal_non_contiguous():
    """A non-contiguous output is filled through a contiguous staging buffer."""
    torch_dtype = torch.float32
    key = _make_key(5150, 32, flag_gems.device)
    base = torch.empty((32, 64), dtype=torch_dtype, device=flag_gems.device)
    inp = base.t()
    assert not inp.is_contiguous()

    res_out = flag_gems._philox_normal_(inp, key, 0.0, 1.0)

    assert res_out.data_ptr() == inp.data_ptr()
    ref_out = _reference_normal(
        inp.numel(), 5150, 32, 0.0, 1.0, torch_dtype, flag_gems.device
    ).reshape(inp.shape)
    utils.gems_assert_close(inp, ref_out, torch_dtype)


@pytest.mark.philox_normal_
def test_philox_normal_empty():
    """An empty output is left untouched rather than launching a kernel."""
    key = _make_key(1, 0, flag_gems.device)
    inp = torch.empty(0, dtype=torch.float32, device=flag_gems.device)

    res_out = flag_gems._philox_normal_(inp, key)

    assert res_out.data_ptr() == inp.data_ptr()
    assert res_out.numel() == 0


@pytest.mark.philox_normal_
def test_philox_normal_batched_key():
    """A ``(*batch, 1..., 2)`` key gives each output block its own stream.

    As in ATen, a key owns the output dimensions it leaves unsized: the
    ``(3, 1, 2)`` key below feeds three 64-element blocks.
    """
    torch_dtype = torch.float32
    num_keys, elems_per_key = 3, 64
    keys = [(11, 0), (22, 128), (33, 256)]
    key = torch.tensor(keys, dtype=torch.uint64, device=flag_gems.device).reshape(
        num_keys, 1, 2
    )
    out = torch.empty(
        (num_keys, elems_per_key), dtype=torch_dtype, device=flag_gems.device
    )

    res_out = flag_gems._philox_normal_(out, key, 0.0, 1.0)

    expected = torch.cat(
        [
            _reference_normal(
                elems_per_key, s, o, 0.0, 1.0, torch_dtype, flag_gems.device
            )
            for s, o in keys
        ]
    ).reshape(num_keys, elems_per_key)
    utils.gems_assert_close(res_out, expected, torch_dtype)


@pytest.mark.philox_normal_
def test_philox_normal_stream_continuity():
    """Consecutive offsets pick up the stream exactly where the last left off."""
    torch_dtype = torch.float32
    key_a = _make_key(4242, 0, flag_gems.device)
    key_b = _make_key(4242, 32, flag_gems.device)

    first = flag_gems._philox_normal_(
        torch.empty(128, dtype=torch_dtype, device=flag_gems.device), key_a
    )
    second = flag_gems._philox_normal_(
        torch.empty(128, dtype=torch_dtype, device=flag_gems.device), key_b
    )

    expected_first = _reference_normal(
        128, 4242, 0, 0.0, 1.0, torch_dtype, flag_gems.device
    )
    expected_second = _reference_normal(
        128, 4242, 32, 0.0, 1.0, torch_dtype, flag_gems.device
    )
    utils.gems_assert_close(first, expected_first, torch_dtype)
    utils.gems_assert_close(second, expected_second, torch_dtype)


@pytest.mark.philox_normal_
def test_philox_normal_large_offset():
    """Offsets beyond 2**32 keep generating a continuous stream."""
    torch_dtype = torch.float32
    seed = 987654321
    offset = (1 << 40) + 12345
    key = _make_key(seed, offset, flag_gems.device)

    res_out = flag_gems._philox_normal_(
        torch.empty(256, dtype=torch_dtype, device=flag_gems.device), key
    )

    ref_out = _reference_normal(
        256, seed, offset, 0.0, 1.0, torch_dtype, flag_gems.device
    )
    utils.gems_assert_close(res_out, ref_out, torch_dtype)


@pytest.mark.philox_normal_
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_philox_normal_statistics(dtype):
    """Sanity-check the distribution itself, independently of the stream.

    A whole-range mismatch in the Box-Muller pairing or angle assignment would
    still look plausible element-wise in a small sample, but it shifts the
    sample mean or standard deviation well outside the sampling error.
    """
    mean, std = -3.0, 2.0
    numel = 1 << 16
    key = _make_key(31337, 4, flag_gems.device)

    res_out = flag_gems._philox_normal_(
        torch.empty(numel, dtype=dtype, device=flag_gems.device), key, mean, std
    )

    values = res_out.float()
    # Sampling error of the mean is std/sqrt(numel) ~= 0.008; leave a wide
    # margin so the test cannot flake.
    assert abs(values.mean().item() - mean) < 0.1
    assert abs(values.std().item() - std) < 0.1
