# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import pytest
import torch

import flag_gems

from . import accuracy_utils as utils
from .conftest import QUICK_MODE

# dim is a layout-metadata query returning a plain int; the result is the
# tensor rank and is independent of dtype and of stored data. Coverage is
# driven by layout and rank instead: strided tensors of rank 0..5 (including
# non-contiguous and as_strided views), sparse COO (plain, 1-D, hybrid with
# dense trailing dims, zero-nnz, uncoalesced) and sparse compressed
# (CSR/CSC/BSR/BSC), plus nested tensors.
if QUICK_MODE:
    STRIDED_SHAPES = [(2, 3)]
else:
    STRIDED_SHAPES = [(), (5,), (2, 3), (2, 3, 4), (2, 3, 4, 5), (1, 1, 1, 1, 1, 1)]


def _make_coo(nnd, nnz, size, seed=0):
    gen = torch.Generator().manual_seed(seed)
    numel = 1
    for s in size[:nnd]:
        numel *= s
    flat = torch.randperm(numel, generator=gen)[:nnz]
    indices = torch.empty((nnd, nnz), dtype=torch.int64)
    for d in reversed(range(nnd)):
        indices[d] = flat % size[d]
        flat = flat // size[d]
    # Deliberately unsorted: uncoalesced COO must return the same metadata.
    values = torch.randn(nnz, generator=gen)
    return torch.sparse_coo_tensor(indices, values, size)


def _make_compressed(dev):
    c = torch.tensor([0, 2, 4], dtype=torch.int64, device=dev)
    cc = torch.tensor([0, 1, 0, 1], dtype=torch.int64, device=dev)
    val = torch.randn(4, device=dev)
    brow = torch.tensor([0, 1, 2], dtype=torch.int64, device=dev)
    bcol = torch.tensor([0, 1], dtype=torch.int64, device=dev)
    bval = torch.randn(2, 2, 2, device=dev)
    return {
        "csr": torch.sparse_csr_tensor(c, cc, val, (2, 3), device=dev),
        "csc": torch.sparse_csc_tensor(cc, c, val, (2, 3), device=dev),
        "bsr": torch.sparse_bsr_tensor(brow, bcol, bval, (4, 4), device=dev),
        "bsc": torch.sparse_bsc_tensor(bcol, brow, bval, (4, 4), device=dev),
    }


@pytest.mark.dim
@pytest.mark.parametrize("shape", STRIDED_SHAPES)
def test_dim_strided(shape):
    inp = torch.randn(shape, device=flag_gems.device)
    ref_inp = utils.to_reference(inp)

    ref_out = ref_inp.dim()
    res_out = flag_gems.dim(inp)

    assert isinstance(res_out, int)
    assert res_out == ref_out
    assert res_out == len(shape)


@pytest.mark.dim
def test_dim_strided_views():
    # Non-contiguous / strided / expanded layouts must report the same rank as
    # native: dim() reads the sizes array, never the storage layout.
    base = torch.randn(4, 6, device=flag_gems.device)
    views = {
        "transpose": base.t(),
        "narrow": base.narrow(1, 1, 3),
        "as_strided": torch.as_strided(base, (2, 3), (6, 2), 1),
        "expand": torch.randn(1, 6, device=flag_gems.device).expand(4, 6),
        "slice": base[1:3],
        "reshape3d": base.reshape(2, 3, 4),
        "unsqueeze": base.unsqueeze(0),
    }
    for name, view in views.items():
        ref_out = utils.to_reference(view).dim()
        res_out = flag_gems.dim(view)
        assert res_out == ref_out, f"{name}: {res_out} != {ref_out}"


@pytest.mark.dim
def test_dim_sparse_coo():
    dev = flag_gems.device
    for name, sparse, expected in [
        ("plain", _make_coo(2, 3, (2, 3), seed=1).to(dev), 2),
        ("1d", _make_coo(1, 3, (4,), seed=2).to(dev), 1),
        (
            "hybrid",
            torch.sparse_coo_tensor(
                torch.tensor([[0, 1]], device=dev),
                torch.randn(2, 3, device=dev),
                (2, 3),
            ),
            2,
        ),
        (
            "zero-nnz",
            torch.sparse_coo_tensor(
                torch.zeros(2, 0, dtype=torch.int64, device=dev),
                torch.zeros(0, device=dev),
                (2, 3),
            ),
            2,
        ),
        ("uncoalesced", _make_coo(2, 4, (2, 3), seed=3).to(dev), 2),
        ("3d", _make_coo(3, 5, (2, 3, 4), seed=4).to(dev), 3),
    ]:
        ref_out = utils.to_reference(sparse).dim()
        res_out = flag_gems.dim(sparse)
        assert res_out == ref_out, f"{name}: {res_out} != {ref_out}"
        assert res_out == expected, f"{name}: {res_out} != {expected}"


@pytest.mark.dim
def test_dim_sparse_compressed():
    for name, t in _make_compressed(flag_gems.device).items():
        ref_out = utils.to_reference(t).dim()
        res_out = flag_gems.dim(t)
        # A 2-D compressed tensor has rank 2 (sparse_dim + dense_dim = 2),
        # independent of which of the four compressed layouts is used.
        assert res_out == ref_out, f"{name}: {res_out} != {ref_out}"
        assert res_out == 2, f"{name}: {res_out} != 2"


@pytest.mark.dim
def test_dim_nested():
    # Nested tensors carry a rank; the implementation must not read `shape`
    # or `stride` here because those raise for nested inputs.
    nt = torch.nested.nested_tensor(
        [
            torch.randn(2, 3, device=flag_gems.device),
            torch.randn(4, 5, device=flag_gems.device),
        ],
        device=flag_gems.device,
    )
    ref_out = utils.to_reference(nt).dim()
    res_out = flag_gems.dim(nt)
    assert res_out == ref_out
    assert res_out == 3


@pytest.mark.dim
def test_dim_matches_reference_table():
    # Reference values captured on H20 in a process that never imported
    # flag_gems (runs/dim/native_semantics_gpu.py), pinned here as literals.
    table = {
        "strided()": 0,
        "strided(5,)": 1,
        "strided(2,3)": 2,
        "strided(2,3,4)": 3,
        "strided(2,3,4,5)": 4,
        "strided(1,1,1,1,1,1)": 6,
        "coo-1d": 1,
        "coo-2d": 2,
        "coo-hybrid": 2,
        "coo-3d": 3,
        "csr": 2,
        "csc": 2,
        "bsr": 2,
        "bsc": 2,
        "nested": 3,
    }
    dev = flag_gems.device
    assert flag_gems.dim(torch.randn((), device=dev)) == table["strided()"]
    assert flag_gems.dim(torch.randn(5, device=dev)) == table["strided(5,)"]
    assert flag_gems.dim(torch.randn(2, 3, device=dev)) == table["strided(2,3)"]
    assert flag_gems.dim(torch.randn(2, 3, 4, device=dev)) == table["strided(2,3,4)"]
    assert (
        flag_gems.dim(torch.randn(2, 3, 4, 5, device=dev)) == table["strided(2,3,4,5)"]
    )
    assert (
        flag_gems.dim(torch.randn(1, 1, 1, 1, 1, 1, device=dev))
        == table["strided(1,1,1,1,1,1)"]
    )
    assert flag_gems.dim(_make_coo(1, 3, (4,), seed=6).to(dev)) == table["coo-1d"]
    assert flag_gems.dim(_make_coo(2, 3, (2, 3), seed=5).to(dev)) == table["coo-2d"]
    hybrid = torch.sparse_coo_tensor(
        torch.tensor([[0, 1]], device=dev),
        torch.randn(2, 3, device=dev),
        (2, 3),
    )
    assert flag_gems.dim(hybrid) == table["coo-hybrid"]
    assert flag_gems.dim(_make_coo(3, 5, (2, 3, 4), seed=4).to(dev)) == table["coo-3d"]
    for name, t in _make_compressed(dev).items():
        assert flag_gems.dim(t) == table[name], f"{name}"

    nt = torch.nested.nested_tensor(
        [torch.randn(2, 3, device=dev), torch.randn(4, 5, device=dev)], device=dev
    )
    assert flag_gems.dim(nt) == table["nested"]


@pytest.mark.dim
def test_dim_aliases_agree():
    # dim(), ndim and ndimension are aliases on native tensors; the submitted
    # implementation must agree with all three reference forms on every layout.
    dev = flag_gems.device
    cases = [
        torch.randn(2, 3, device=dev),
        torch.randn((), device=dev),
        torch.randn(4, 6, device=dev).t(),
        _make_coo(2, 3, (2, 3), seed=8).to(dev),
        _make_compressed(dev)["csr"],
        _make_compressed(dev)["bsc"],
    ]
    for t in cases:
        ref = utils.to_reference(t)
        res_out = flag_gems.dim(t)
        assert res_out == ref.dim()
        assert res_out == ref.ndim
        assert res_out == ref.ndimension()
        # torch.ops.aten.dim is the ATen reference call form.
        assert res_out == torch.ops.aten.dim(ref)


@pytest.mark.dim
def test_dim_is_dispatch_free():
    # The implementation must not re-enter the dispatcher: reading `ndim` is a
    # TensorImpl property read. Instrumented with TorchDispatchMode, a call to
    # flag_gems.dim must not raise any dispatcher op on any layout (a re-entrant
    # `self.dim()` would).
    class Recorder(torch.utils._python_dispatch.TorchDispatchMode):
        def __init__(self):
            self.seen = []

        def __torch_dispatch__(self, func, types, args=(), kwargs=None):
            self.seen.append(func._schema.name)
            return func(*args, **(kwargs or {}))

    dev = flag_gems.device
    cases = [
        torch.randn(2, 3, device=dev),
        _make_coo(2, 3, (2, 3), seed=9).to(dev),
        _make_compressed(dev)["csr"],
    ]
    for t in cases:
        with Recorder() as rec:
            res_out = flag_gems.dim(t)
        assert res_out == utils.to_reference(t).dim()
        assert rec.seen == [], f"unexpected dispatcher calls: {rec.seen}"


@pytest.mark.dim
def test_dim_dtype_and_device_independence():
    # dim is metadata-only: the value must not vary with dtype or device.
    dev = flag_gems.device
    dtypes = [torch.float16, torch.float32, torch.bfloat16, torch.int32, torch.bool]
    if not QUICK_MODE:
        dtypes += [torch.float64, torch.int8, torch.int64]
    for dtype in dtypes:
        inp = torch.empty((2, 3, 4), dtype=dtype, device=dev)
        assert flag_gems.dim(inp) == 3, f"{dtype}"
    # CPU tensors are pure metadata too; the reference is taken on CPU in the
    # quick phase, so this exercises that path explicitly.
    cpu = torch.randn(2, 3, 4, 5)
    assert flag_gems.dim(cpu) == 4
    assert flag_gems.dim(cpu) == utils.to_reference(cpu).dim()


@pytest.mark.dim
def test_dim_requires_grad_and_meta():
    dev = flag_gems.device
    grad = torch.randn(2, 3, device=dev, requires_grad=True)
    assert flag_gems.dim(grad) == utils.to_reference(grad).dim()
    with torch.no_grad():
        assert flag_gems.dim(grad) == 2
    meta = torch.randn(2, 3, 4, device="meta")
    # A meta tensor holds only sizes/strides metadata and cannot be copied to
    # CPU, so the reference is the native ATen call on the meta tensor itself
    # (dim never touches storage), cross-checked against a same-shape CPU
    # tensor for the rank.
    assert flag_gems.dim(meta) == torch.ops.aten.dim(meta)
    assert flag_gems.dim(meta) == torch.randn(2, 3, 4).dim()
    assert flag_gems.dim(meta) == 3


@pytest.mark.dim
def test_dim_arg_validation():
    # Native validates the argument before any dispatch: an over-long argument
    # list and a non-tensor first argument are both rejected. Assert only that
    # the rejection is raised (the class/wording differs between builds), per
    # the batch's error-assertion rules.
    t = torch.randn(2, 3, device=flag_gems.device)
    with pytest.raises(Exception):
        torch.ops.aten.dim(t, 3)
    with pytest.raises(Exception):
        torch.ops.aten.dim(3)
    with pytest.raises(Exception):
        torch.ops.aten.dim("not a tensor")


@pytest.mark.dim
def test_dim_with_registration_active():
    # Mirror what GeneralOpRegistrar does for the _FULL_CONFIG entry: register
    # the submitted implementation on the device key (plus the sparse keys the
    # sibling metadata ops use), then exercise both the implementation and the
    # native call forms.
    #
    # aten::dim is NOT a dispatcher operator on this build, so this
    # registration cannot intercept `t.dim()` / `torch.ops.aten.dim(t)`; that
    # is pinning the measured state, not an assumption. What this test does
    # guarantee is the invariant that matters: with the registration active the
    # implementation stays correct and non-recursive on every layout, and it
    # does not perturb the native call forms.
    lib = torch.library.Library("aten", "IMPL")
    for key in ("CUDA", "SparseCUDA", "SparseCsrCUDA"):
        lib.impl("dim", flag_gems.dim, key)
    try:
        dev = flag_gems.device
        cases = [
            (torch.randn(2, 3, device=dev), 2),
            (torch.randn((), device=dev), 0),
            (_make_coo(2, 3, (2, 3), seed=10).to(dev), 2),
            (_make_compressed(dev)["csr"], 2),
        ]
        for t, expected in cases:
            # Repeated calls: a self-recursion bug would surface here.
            for _ in range(3):
                assert flag_gems.dim(t) == expected
            # Native call forms keep working and keep returning the rank.
            assert t.dim() == expected
            assert torch.ops.aten.dim(t) == expected
            assert t.ndim == expected
    finally:
        lib._destroy()
