# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import pytest
import torch

import flag_gems

from . import accuracy_utils as utils


@pytest.mark.hardshrink_backward
@pytest.mark.parametrize("shape", utils.POINTWISE_SHAPES)
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
@pytest.mark.parametrize("lambd", [0.5, 1.0, 0.0])
def test_hardshrink_backward(shape, dtype, lambd):
    grad_output = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    inp = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    ref_grad = utils.to_reference(grad_output)
    ref_inp = utils.to_reference(inp)

    ref_out = torch.ops.aten.hardshrink_backward(ref_grad, ref_inp, lambd)
    res_out = flag_gems.hardshrink_backward(grad_output, inp, lambd)

    utils.gems_assert_close(res_out, ref_out, dtype)


@pytest.mark.hardshrink_backward_grad_input
@pytest.mark.parametrize("shape", utils.POINTWISE_SHAPES)
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_hardshrink_backward_grad_input(shape, dtype):
    grad_output = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    inp = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    ref_grad = utils.to_reference(grad_output)
    ref_inp = utils.to_reference(inp)

    ref_out_buf = torch.empty(shape, dtype=ref_inp.dtype, device=ref_inp.device)
    ref_out = torch.ops.aten.hardshrink_backward.grad_input(
        ref_grad, ref_inp, 0.5, grad_input=ref_out_buf
    )

    res_out_buf = torch.empty(shape, dtype=dtype, device=flag_gems.device)
    res_out = flag_gems.hardshrink_backward_grad_input(
        grad_output, inp, 0.5, grad_input=res_out_buf
    )

    utils.gems_assert_close(res_out, ref_out, dtype)
    utils.gems_assert_close(res_out_buf, ref_out_buf, dtype)


@pytest.mark.hardshrink_backward
def test_hardshrink_backward_special_values():
    # Gradient must pass through at NaN / +-inf inputs, matching ATen behavior.
    inp = torch.tensor(
        [float("nan"), float("-inf"), float("inf"), 0.0, 0.5, -0.5, 0.7, -0.7],
        device=flag_gems.device,
    )
    grad_output = torch.ones_like(inp)
    ref_grad = utils.to_reference(grad_output)
    ref_inp = utils.to_reference(inp)

    ref_out = torch.ops.aten.hardshrink_backward(ref_grad, ref_inp, 0.5)
    res_out = flag_gems.hardshrink_backward(grad_output, inp, 0.5)

    utils.gems_assert_equal(res_out, ref_out, equal_nan=True)
