# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import pytest
import torch

import flag_gems

from . import accuracy_utils as utils
from . import conftest as cfg

if cfg.QUICK_MODE:
    WINDOW_LENGTHS = [100]
else:
    WINDOW_LENGTHS = [0, 1, 2, 3, 10, 100, 1000, 4096, 10000]


@pytest.mark.bartlett_window
@pytest.mark.parametrize("window_length", WINDOW_LENGTHS)
@pytest.mark.parametrize("periodic", [True, False])
@pytest.mark.parametrize("dtype", utils.ALL_FLOAT_DTYPES)
def test_bartlett_window(window_length, periodic, dtype):
    device = "cpu" if cfg.TO_CPU else flag_gems.device
    res_out = flag_gems.bartlett_window(
        window_length, periodic=periodic, dtype=dtype, device=device
    )
    # Compare against the float64 window: torch's low-precision path accumulates
    # in the output dtype and drifts by 1-2 ULP, so it is not a tight reference.
    ref_out = torch.bartlett_window(
        window_length, periodic=periodic, dtype=torch.float64, device=device
    ).to(dtype)
    if window_length > 1:
        utils.gems_assert_close(res_out, ref_out, dtype)
    else:
        utils.gems_assert_equal(res_out, ref_out)
