# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

"""Accuracy tests for ``aten::_scaled_grouped_mm_v2``.

The operator is the newer, recipe-driven spelling of the grouped scaled
matrix multiply: ``scale_a``/``scale_b`` arrive as lists, paired with
``recipe_a``/``recipe_b`` (``TensorWise`` / ``RowWise``) and, optionally,
``swizzle_a``/``swizzle_b``.

Only ``float8_e4m3fn`` operands with ``float32`` decoding scales and a
``bfloat16`` high-precision output are exercised, matching what the upstream
grouped GEMM kernels accept.  The reference is computed group by group on the
CPU from the same operands, so the comparison is deterministic.
"""

import pytest
import torch

import flag_gems

from .conftest import QUICK_MODE

if QUICK_MODE:
    CASES = ["m_varying"]
else:
    CASES = ["m_varying", "batch", "k_varying", "n_varying"]


def _cuda_fp8_available():
    if flag_gems.device != "cuda" or not torch.cuda.is_available():
        return False
    if not hasattr(torch, "float8_e4m3fn"):
        return False
    major, minor = torch.cuda.get_device_capability()
    return major * 10 + minor >= 89


def _dtype_cases():
    return [torch.float8_e4m3fn] if _cuda_fp8_available() else []


def _make_tensor(shape, dtype):
    base = torch.randn(shape, dtype=torch.float32, device=flag_gems.device) * 0.25
    try:
        return base.to(dtype)
    except RuntimeError as exc:
        pytest.skip(f"{dtype} is not supported on {flag_gems.device}: {exc}")


def _make_mat_b(shape, dtype):
    """Build ``mat_b`` in the transposed (column major) layout the kernel wants.

    ``shape`` is the logical ``(..., K, N)`` shape.  The kernel contracts along
    the leading dimension and walks columns with unit stride, so the values are
    materialised as ``(..., N, K)`` and swapped, leaving ``stride(-2) == 1``.
    """
    k_size, n_size = shape[-2], shape[-1]
    base = torch.randn(
        shape[:-2] + (n_size, k_size), dtype=torch.float32, device=flag_gems.device
    )
    return (base * 0.25).to(dtype).transpose(-2, -1)


def _make_case(case_name, dtype):
    """Build the operands, scales and ``offs`` for one of the four layouts.

    Each case is chosen so the group boundaries are exact: the jagged extents
    are multiples of the 16 elements that the upstream fp8 kernels require for
    the scaled dimension of the output.
    """
    groups, m_per_group, n_per_group, k_size = 3, 32, 64, 128

    if case_name == "m_varying":
        # ``mat_a`` is 2D and sliced along M; ``mat_b`` stays 3D.
        sizes = [16, 32, 48]
        total_m = sum(sizes)
        mat_a = _make_tensor((total_m, k_size), dtype)
        mat_b = _make_mat_b((groups, k_size, n_per_group), dtype)
        offs = torch.tensor(
            [sum(sizes[: i + 1]) for i in range(groups)],
            dtype=torch.int32,
            device=flag_gems.device,
        )
        scale_a = torch.linspace(0.75, 1.25, total_m, device=flag_gems.device)
        scale_b = torch.linspace(
            1.25, 0.75, groups * n_per_group, device=flag_gems.device
        ).reshape(groups, n_per_group)
        return mat_a, mat_b, scale_a, scale_b, offs

    if case_name == "batch":
        # Both operands are 3D and ``offs`` has to be ``None``.
        mat_a = _make_tensor((groups, m_per_group, k_size), dtype)
        mat_b = _make_mat_b((groups, k_size, n_per_group), dtype)
        scale_a = torch.linspace(
            0.75, 1.25, groups * m_per_group, device=flag_gems.device
        ).reshape(groups, m_per_group)
        scale_b = torch.linspace(
            1.25, 0.75, groups * n_per_group, device=flag_gems.device
        ).reshape(groups, n_per_group)
        return mat_a, mat_b, scale_a, scale_b, None

    if case_name == "k_varying":
        # Both operands are 2D; ``offs`` slices the contraction dimension and
        # the output gains a batch dimension.  Both scales are flat, holding
        # one row per group.
        k_offsets = [32, 64, 96]
        mat_a = _make_tensor((m_per_group, k_size), dtype)
        mat_b = _make_mat_b((k_size, n_per_group), dtype)
        offs = torch.tensor(k_offsets, dtype=torch.int32, device=flag_gems.device)
        scale_a = torch.linspace(
            0.75, 1.25, groups * m_per_group, device=flag_gems.device
        )
        scale_b = torch.linspace(
            1.25, 0.75, groups * n_per_group, device=flag_gems.device
        )
        return mat_a, mat_b, scale_a, scale_b, offs

    # ``n_varying``: ``mat_a`` stays 3D, ``mat_b`` is 2D and sliced along N.
    n_offsets = [16, 32, 64]
    mat_a = _make_tensor((groups, m_per_group, k_size), dtype)
    mat_b = _make_mat_b((k_size, n_offsets[-1]), dtype)
    offs = torch.tensor(n_offsets, dtype=torch.int32, device=flag_gems.device)
    scale_a = torch.linspace(
        0.75, 1.25, groups * m_per_group, device=flag_gems.device
    ).reshape(groups, m_per_group)
    scale_b = torch.linspace(1.25, 0.75, n_offsets[-1], device=flag_gems.device)
    return mat_a, mat_b, scale_a, scale_b, offs


def _scale_and_bias(out, scale_a, scale_b):
    return out * scale_a * scale_b


def _reference(mat_a, mat_b, scale_a, scale_b, offs):
    """Per-group reference GEMM, computed on the CPU in float32."""
    a_is_2d = mat_a.dim() == 2
    b_is_2d = mat_b.dim() == 2
    if a_is_2d and b_is_2d:
        groups = offs.numel()
    elif a_is_2d:
        groups = mat_b.shape[0]
    else:
        groups = mat_a.shape[0]

    mat_a = mat_a.detach().cpu().float()
    mat_b = mat_b.detach().cpu().float()
    scale_a = scale_a.detach().cpu().float()
    scale_b = scale_b.detach().cpu().float()
    offsets = [0] + (offs.detach().cpu().tolist() if offs is not None else [])

    chunks = []
    if a_is_2d and not b_is_2d:
        for group_idx in range(groups):
            m_start, m_end = offsets[group_idx], offsets[group_idx + 1]
            chunk = mat_a[m_start:m_end].mm(mat_b[group_idx])
            chunks.append(
                _scale_and_bias(
                    chunk,
                    scale_a[m_start:m_end].reshape(-1, 1),
                    scale_b[group_idx].reshape(1, -1),
                )
            )
        return torch.cat(chunks, dim=0)

    if not a_is_2d and b_is_2d:
        for group_idx in range(groups):
            n_start, n_end = offsets[group_idx], offsets[group_idx + 1]
            chunk = mat_a[group_idx].mm(mat_b[:, n_start:n_end])
            chunks.append(
                _scale_and_bias(
                    chunk,
                    scale_a[group_idx].reshape(-1, 1),
                    scale_b[n_start:n_end].reshape(1, -1),
                )
            )
        return torch.cat(chunks, dim=1)

    if a_is_2d and b_is_2d:
        scale_a = scale_a.reshape(groups, mat_a.shape[0])
        scale_b = scale_b.reshape(groups, mat_b.shape[1])
        for group_idx in range(groups):
            k_start, k_end = offsets[group_idx], offsets[group_idx + 1]
            chunk = mat_a[:, k_start:k_end].mm(mat_b[k_start:k_end])
            chunks.append(
                _scale_and_bias(
                    chunk,
                    scale_a[group_idx].reshape(-1, 1),
                    scale_b[group_idx].reshape(1, -1),
                )
            )
        return torch.stack(chunks, dim=0)

    for group_idx in range(groups):
        chunk = mat_a[group_idx].mm(mat_b[group_idx])
        chunks.append(
            _scale_and_bias(
                chunk,
                scale_a[group_idx].reshape(-1, 1),
                scale_b[group_idx].reshape(1, -1),
            )
        )
    return torch.stack(chunks, dim=0)


def _row_wise_scales(mat_a, mat_b, scale_a, scale_b):
    """Descriptor tuple feeding ``recipe`` / ``swizzle`` for the RowWise path."""
    return [scale_a], [1], [0], [scale_b], [1], [0]


@pytest.mark.scaled_grouped_mm_v2
@pytest.mark.parametrize("case_name", CASES)
@pytest.mark.parametrize("dtype", _dtype_cases())
def test_scaled_grouped_mm_v2(case_name, dtype):
    mat_a, mat_b, scale_a, scale_b, offs = _make_case(case_name, dtype)

    ref = _reference(mat_a, mat_b, scale_a, scale_b, offs)
    ref = ref.to(torch.bfloat16)

    lst_a, recipe_a, swizzle_a, lst_b, recipe_b, swizzle_b = _row_wise_scales(
        mat_a, mat_b, scale_a, scale_b
    )
    res = flag_gems._scaled_grouped_mm_v2(
        mat_a,
        mat_b,
        lst_a,
        recipe_a,
        swizzle_a,
        lst_b,
        recipe_b,
        swizzle_b,
        offs,
        None,
        torch.bfloat16,
        [],
        False,
    )

    assert res.shape == ref.shape
    assert res.dtype == torch.bfloat16
    # fp8 operands accumulate in float32 but the reference rounds to bf16, so
    # the comparison has to tolerate the ~1e-2 resolution bf16 carries at the
    # magnitudes this GEMM produces.
    torch.testing.assert_close(res.float().cpu(), ref.float(), atol=2.5e-1, rtol=5e-1)


@pytest.mark.scaled_grouped_mm_v2
@pytest.mark.parametrize("dtype", _dtype_cases())
def test_scaled_grouped_mm_v2_tensor_wise(dtype):
    """``TensorWise`` recipes carry a single scalar factor per operand.

    The upstream kernels do not implement this combination (they reject it
    with "No gemm implementation was found"), so the Triton kernel is checked
    against the per-group reference alone.
    """
    mat_a, mat_b, scale_a, scale_b, offs = _make_case("m_varying", dtype)
    groups = mat_b.shape[0]
    total_m = mat_a.shape[0]
    n_size = mat_b.shape[-1]

    scale_a = torch.full((1,), 0.9, device=flag_gems.device)
    scale_b = torch.full((1,), 1.1, device=flag_gems.device)
    ref = (
        _reference(
            mat_a,
            mat_b,
            torch.full((total_m,), 0.9, device=flag_gems.device),
            torch.full((groups, n_size), 1.1, device=flag_gems.device),
            offs,
        )
        .to(torch.bfloat16)
        .float()
    )

    res = flag_gems._scaled_grouped_mm_v2(
        mat_a,
        mat_b,
        [scale_a],
        [0],
        [0],
        [scale_b],
        [0],
        [0],
        offs,
        None,
        torch.bfloat16,
        [],
        False,
    )

    torch.testing.assert_close(res.float().cpu(), ref, atol=2.5e-1, rtol=5e-1)


@pytest.mark.scaled_grouped_mm_v2
@pytest.mark.parametrize("dtype", _dtype_cases())
def test_scaled_grouped_mm_v2_out_dtype_default(dtype):
    """Leaving ``out_dtype`` unset yields the bfloat16 high-precision output."""
    mat_a, mat_b, scale_a, scale_b, offs = _make_case("m_varying", dtype)
    lst_a, recipe_a, swizzle_a, lst_b, recipe_b, swizzle_b = _row_wise_scales(
        mat_a, mat_b, scale_a, scale_b
    )

    ref = _reference(mat_a, mat_b, scale_a, scale_b, offs).to(torch.bfloat16).float()

    res = flag_gems._scaled_grouped_mm_v2(
        mat_a,
        mat_b,
        lst_a,
        recipe_a,
        swizzle_a,
        lst_b,
        recipe_b,
        swizzle_b,
        offs,
        None,
        None,
        [],
        False,
    )

    assert res.dtype == torch.bfloat16
    torch.testing.assert_close(res.float().cpu(), ref, atol=2.5e-1, rtol=5e-1)


@pytest.mark.scaled_grouped_mm_v2
@pytest.mark.parametrize("dtype", _dtype_cases())
def test_scaled_grouped_mm_v2_use_fast_accum(dtype):
    """``use_fast_accum`` selects a different accumulation path, not a result."""
    mat_a, mat_b, scale_a, scale_b, offs = _make_case("m_varying", dtype)
    lst_a, recipe_a, swizzle_a, lst_b, recipe_b, swizzle_b = _row_wise_scales(
        mat_a, mat_b, scale_a, scale_b
    )

    res_slow = flag_gems._scaled_grouped_mm_v2(
        mat_a,
        mat_b,
        lst_a,
        recipe_a,
        swizzle_a,
        lst_b,
        recipe_b,
        swizzle_b,
        offs,
        None,
        torch.bfloat16,
        [],
        False,
    )
    res_fast = flag_gems._scaled_grouped_mm_v2(
        mat_a,
        mat_b,
        lst_a,
        recipe_a,
        swizzle_a,
        lst_b,
        recipe_b,
        swizzle_b,
        offs,
        None,
        torch.bfloat16,
        [],
        True,
    )

    torch.testing.assert_close(
        res_fast.float().cpu(), res_slow.float().cpu(), atol=2.5e-1, rtol=5e-1
    )


@pytest.mark.scaled_grouped_mm_v2
@pytest.mark.skipif(
    not _cuda_fp8_available(), reason="unsupported input dtype requires CUDA fp8"
)
def test_scaled_grouped_mm_v2_rejects_bias():
    mat_a, mat_b, scale_a, scale_b, offs = _make_case("m_varying", torch.float8_e4m3fn)
    lst_a, recipe_a, swizzle_a, lst_b, recipe_b, swizzle_b = _row_wise_scales(
        mat_a, mat_b, scale_a, scale_b
    )
    with pytest.raises(ValueError, match="Bias not supported"):
        flag_gems._scaled_grouped_mm_v2(
            mat_a,
            mat_b,
            lst_a,
            recipe_a,
            swizzle_a,
            lst_b,
            recipe_b,
            swizzle_b,
            offs,
            torch.zeros(mat_b.shape[-1], device=flag_gems.device),
            torch.bfloat16,
            [],
            False,
        )


@pytest.mark.scaled_grouped_mm_v2
@pytest.mark.parametrize("case_name", CASES)
@pytest.mark.parametrize("dtype", _dtype_cases())
def test_scaled_grouped_mm_v2_matches_native(case_name, dtype):
    """Every supported layout agrees with the upstream ATen kernel."""
    if not hasattr(torch, "_scaled_grouped_mm_v2"):
        pytest.skip("torch build does not expose aten::_scaled_grouped_mm_v2")

    mat_a, mat_b, scale_a, scale_b, offs = _make_case(case_name, dtype)
    lst_a, recipe_a, swizzle_a, lst_b, recipe_b, swizzle_b = _row_wise_scales(
        mat_a, mat_b, scale_a, scale_b
    )

    ref = torch._scaled_grouped_mm_v2(
        mat_a,
        mat_b,
        lst_a,
        recipe_a,
        swizzle_a,
        lst_b,
        recipe_b,
        swizzle_b,
        offs,
        None,
        torch.bfloat16,
        [],
        False,
    )
    res = flag_gems._scaled_grouped_mm_v2(
        mat_a,
        mat_b,
        lst_a,
        recipe_a,
        swizzle_a,
        lst_b,
        recipe_b,
        swizzle_b,
        offs,
        None,
        torch.bfloat16,
        [],
        False,
    )

    torch.testing.assert_close(
        res.float().cpu(), ref.float().cpu(), atol=2.5e-1, rtol=5e-1
    )
