# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

from flag_gems.ops.attention import flash_attention_forward

logger = logging.getLogger(__name__)


def _materialize_bshd_view(t):
    """Return ``t`` (B, S, H, D) as a transpose view of a (B, H, S, D)-contiguous
    buffer, the layout the kernel is validated against (see #5896)."""
    bhsd = t.transpose(1, 2)
    if bhsd.is_contiguous():
        return t
    return bhsd.contiguous().transpose(1, 2)


def _flash_attention_forward(
    query,
    key,
    value,
    cumulative_sequence_length_q,
    cumulative_sequence_length_k,
    max_q,
    max_k,
    dropout_p,
    is_causal,
    return_debug_mask,
    *,
    scale=None,
    window_size_left=None,
    window_size_right=None,
    seqused_k=None,
    alibi_slopes=None,
):
    """Run the canonical ATen entry through the existing
    FlashAttention implementation.
    """
    logger.debug("GEMS _FLASH_ATTENTION_FORWARD")
    query = _materialize_bshd_view(query)
    key = _materialize_bshd_view(key)
    value = _materialize_bshd_view(value)
    return flash_attention_forward(
        query,
        key,
        value,
        cumulative_sequence_length_q,
        cumulative_sequence_length_k,
        max_q,
        max_k,
        dropout_p,
        is_causal,
        return_debug_mask,
        scale=scale,
        window_size_left=window_size_left,
        window_size_right=window_size_right,
        seqused_k=seqused_k,
        alibi_slopes=alibi_slopes,
    )
