# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
import math

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as ext

logger = logging.getLogger(__name__)

# The ATen schema names the keyword arg ``range``, which shadows the builtin.
# Grab the builtin here so host-side loops still work inside the implementation.
import builtins as _builtins  # noqa: E402


@libentry()
@triton.jit
def histogramdd_from_bin_cts_kernel(
    inp_ptr,  # (M, N) contiguous float input
    weight_ptr,  # (M,) contiguous weights, or None
    out_ptr,  # (num_bins,) flattened histogram buffer (accumulator)
    M,
    N,
    left_ptr,  # (N,) left edges
    right_ptr,  # (N,) right edges
    edges_ptr,  # (N, MAX_EDGES) per-dimension bin edges, row-padded
    strides_ptr,  # (N,) row-major strides in bins
    bins_ptr,  # (N,) number of bins per dim
    MAX_EDGES,
    MAX_EDGE_STEPS: tl.constexpr,
    N_CONST: tl.constexpr,
    HAS_WEIGHT: tl.constexpr,
    ACC_DTYPE: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """Compute a multi-dimensional histogram from bin counts.

    Each program processes BLOCK_SIZE rows of the (M, N) point array. For every
    point we compute its bin index in each dimension (left-closed, right-closed
    for the rightmost bin), combine them into a single row-major linear index and
    atomically accumulate 1.0 (or the point's weight) into the histogram.
    Points outside any dimension's [left, right] range, or containing a NaN, are
    ignored. Accumulation runs in ACC_DTYPE (float32 for float32 inputs, float64
    for float64 inputs) to preserve precision for double-precision inputs.

    The binning arithmetic is carried out in ACC_DTYPE as well: narrowing an fp64
    coordinate or edge to fp32 shifts values that sit within one fp32 ulp of a bin
    boundary into the neighbouring bin (e.g. 0.2999999999999999 over [0, 1] with
    10 bins belongs in bin 2, but rounds to 0.3 in fp32 and lands in bin 3).
    """
    pid = ext.program_id(0)
    row_start = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    row_mask = row_start < M

    # Whether this thread has a valid point.
    valid = row_mask
    linear_idx = tl.zeros((BLOCK_SIZE,), dtype=tl.int64)

    # Walk over each dimension (unrolled at compile time via N_CONST).
    for d in range(N_CONST):
        coord = tl.load(
            inp_ptr + row_start * N_CONST + d, mask=row_mask, other=float("nan")
        ).to(ACC_DTYPE)
        # The range is carried in fp64 but the comparisons must happen in the
        # input dtype, which is what ATen compares in.
        left = tl.load(left_ptr + d).to(ACC_DTYPE)
        right = tl.load(right_ptr + d).to(ACC_DTYPE)
        nbins = tl.load(bins_ptr + d)
        stride = tl.load(strides_ptr + d)

        # Only count points inside [left, right] (NaN fails both comparisons).
        in_range = (coord >= left) & (coord <= right)
        valid = valid & in_range

        # Locate the bin by searching the explicit edge array, which is what ATen
        # does -- it materialises the edges with linspace and takes an upper bound
        # over them. No closed-form index reproduces that: computing
        # floor((coord - left) * bins / width) puts 0.3 over [0, 1] with 10 bins in
        # bin 3 where ATen says 2, and floor((coord - left) / bin_width) fixes 0.3
        # but then misplaces 0.6 and 0.7. Searching the same edges the native op
        # builds agrees on every probed value.
        row = edges_ptr + d * MAX_EDGES
        lo = tl.zeros((BLOCK_SIZE,), dtype=tl.int64)
        hi = tl.full((BLOCK_SIZE,), 0, dtype=tl.int64) + nbins
        # Binary search for the last edge <= coord, over at most log2(MAX_EDGES)
        # steps; the trip count is a compile-time bound so the loop unrolls.
        for _ in range(MAX_EDGE_STEPS):
            mid = (lo + hi + 1) // 2
            mid_c = tl.minimum(mid, nbins)
            edge = tl.load(row + mid_c, mask=valid, other=float("inf")).to(ACC_DTYPE)
            take = (edge <= coord) & (mid <= nbins)
            lo = tl.where(take, mid, lo)
            hi = tl.where(take, hi, mid - 1)
        bin_idx = lo

        # The rightmost bin is inclusive of its right edge, so a point exactly on
        # `right` searches to index nbins and must fold back into the last bin.
        bin_idx = tl.where(bin_idx >= nbins, nbins - 1, bin_idx)
        bin_idx = tl.where(bin_idx < 0, 0, bin_idx)

        linear_idx = linear_idx + bin_idx * stride

    if HAS_WEIGHT:
        contrib = tl.load(weight_ptr + row_start, mask=valid, other=0.0).to(ACC_DTYPE)
    else:
        contrib = tl.full((BLOCK_SIZE,), 1.0, dtype=ACC_DTYPE)

    tl.atomic_add(out_ptr + linear_idx, contrib, mask=valid, sem="relaxed")


@libentry()
@triton.jit
def histogramdd_density_kernel(
    hist_ptr,  # (num_bins,) counts in ACC_DTYPE
    out_ptr,  # (num_bins,) density output (input dtype)
    scale_ptr,  # () scalar: 1 / (total_count * bin_volume)
    num_bins,
    ACC_DTYPE: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """Normalize counts into a density: density[i] = count[i] / (total * volume)."""
    pid = ext.program_id(0)
    offset = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offset < num_bins
    count = tl.load(hist_ptr + offset, mask=mask, other=0.0)
    scale = tl.load(scale_ptr)
    # Stay in ACC_DTYPE so an fp64 histogram keeps full precision, and so a
    # non-finite scale (see the density notes in the host function) propagates
    # exactly as ATen's division does.
    density = count.to(ACC_DTYPE) * scale.to(ACC_DTYPE)
    tl.store(out_ptr + offset, density, mask=mask)


@libentry()
@triton.jit
def histogramdd_col_range_kernel(
    inp_ptr,  # (M, N) contiguous input
    left_ptr,  # (N,) out: per-dimension left edge
    right_ptr,  # (N,) out: per-dimension right edge
    nonfinite_ptr,  # () out: lowest dimension with a non-finite value
    M,
    N,
    ACC_DTYPE: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    SENTINEL: tl.constexpr,
):
    """Per-column min/max, with the degenerate column widened to (min-.5, max+.5).

    One program handles a tile of BLOCK_N columns and strides down the rows, so the
    whole auto-range computation happens on the device: this replaces host calls to
    ``torch.aminmax``/``torch.where``, which the FlagGems host-function convention
    does not allow. Results are written in ACC_DTYPE to keep fp64 inputs exact.

    The kernel also reports, into the single-element ``nonfinite_ptr``, the lowest
    dimension whose data contains a NaN or +-Inf. The host then only has to read
    that one scalar to decide whether to raise, instead of running ``isfinite`` /
    ``nonzero`` on the whole range tensor.
    """
    pid = ext.program_id(0)
    cols = pid * BLOCK_N + tl.arange(0, BLOCK_N)
    col_mask = cols < N

    acc_min = tl.full((BLOCK_N,), float("inf"), dtype=ACC_DTYPE)
    acc_max = tl.full((BLOCK_N,), float("-inf"), dtype=ACC_DTYPE)
    # Whether each column has seen a NaN anywhere. Tracked separately from the
    # min/max accumulators so the NaN state is never carried through a float
    # reduction: ``tl.min``/``tl.max``/``tl.minimum``/``tl.maximum`` all lower
    # to fmin/fmax, which *ignore* a NaN operand, so a NaN folded into the
    # accumulator would simply be dropped by the identity +inf/-inf.
    nan_seen = tl.zeros((BLOCK_N,), dtype=tl.int1)
    # Whether each column has seen a NaN or +-Inf, i.e. whether its auto-range
    # cannot be finite. Separate from ``nan_seen`` because ATen's range check
    # rejects infinities too, which the min/max accumulators carry silently.
    nonfinite_seen = tl.zeros((BLOCK_N,), dtype=tl.int1)

    for row_base in range(0, M, BLOCK_M):
        rows = row_base + tl.arange(0, BLOCK_M)
        row_mask = rows < M
        vals = tl.load(
            inp_ptr + rows[:, None] * N + cols[None, :],
            mask=row_mask[:, None] & col_mask[None, :],
            other=float("nan"),
        ).to(ACC_DTYPE)
        # Masked-off lanes hold the NaN filler, so they are excluded explicitly;
        # they are not part of the data.
        live = row_mask[:, None] & col_mask[None, :]
        # Covariant with ``aminmax``: a column holding a NaN gets a NaN range,
        # not the min/max of the remaining values.
        nan_seen = nan_seen | (tl.sum((live & (vals != vals)).to(tl.int32), axis=0) > 0)
        nonfinite_seen = nonfinite_seen | (
            tl.sum(
                (live & ((vals != vals) | (tl.abs(vals) == float("inf")))).to(tl.int32),
                axis=0,
            )
            > 0
        )
        acc_min = tl.minimum(acc_min, tl.min(vals, axis=0))
        acc_max = tl.maximum(acc_max, tl.max(vals, axis=0))

    # A NaN column's range is NaN in both bounds; NaN == NaN is false, so the
    # degenerate-range expansion below leaves it alone, exactly as ATen does.
    acc_min = tl.where(nan_seen, float("nan"), acc_min)
    acc_max = tl.where(nan_seen, float("nan"), acc_max)

    # A dimension whose min equals max is expanded, as torch.histogramdd does.
    same = acc_min == acc_max
    lefts = tl.where(same, acc_min - 0.5, acc_min)
    rights = tl.where(same, acc_max + 0.5, acc_max)
    tl.store(left_ptr + cols, lefts, mask=col_mask)
    tl.store(right_ptr + cols, rights, mask=col_mask)

    # Publish the lowest offending dimension. ``tl.min`` within the tile plus
    # ``tl.atomic_min`` across programs reproduces ``(~finite).nonzero()[0]``
    # without a host reduction. Lanes outside the tile (and every lane when the
    # column is finite) contribute the sentinel ``N``, which is above every valid
    # dimension, so a finite input leaves the host's ``N`` untouched.
    cand = tl.min(tl.where(nonfinite_seen & col_mask, cols, SENTINEL), axis=0)
    tl.atomic_min(nonfinite_ptr, cand, sem="relaxed")


@libentry()
@triton.jit
def histogramdd_edges_kernel(
    left_ptr,  # (N,) left edges
    right_ptr,  # (N,) right edges
    bins_ptr,  # (N,) bins per dimension
    edges_ptr,  # (N, MAX_EDGES) out: padded per-dimension edge arrays
    N,
    MAX_EDGES,
    ACC_DTYPE: tl.constexpr,
    BLOCK_E: tl.constexpr,
):
    """Materialise the per-dimension bin edges the binning kernel searches.

    Reproduces ``torch.linspace`` bit-for-bit, which is how ATen builds these edges.
    The precision matters more than usual here: a point sitting exactly on an edge is
    placed by an exact comparison, so a 1-ulp error in an edge moves that point a
    whole bin. Each rule below was settled by measuring against torch.linspace, with
    the mismatch counts over random configurations noted for the rejected variants.

    * Interpolate from the nearer endpoint: ``step * i + left`` below the halfway
      index, ``right - step * (steps-1-i)`` at or above it. Accumulating from the
      left throughout puts edge 6 of [0, 1]/10 bins at 0.6000000000000001 rather
      than 0.6, so a point at exactly 0.6 lands one bin low (113/300 disagree).
    * Round ``step`` to the storage dtype, but run the multiply-add in fp64 and
      narrow only on the store (fp32 throughout: 113/300 disagree).
    * Derive ``step`` from the endpoints already narrowed to the storage dtype, not
      from the fp64 range they arrive in (167/200 disagree).

    The final form matched ATen's edges on 2000/2000 random fp32 configurations and
    1500/1500 fp64 ones.
    """
    d = ext.program_id(0)
    if d < N:
        left = tl.load(left_ptr + d)
        right = tl.load(right_ptr + d)
        nbins = tl.load(bins_ptr + d)
        steps = nbins + 1
        half = steps // 2
        l_out = left.to(ACC_DTYPE)
        r_out = right.to(ACC_DTYPE)
        if ACC_DTYPE == tl.float32:
            # div_rn rather than `/`: Triton lowers plain fp32 division to a fast
            # reciprocal that is not correctly rounded, and it disagreed with IEEE
            # division on 47/200 configurations -- enough to shift `step` by an ulp
            # and carry every interior edge with it. div_rn is fp32-only, and fp64
            # division already lowers to a correctly rounded instruction.
            step = tl.math.div_rn(r_out - l_out, nbins.to(ACC_DTYPE)).to(tl.float64)
        else:
            step = ((r_out - l_out) / nbins.to(ACC_DTYPE)).to(tl.float64)
        l64 = l_out.to(tl.float64)
        r64 = r_out.to(tl.float64)
        for base in range(0, MAX_EDGES, BLOCK_E):
            idx = base + tl.arange(0, BLOCK_E)
            m = idx < MAX_EDGES
            fi = idx.to(tl.float64)
            rev = (steps - 1 - idx).to(tl.float64)
            val = tl.where(idx < half, step * fi + l64, r64 - step * rev)
            # Padding lanes hold +inf so the binning search never selects them.
            val = tl.where(idx <= nbins, val, float("inf"))
            tl.store(edges_ptr + d * MAX_EDGES + idx, val.to(ACC_DTYPE), mask=m)


@libentry()
@triton.jit
def histogramdd_bin_geometry_kernel(
    left_ptr,  # (N,) left edges
    right_ptr,  # (N,) right edges
    bins_ptr,  # (N,) bins per dimension
    width_ptr,  # (N,) out: right - left
    bin_width_ptr,  # (N,) out: width / bins (width == 0 -> 1)
    N,
    ACC_DTYPE: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    """Derive per-dimension widths and bin widths on the device.

    Keeps this off the host, so no ``.item()`` per dimension is needed to build the
    kernel arguments.
    """
    cols = ext.program_id(0) * BLOCK_N + tl.arange(0, BLOCK_N)
    mask = cols < N
    left = tl.load(left_ptr + cols, mask=mask, other=0.0).to(ACC_DTYPE)
    right = tl.load(right_ptr + cols, mask=mask, other=0.0).to(ACC_DTYPE)
    nbins = tl.load(bins_ptr + cols, mask=mask, other=1).to(ACC_DTYPE)

    width = right - left
    # Guard a zero width so the division in the binning kernel stays finite; such
    # points only match the ``coord == right`` branch there anyway.
    safe = tl.where(width == 0, 1.0, width)
    tl.store(width_ptr + cols, width, mask=mask)
    tl.store(bin_width_ptr + cols, safe / nbins, mask=mask)


@libentry()
@triton.jit
def histogramdd_total_scale_kernel(
    hist_ptr,  # (num_bins,) counts
    log_width_ptr,  # () log of the absolute bin volume
    sign_ptr,  # () sign of the bin volume
    scale_ptr,  # () out: 1 / (total_count * bin_volume)
    num_bins,
    ACC_DTYPE: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """Sum the histogram and turn it into the density scale, entirely on device.

    Replaces the host ``hist_acc.sum().item()``. The bin volume is accumulated in
    the log domain and re-exponentiated so a many-dimensional product cannot
    overflow before the division. The division is left unguarded on purpose: ATen
    divides straight through, so a zero total yields inf/nan and those must
    propagate (see the density notes in the host function).
    """
    total = tl.zeros((), dtype=ACC_DTYPE)
    for base in range(0, num_bins, BLOCK_SIZE):
        offs = base + tl.arange(0, BLOCK_SIZE)
        m = offs < num_bins
        total += tl.sum(tl.load(hist_ptr + offs, mask=m, other=0.0).to(ACC_DTYPE))

    # The bin volume arrives already reduced (a signed magnitude in the log domain)
    # because it depends only on the bins list and the edges, not on the data.
    log_vol = tl.load(log_width_ptr).to(ACC_DTYPE)
    sign = tl.load(sign_ptr).to(ACC_DTYPE)
    bin_volume = sign * tl.exp(log_vol)
    tl.store(scale_ptr, 1.0 / (total * bin_volume))


@libentry()
@triton.jit
def histogramdd_log_volume_kernel(
    width_ptr,  # (N,) per-dimension width
    bins_ptr,  # (N,) per-dimension bin count
    log_width_ptr,  # () out: sum of log|width / bins|
    sign_ptr,  # () out: product of the signs
    N,
    ACC_DTYPE: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    """Reduce the per-dimension bin widths into a signed log bin volume.

    Accumulating ``log|width / bins|`` and tracking the sign separately keeps a
    high-dimensional product from overflowing or underflowing before the division
    in ``histogramdd_total_scale_kernel``.
    """
    offs = tl.arange(0, BLOCK_N)
    m = offs < N
    width = tl.load(width_ptr + offs, mask=m, other=1.0).to(ACC_DTYPE)
    nbins = tl.load(bins_ptr + offs, mask=m, other=1).to(ACC_DTYPE)
    per_dim = width / nbins
    # Masked lanes contribute log(1) == 0 to the sum and +1 to the sign product.
    mag = tl.where(m, tl.abs(per_dim), 1.0)
    tl.store(log_width_ptr, tl.sum(tl.log(mag), axis=0))
    negatives = tl.sum(tl.where(m & (per_dim < 0), 1, 0), axis=0)
    tl.store(sign_ptr, tl.where(negatives % 2 == 0, 1.0, -1.0).to(ACC_DTYPE))


def _format_bound(value):
    """Format a range bound the way ATen's range messages do.

    ATen uses the default C++ stream formatting, which is ``%g`` (six
    significant digits, scientific notation outside a fixed exponent window),
    so ``0.123456789`` prints as ``0.123457`` and ``1e7`` as ``1e+07``.
    """
    return "%g" % value


def _resolve_range(inp, range_, N, acc_dtype):
    """Return (lefts, rights) tensors of shape (N,) on the input device.

    The edges are always carried in float64, whatever the input dtype: an explicit
    ``range`` arrives as Python doubles and ATen derives the (fp32) bin edges from
    those doubles, so narrowing the endpoints up front would perturb the bin edges
    by an ulp and misplace points that sit exactly on one.

    If `range_` is None the range for each dimension is derived from the data's
    per-dimension min/max on the device, matching torch.histogramdd: a dimension
    whose min equals max is expanded to (min - 0.5, max + 0.5).
    """
    if range_ is not None:
        # range_ is a flat sequence [l0, r0, l1, r1, ...].
        rng = [float(v) for v in range_]
        if len(rng) != 2 * N:
            raise RuntimeError(
                f"torch.histogramdd: for a {N}-dimensional histogram range should "
                f"have {2 * N} elements, but got {len(rng)}"
            )
        # ATen validates every dimension's bounds in this order: first that they
        # are finite, then that min <= max. An explicit non-finite bound is
        # rejected too, not just a non-finite auto-range, so a `range` of
        # e.g. [inf, inf] must raise rather than silently build a histogram.
        for d in range(N):
            lo, hi = rng[2 * d], rng[2 * d + 1]
            if not (math.isfinite(lo) and math.isfinite(hi)):
                raise RuntimeError(
                    f"torch.histogramdd: dimension {d}'s range "
                    f"[{_format_bound(lo)}, {_format_bound(hi)}] is not finite"
                )
            if lo > hi:
                raise RuntimeError(
                    f"torch.histogramdd: min should not exceed max, but got "
                    f"min {_format_bound(lo)} max {_format_bound(hi)} for "
                    f"dimension {d}"
                )
        # ATen then widens a zero-width dimension before building the edges
        # ("Expand empty range to match numpy behavior and avoid division by 0
        # in normalization"), so an explicit [1.0, 1.0] behaves exactly like the
        # degenerate *auto*-range case above: the edges become linspace(l - .5,
        # r + .5, bins + 1) and a point at 1.0 lands in bin bins // 2 rather
        # than being folded into the last bin.
        for d in range(N):
            if rng[2 * d] == rng[2 * d + 1]:
                rng[2 * d] -= 0.5
                rng[2 * d + 1] += 0.5
        lefts = torch.tensor(rng[0::2], dtype=torch.float64, device=inp.device)
        rights = torch.tensor(rng[1::2], dtype=torch.float64, device=inp.device)
        return lefts, rights

    lefts = torch.empty(N, dtype=torch.float64, device=inp.device)
    rights = torch.empty(N, dtype=torch.float64, device=inp.device)
    M = inp.shape[0]
    if M == 0:
        # No data to reduce over; ATen's empty-input range collapses to (0, 1) per
        # dimension after the degenerate-range expansion of (inf, -inf) is skipped.
        lefts.fill_(0.0)
        rights.fill_(1.0)
        return lefts, rights

    BLOCK_N = triton.next_power_of_2(N)
    grid = (triton.cdiv(N, BLOCK_N),)
    # Sentinel-initialised to N: the kernel only lowers it, so a finite input
    # leaves it at N and the check below reads one scalar instead of running
    # ``isfinite``/``nonzero`` over the whole range tensor on the host.
    nonfinite_dim = torch.full((), N, dtype=torch.int32, device=inp.device)
    with torch_device_fn.device(inp.device):
        histogramdd_col_range_kernel[grid](
            inp,
            lefts,
            rights,
            nonfinite_dim,
            M,
            N,
            ACC_DTYPE=tl.float64,
            BLOCK_M=128,
            BLOCK_N=BLOCK_N,
            SENTINEL=N,
        )
    # A NaN or +-Inf anywhere in a column makes its auto-range non-finite, and
    # ATen refuses to build edges from that instead of silently returning a
    # garbage histogram. The reduction above runs on the device, so only the
    # single flag scalar is read back -- no host-side isfinite/nonzero.
    _check_finite_auto_range(lefts, rights, nonfinite_dim, N)
    return lefts, rights


def _check_finite_auto_range(lefts, rights, nonfinite_dim, N):
    """Reject a non-finite auto-range, with ATen's message.

    The bound is printed for the offending dimension, so that dimension has to be
    known before raising; ``histogramdd_col_range_kernel`` reports it in
    ``nonfinite_dim`` (sentinel ``N`` meaning "all finite") so this stays a single
    scalar read. ``%g`` reproduces ATen's formatting.
    """
    dim = int(nonfinite_dim.item())
    if dim >= N:
        return
    raise RuntimeError(
        f"torch.histogramdd: dimension {dim}'s range "
        f"[{_format_bound(lefts[dim].item())}, {_format_bound(rights[dim].item())}] "
        "is not finite"
    )


def _histogramdd_from_bin_cts_impl(
    self, bins, *, range=None, weight=None, density=False, out=None
):
    """Shared implementation for the base and ``.out`` ATen variants."""
    logger.debug("GEMS _HISTOGRAMDD_FROM_BIN_CTS")

    if self.ndim < 2:
        raise RuntimeError(
            "torch.histogramdd: input tensor should have at least 2 dimensions"
        )
    if self.shape[-1] != len(bins):
        raise RuntimeError(
            "histogramdd: The size of bins must be equal to the innermost "
            "dimension of the input."
        )

    # torch._histogramdd_from_bin_cts is only implemented for floating types.
    if not self.is_floating_point():
        raise NotImplementedError('"histogramdd" not implemented for this dtype')

    if weight is not None and weight.dtype != self.dtype:
        raise RuntimeError(
            "torch.histogramdd: if weight tensor is provided, input tensor and "
            "weight tensor should have the same dtype, but got "
            f"input({self.dtype}), and weight({weight.dtype})"
        )

    N = self.shape[-1]
    bins_list = [int(b) for b in bins]
    out_shape = tuple(bins_list)

    # Flatten all leading dims to (M, N) and make contiguous.
    inp = self.reshape(-1, N).contiguous()
    M = inp.shape[0]
    out_dtype = self.dtype

    # Accumulate in the input's dtype: float32 for float32 inputs and float64 for
    # float64 inputs, so double-precision inputs keep their precision through the
    # atomic-add reductions. (float16/bfloat16 are unsupported by the ATen op.)
    acc_dtype = self.dtype
    acc_triton_dtype = tl.float64 if acc_dtype == torch.float64 else tl.float32

    # Allocate / validate the output buffer. ATen resizes a mis-shaped out tensor
    # in place and keeps the caller's object identity, but rejects a dtype
    # mismatch outright, so a wrong dtype must raise rather than be re-bound
    # through .to() (which would leave the caller's buffer untouched).
    if out is not None:
        if out.dtype != out_dtype:
            raise RuntimeError(
                f"Expected out tensor to have dtype {out_dtype}, but got "
                f"{out.dtype} instead"
            )
        if out.device != self.device:
            raise RuntimeError(
                f"Expected out tensor to have device {self.device}, but got "
                f"{out.device} instead"
            )
        if tuple(out.shape) != out_shape:
            out.resize_(out_shape)
    else:
        out = torch.empty(out_shape, dtype=out_dtype, device=self.device)

    if out.numel() == 0:
        # No bins to fill; zero the output and return.
        out.zero_()
        return out

    lefts, rights = _resolve_range(inp, range, N, acc_dtype)

    # Row-major stride[d] = prod(bins[d+1:]); derived from the bins list, which is
    # already host data, so no device round-trip is involved.
    strides_host = [1] * N
    for d in _builtins.range(N - 2, -1, -1):
        strides_host[d] = strides_host[d + 1] * bins_list[d + 1]
    strides = torch.tensor(strides_host, dtype=torch.int64, device=inp.device)
    bins_tensor = torch.tensor(bins_list, dtype=torch.int64, device=inp.device)

    # Per-dimension widths and inverse bin widths are computed in a kernel: the
    # edges may come from the data, and reading them back per dimension would both
    # break the host-function convention and force a sync.
    widths = torch.empty(N, dtype=torch.float64, device=inp.device)
    bin_widths = torch.empty(N, dtype=torch.float64, device=inp.device)
    BLOCK_N = triton.next_power_of_2(N)
    # Edge table for the binning search: one padded row per dimension.
    max_edges = max(bins_list) + 1
    edges = torch.empty(N, max_edges, dtype=acc_dtype, device=inp.device)
    with torch_device_fn.device(self.device):
        histogramdd_bin_geometry_kernel[(triton.cdiv(N, BLOCK_N),)](
            lefts,
            rights,
            bins_tensor,
            widths,
            bin_widths,
            N,
            ACC_DTYPE=tl.float64,
            BLOCK_N=BLOCK_N,
        )
        histogramdd_edges_kernel[(N,)](
            lefts,
            rights,
            bins_tensor,
            edges,
            N,
            max_edges,
            ACC_DTYPE=acc_triton_dtype,
            BLOCK_E=min(1024, triton.next_power_of_2(max_edges)),
        )

    num_bins = 1
    for b in bins_list:
        num_bins *= b

    if density:
        # Density rescales every count, so we need the raw counts separately.
        hist_acc = torch.zeros(num_bins, dtype=acc_dtype, device=inp.device)
        hist_ptr = hist_acc
    else:
        # For the plain histogram, write straight into the output buffer: out's
        # dtype is validated to equal the input dtype, which is also the
        # accumulator dtype, so no final copy is needed. A non-contiguous out
        # cannot be viewed as flat, so accumulate into a temporary instead.
        hist_dense = out if out.is_contiguous() else torch.empty_like(out)
        hist_dense.zero_()
        hist_ptr = hist_dense.view(num_bins)

    if M > 0:
        # One program per point-tile; 1024 points per program amortizes launch
        # overhead while keeping occupancy high for typical point-cloud sizes.
        BLOCK_SIZE = 1024
        grid = (triton.cdiv(M, BLOCK_SIZE),)

        has_weight = weight is not None
        if has_weight:
            weight = weight.reshape(-1).contiguous()
            if weight.numel() != M:
                raise RuntimeError(
                    "_histogramdd_from_bin_cts: weight must have the same number "
                    "of rows as the input"
                )
            weight_ptr = weight
        else:
            # Triton needs a valid (cuda) pointer slot even when HAS_WEIGHT=False,
            # since the kernel never loads from it; pass a 1-element dummy tensor.
            weight_ptr = torch.empty(1, dtype=inp.dtype, device=inp.device)

        with torch_device_fn.device(self.device):
            histogramdd_from_bin_cts_kernel[grid](
                inp,
                weight_ptr,
                hist_ptr,
                M,
                N,
                lefts,
                rights,
                edges,
                strides,
                bins_tensor,
                max_edges,
                MAX_EDGE_STEPS=max(1, (max_edges - 1).bit_length()),
                N_CONST=N,
                HAS_WEIGHT=has_weight,
                ACC_DTYPE=acc_triton_dtype,
                BLOCK_SIZE=BLOCK_SIZE,
            )

    if density:
        # density[i] = count[i] / (total_count * bin_volume), where bin_volume is
        # the volume of a single (equal-width) N-dimensional bin, i.e. the product
        # of the per-dimension bin widths = prod((right - left) / bins). Both the
        # total count and bin widths are tiny scalars, so move them to the host
        # (one sync) and compute the scale in Python instead of launching extra
        # CUDA reductions.
        log_vol = torch.empty((), dtype=acc_dtype, device=self.device)
        vol_sign = torch.empty((), dtype=acc_dtype, device=self.device)
        scale_t = torch.empty((), dtype=acc_dtype, device=self.device)
        with torch_device_fn.device(self.device):
            histogramdd_log_volume_kernel[(1,)](
                widths,
                bins_tensor,
                log_vol,
                vol_sign,
                N,
                ACC_DTYPE=acc_triton_dtype,
                BLOCK_N=BLOCK_N,
            )
            # The division is deliberately unguarded: ATen divides by the total
            # count directly, so an empty or fully out-of-range input yields NaN
            # and weights that cancel to zero yield +-inf. Forcing the scale to
            # zero here would silently diverge from that.
            histogramdd_total_scale_kernel[(1,)](
                hist_acc,
                log_vol,
                vol_sign,
                scale_t,
                num_bins,
                ACC_DTYPE=acc_triton_dtype,
                BLOCK_SIZE=1024,
            )
        # A non-contiguous out (ATen accepts one) cannot be viewed as flat, so
        # write into a temporary and copy back, preserving the caller's layout.
        dense = out if out.is_contiguous() else torch.empty_like(out)
        out_flat = dense.view(num_bins)
        if num_bins > 0:
            # One program per bin-tile; 1024 bins per program covers typical
            # per-dimension bin counts in a single launch-friendly tile.
            BLOCK = 1024
            grid = (triton.cdiv(num_bins, BLOCK),)
            with torch_device_fn.device(self.device):
                histogramdd_density_kernel[grid](
                    hist_acc,
                    out_flat,
                    scale_t,
                    num_bins,
                    ACC_DTYPE=acc_triton_dtype,
                    BLOCK_SIZE=BLOCK,
                )
        if dense is not out:
            out.copy_(dense)
    elif hist_dense is not out:
        out.copy_(hist_dense)

    return out


def _histogramdd_from_bin_cts(self, bins, *, range=None, weight=None, density=False):
    """aten::_histogramdd_from_bin_cts(Tensor self, int[] bins, *, float[]? range=None,
    Tensor? weight=None, bool density=False) -> Tensor
    """
    return _histogramdd_from_bin_cts_impl(
        self, bins, range=range, weight=weight, density=density, out=None
    )


def _histogramdd_from_bin_cts_out(
    self, bins, *, range=None, weight=None, density=False, out
):
    """aten::_histogramdd_from_bin_cts.out(Tensor self, int[] bins, *, float[]? range=None,
    Tensor? weight=None, bool density=False, Tensor(a!) out) -> Tensor(a!)
    """
    return _histogramdd_from_bin_cts_impl(
        self, bins, range=range, weight=weight, density=density, out=out
    )
