# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

from flag_gems.ops.svd import svd

logger = logging.getLogger(__name__)

# Drivers the native CUDA op accepts. Measured against `aten::_linalg_svd` on
# CUDA: "gesvd" and "gesvda" are accepted and "gesdd" is not (the CPU backend
# rejects every driver at dispatch time, so the CUDA set is the relevant one).
# The strings are case-sensitive on native.
_VALID_DRIVERS = ("gesvd", "gesvda")


def _linalg_svd(A, full_matrices=False, compute_uv=True, *, driver=None):
    """Triton implementation of ``aten::_linalg_svd``.

    Delegates to the hand-written Triton SVD kernels in ``svd.py``.

    ``aten::_linalg_svd`` is the private primitive that ``torch.linalg.svd`` /
    ``torch.linalg.svdvals`` decompose into. It returns ``(U, S, Vh)`` such that
    ``A = U diag(S) Vh``. The internal ``svd`` helper follows the ``torch.svd``
    convention and returns ``(U, S, V)`` (with ``A = U diag(S) V^H``), so we
    transpose-conjugate ``V`` to obtain ``Vh``. ``full_matrices=True``
    corresponds to ``some=False`` (full U/V matrices) in the ``torch.svd``
    convention.

    When ``compute_uv`` is ``False``, ``aten::_linalg_svd`` returns empty ``U``
    and ``Vh`` tensors (only ``S`` is materialized), unlike the ``torch.svd``
    convention which returns zero-filled factors; we honor the aten contract
    here.
    """
    logger.debug("GEMS _LINALG_SVD")
    # ``driver`` is validated before anything else, matching the CUDA native op,
    # which rejects an unknown driver regardless of the input dtype. The Triton
    # kernels have no driver concept -- they always compute the reduced SVD and
    # expand to the full factors, which is what both cuSOLVER drivers do from
    # the caller's point of view -- so a valid driver only has to be accepted,
    # not acted on.
    if driver is not None and driver not in _VALID_DRIVERS:
        raise RuntimeError(
            f"torch.linalg.svd: unknown svd driver {driver} in svd_cusolver "
            "computation. Check doc at "
            "https://pytorch.org/docs/stable/generated/torch.linalg.svd.html"
        )
    # The Triton SVD kernels only implement float32; higher/lower precision
    # matrices (e.g. float16/bfloat16) are not supported by the backend.
    if A.dtype != torch.float32:
        raise TypeError(f"_linalg_svd only supports float32 input, got {A.dtype}")
    U, S, V = svd(A, some=not full_matrices, compute_uv=compute_uv)
    if not compute_uv:
        # aten::_linalg_svd leaves U/Vh empty when compute_uv is False.
        empty = A.new_empty(0)
        return empty, S, empty
    Vh = V.mH
    return U, S, Vh
