# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

logger = logging.getLogger(__name__)


def _linalg_eigh(inp, UPLO="L", compute_v=True):
    """Eigenvalue decomposition of a symmetric/Hermitian matrix (aten entry).

    Thin dispatch to ``linalg_eigh`` that honours ``compute_v``: when False,
    only eigenvalues are computed and the eigenvectors tensor is empty.
    """
    logger.debug("GEMS _LINALG_EIGH")

    # Lazy import: linalg_eigh imports nothing from this module at module load,
    # but importing here keeps the dependency directed one way.
    from flag_gems.ops.linalg_eigh import linalg_eigh

    w, v = linalg_eigh(inp, UPLO=UPLO, compute_v=compute_v)
    return w, v
