# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry, tl_extra_shim
from flag_gems.utils import triton_lang_extension as tle

logger = logging.getLogger(__name__)

_INT_DTYPES = (torch.uint8, torch.int8, torch.int16, torch.int32, torch.int64)


@triton.jit
def _logaddexp(a, b):
    """Associative ``logaddexp`` on real scalars.

    Mirrors ``_log_add_exp_helper`` from
    ``aten/src/ATen/native/cuda/LogcumsumexpKernel.cu``.  Because the shift is
    taken against the *pairwise* maximum instead of the maximum of the whole
    row, prefixes far below the row maximum stay accurate (no underflow to
    ``-inf``), and the ``min == max`` special case reproduces ATen's handling
    of all-``+-inf`` inputs instead of producing NaN.
    """
    lo = tl.minimum(a, b)
    hi = tl.maximum(a, b)
    # ATen returns its first argument verbatim when min == max is not finite
    # (both +inf or both -inf); log1p(inf - inf) would otherwise give NaN.
    merged = tl_extra_shim.log1p(tl.exp(lo - hi)) + hi
    both_inf = (lo == hi) & (tl.abs(lo) == float("inf"))
    res = tl.where(both_inf, a, merged)
    # fmin/fmax ignore NaN operands, so NaN has to be made infectious
    # explicitly (ATen propagates it through min/max ordering).
    return tl.where((a != a) | (b != b), float("nan"), res)


@triton.jit
def _complex_log1p(x, y):
    """``c10::log1p`` for a complex number (CUDA path of c10/util/complex_math.h).

    Evaluates ``log(r) + i * atan2(y, x + 1)`` with ``r = hypot(1 + x, y)``,
    using ``log1p`` on the squared modulus for small ``|z|`` so that the
    result stays accurate near the origin.
    """
    zabs = tl_extra_shim.hypot(x, y)
    theta = tl_extra_shim.atan2(y, x + 1.0)
    r = x * (2.0 + x) + y * y
    small = tl.where(r == 0.0, x, 0.5 * tl_extra_shim.log1p(r))
    big = tl_extra_shim.log(tl_extra_shim.hypot(x + 1.0, y))
    return tl.where(zabs < 0.5, small, big), theta


@triton.jit
def _complex_exp(x, y):
    """``_fast_build_exp`` from ATen: complex exp for finite z = x + iy."""
    exp_abs = tl.exp(x)
    return exp_abs * tl.cos(y), exp_abs * tl.sin(y)


@triton.jit
def _complex_exp_pos_inf(y):
    """``_fast_build_exp_inf`` from ATen: real part is +inf, only angle matters.

    The axes are forced to zero so that ``inf * 0`` does not turn the exact
    +/-i directions into NaN.
    """
    cos_v = tl.cos(y)
    sin_v = tl.sin(y)
    real = tl.where(cos_v == 0.0, 0.0, float("inf") * cos_v)
    imag = tl.where(sin_v == 0.0, 0.0, float("inf") * sin_v)
    return real, imag


@triton.jit
def _complex_logaddexp(ar, ai, br, bi):
    """Associative complex ``logaddexp``; ATen's complex ``_log_add_exp_helper``.

    The operands are ordered by real part like ATen's
    ``_logcumsumexp_minmax`` (NaNs last), then combined as
    ``hi + log1p(exp(lo - hi))`` with ATen's dedicated +-inf branches so that
    infinite and NaN inputs keep their exact parity.
    """
    a_nan = (ar != ar) | (ai != ai)
    b_nan = (br != br) | (bi != bi)
    a_first = ar < br
    lo_r = tl.where(b_nan, br, tl.where(a_nan, ar, tl.where(a_first, ar, br)))
    lo_i = tl.where(b_nan, bi, tl.where(a_nan, ai, tl.where(a_first, ai, bi)))
    hi_r = tl.where(b_nan, br, tl.where(a_nan, ar, tl.where(a_first, br, ar)))
    hi_i = tl.where(b_nan, bi, tl.where(a_nan, ai, tl.where(a_first, bi, ai)))

    # Infectious NaNs collapse to a quiet NaN pair.
    nan_out = (lo_r != lo_r) | (lo_i != lo_i)

    # Both real parts are the same non-finite value.
    both_inf = (lo_r == hi_r) & tl_extra_shim.isinf(lo_r)
    neg_inf = both_inf & (lo_r < 0.0)

    # Generic branch.
    e_r, e_i = _complex_exp(lo_r - hi_r, lo_i - hi_i)
    l_r, l_i = _complex_log1p(e_r, e_i)
    gen_r = l_r + hi_r
    gen_i = l_i + hi_i

    # +inf branch: log1p(exp(lo) + exp(hi) - 1) with infinite-modulus
    # exponentials, which is how ATen avoids NaN here.
    e1_r, e1_i = _complex_exp_pos_inf(lo_i)
    e2_r, e2_i = _complex_exp_pos_inf(hi_i)
    p_r, p_i = _complex_log1p(e1_r + e2_r - 1.0, e1_i + e2_i)

    out_r = tl.where(
        nan_out, float("nan"), tl.where(neg_inf, lo_r, tl.where(both_inf, p_r, gen_r))
    )
    out_i = tl.where(
        nan_out, float("nan"), tl.where(neg_inf, lo_i, tl.where(both_inf, p_i, gen_i))
    )
    return out_r, out_i


@libentry()
@triton.jit
def _logcumsumexp_kernel(
    inp, out, N, S, BLOCK_SIZE: tl.constexpr, IS_FP64: tl.constexpr
):
    """One program per (outer, inner) pair; scans N elements strided by S.

    The input is treated as a contiguous (M, N, K) tensor with ``S == K``, so
    the scanned row of program ``(m, k)`` starts at ``m*N*K + k`` and advances
    with stride ``K``.

    Used for rows no longer than ``_MAX_SINGLE_BLOCK``. Longer rows are handled
    by :func:`_logcumsumexp_chunk_kernel` + :func:`_logcumsumexp_fanin_kernel`,
    which keep the per-program block fixed instead of growing it with N.
    """
    pid_m = tle.program_id(0)
    pid_k = tle.program_id(1)
    base = pid_m * N * S + pid_k

    offsets = tl.arange(0, BLOCK_SIZE)
    mask = offsets < N
    x = tl.load(inp + base + offsets * S, mask=mask, other=0)
    if IS_FP64:
        x = x.to(tl.float64)
    else:
        x = x.to(tl.float32)
    # Padding lanes must not contribute to the scan.
    x = tl.where(mask, x, float("-inf"))

    result = tl.associative_scan(x, 0, _logaddexp)
    tl.store(out + base + offsets * S, result.to(out.dtype.element_ty), mask=mask)


@triton.jit
def _row_base(pid_r, N, K):
    """Start offset of the ``pid_r``-th scanned row of an (M, N, K) tensor.

    The scanned axis is the middle one, so row ``r = m*K + k`` starts at
    ``m*N*K + k``. Deriving it from ``r`` alone keeps the row factorization out
    of the kernel signature.
    """
    return (pid_r // K) * N * K + (pid_r % K)


@libentry()
@triton.jit
def _logcumsumexp_chunk_kernel(
    inp,
    out,
    chunk_total,
    N,
    K,
    num_chunks,
    CHUNK: tl.constexpr,
    IS_FP64: tl.constexpr,
):
    """Scan one chunk of one row and record the chunk's running total.

    ``K`` is the trailing size (the row stride) and ``CHUNK`` the number of
    elements per chunk, so the tile that is scanned is always ``CHUNK`` wide
    regardless of the row length: a long row becomes more programs, not a bigger
    -- and exponentially more expensive to compile -- block.

    ``chunk_total[r, j]`` holds the logaddexp total of chunks ``0..j`` of row
    ``r``, which is what the fan-in pass consumes.
    """
    pid_r = tle.program_id(0)
    pid_j = tle.program_id(1)
    base = _row_base(pid_r, N, K)

    offsets = pid_j * CHUNK + tl.arange(0, CHUNK)
    mask = offsets < N
    x = tl.load(inp + base + offsets * K, mask=mask, other=0)
    if IS_FP64:
        x = x.to(tl.float64)
    else:
        x = x.to(tl.float32)
    # Padding lanes are the identity of logaddexp, so the scan is unaffected.
    x = tl.where(mask, x, float("-inf"))

    res = tl.associative_scan(x, 0, _logaddexp)
    tl.store(out + base + offsets * K, res.to(out.dtype.element_ty), mask=mask)
    # The chunk total is the inclusive scan's last lane. It is picked by a
    # masked sum rather than by ``tl.max``, which would be wrong here: max
    # ignores NaN operands, and the chunk total is exactly what has to carry
    # the NaN state (and the +-inf branches) into the following chunks. Adding
    # the zeros of the masked-out lanes is exact, so the surviving lane is
    # returned unchanged; chunks are full except possibly the tail one, whose
    # padding lanes hold -inf and cannot be selected.
    last_lane_mask = tl.arange(0, CHUNK) == (CHUNK - 1)
    total = tl.sum(tl.where(last_lane_mask, res, 0.0), axis=0)
    tl.store(chunk_total + pid_r * num_chunks + pid_j, total)


@libentry()
@triton.jit
def _logcumsumexp_fanin_kernel(
    out,
    chunk_total,
    N,
    K,
    num_chunks,
    CHUNK: tl.constexpr,
    IS_FP64: tl.constexpr,
):
    """Shift each chunk by the logaddexp of all preceding chunk totals.

    Chunk ``j``'s carry-in is the running ``logaddexp`` of the totals of chunks
    ``0..j-1``; because ``logaddexp`` is associative, applying that carry with a
    single combine is exact, so the chunked result is the value a whole-row scan
    would produce.
    """
    pid_r = tle.program_id(0)
    pid_j = tle.program_id(1)
    base = _row_base(pid_r, N, K)
    acc_ty = tl.float64 if IS_FP64 else tl.float32

    carry = tl.full((), float("-inf"), dtype=acc_ty)
    for j in range(0, pid_j):
        t = tl.load(chunk_total + pid_r * num_chunks + j)
        carry = _logaddexp(carry, t.to(acc_ty))

    offsets = pid_j * CHUNK + tl.arange(0, CHUNK)
    mask = offsets < N
    res = tl.load(out + base + offsets * K, mask=mask, other=0).to(acc_ty)
    shifted = _logaddexp(carry, tl.where(mask, res, float("-inf")))
    tl.store(out + base + offsets * K, shifted.to(out.dtype.element_ty), mask=mask)


@libentry()
@triton.jit
def _logcumsumexp_complex_chunk_kernel(
    inp,
    out,
    chunk_total_r,
    chunk_total_i,
    N,
    K,
    num_chunks,
    CHUNK: tl.constexpr,
    IS_FP64: tl.constexpr,
    REAL_INPUT: tl.constexpr,
):
    """Complex counterpart of :func:`_logcumsumexp_chunk_kernel`.

    The chunked path needs its own complex kernel: ``out`` is the real view
    ``(..., 2)`` here, so running the *real* chunk kernels over that buffer would
    scan the interleaved re/im parts as independent real numbers and produce
    garbage (complex64 N=8192 disagreed with ATen by ~9.6, complex128 N=5000 by
    ~5.5e5). Each chunk therefore scans pairs through ``_complex_logaddexp``.
    """
    pid_r = tle.program_id(0)
    pid_j = tle.program_id(1)
    base = _row_base(pid_r, N, K)

    offsets = pid_j * CHUNK + tl.arange(0, CHUNK)
    mask = offsets < N
    src = base + offsets * K
    dst = src * 2
    if REAL_INPUT:
        xr = tl.load(inp + src, mask=mask, other=0)
        xi = xr * 0.0
    else:
        xr = tl.load(inp + dst, mask=mask, other=0)
        xi = tl.load(inp + dst + 1, mask=mask, other=0)
    if IS_FP64:
        xr = xr.to(tl.float64)
        xi = xi.to(tl.float64)
    else:
        xr = xr.to(tl.float32)
        xi = xi.to(tl.float32)
    # (-inf, 0) is an identity of ``_complex_logaddexp`` on both sides: it is
    # ordered last by real part, so the generic branch gives
    # ``hi + log1p(exp(lo - hi)) == hi`` exactly, and the +-inf branch returns
    # ``lo`` verbatim. Padding is therefore invisible to the scan.
    xr = tl.where(mask, xr, float("-inf"))
    xi = tl.where(mask, xi, 0.0)

    res_r, res_i = tl.associative_scan((xr, xi), 0, _complex_logaddexp)
    tl.store(out + dst, res_r.to(out.dtype.element_ty), mask=mask)
    tl.store(out + dst + 1, res_i.to(out.dtype.element_ty), mask=mask)
    # Same masked-sum extraction of the last lane as the real chunk kernel: a
    # ``tl.max`` would drop the NaN state (and pick the wrong branch) at the
    # chunk boundary. The tail chunk's padding lane makes this total useless,
    # but the fan-in never reads the last chunk's total.
    last_lane_mask = tl.arange(0, CHUNK) == (CHUNK - 1)
    total_r = tl.sum(tl.where(last_lane_mask, res_r, 0.0), axis=0)
    total_i = tl.sum(tl.where(last_lane_mask, res_i, 0.0), axis=0)
    tl.store(chunk_total_r + pid_r * num_chunks + pid_j, total_r)
    tl.store(chunk_total_i + pid_r * num_chunks + pid_j, total_i)


@libentry()
@triton.jit
def _logcumsumexp_complex_fanin_kernel(
    out,
    chunk_total_r,
    chunk_total_i,
    N,
    K,
    num_chunks,
    CHUNK: tl.constexpr,
    IS_FP64: tl.constexpr,
):
    """Shift each complex chunk by the complex logaddexp of the earlier chunks."""
    pid_r = tle.program_id(0)
    pid_j = tle.program_id(1)
    base = _row_base(pid_r, N, K)
    acc_ty = tl.float64 if IS_FP64 else tl.float32

    carry_r = tl.full((), float("-inf"), dtype=acc_ty)
    carry_i = tl.zeros((), dtype=acc_ty)
    for j in range(0, pid_j):
        tr = tl.load(chunk_total_r + pid_r * num_chunks + j).to(acc_ty)
        ti = tl.load(chunk_total_i + pid_r * num_chunks + j).to(acc_ty)
        carry_r, carry_i = _complex_logaddexp(carry_r, carry_i, tr, ti)

    offsets = pid_j * CHUNK + tl.arange(0, CHUNK)
    mask = offsets < N
    dst = (base + offsets * K) * 2
    res_r = tl.load(out + dst, mask=mask, other=0).to(acc_ty)
    res_i = tl.load(out + dst + 1, mask=mask, other=0).to(acc_ty)
    res_r = tl.where(mask, res_r, float("-inf"))
    res_i = tl.where(mask, res_i, 0.0)
    sh_r, sh_i = _complex_logaddexp(carry_r, carry_i, res_r, res_i)
    tl.store(out + dst, sh_r.to(out.dtype.element_ty), mask=mask)
    tl.store(out + dst + 1, sh_i.to(out.dtype.element_ty), mask=mask)


@libentry()
@triton.jit
def _logcumsumexp_complex_kernel(
    inp,
    out,
    N,
    S,
    BLOCK_SIZE: tl.constexpr,
    IS_FP64: tl.constexpr,
    REAL_INPUT: tl.constexpr,
):
    """Complex variant; ``out`` is the real view ``(..., 2)`` of the result.

    ``REAL_INPUT`` marks real data promoted to a complex result
    (``dtype=torch.complex64`` on a real input): ``inp`` is then a plain real
    buffer holding one element per logical value with a zero imaginary part,
    whereas a complex input arrives as its ``(..., 2)`` real view.
    """
    pid_m = tle.program_id(0)
    pid_k = tle.program_id(1)
    base = pid_m * N * S + pid_k

    offsets = tl.arange(0, BLOCK_SIZE)
    mask = offsets < N
    src = base + offsets * S
    dst = src * 2
    if REAL_INPUT:
        xr = tl.load(inp + src, mask=mask, other=0)
        xi = xr * 0.0
    else:
        xr = tl.load(inp + dst, mask=mask, other=0)
        xi = tl.load(inp + dst + 1, mask=mask, other=0)
    if IS_FP64:
        xr = xr.to(tl.float64)
        xi = xi.to(tl.float64)
    else:
        xr = xr.to(tl.float32)
        xi = xi.to(tl.float32)
    xr = tl.where(mask, xr, float("-inf"))
    xi = tl.where(mask, xi, 0.0)

    res_r, res_i = tl.associative_scan((xr, xi), 0, _complex_logaddexp)
    tl.store(out + dst, res_r.to(out.dtype.element_ty), mask=mask)
    tl.store(out + dst + 1, res_i.to(out.dtype.element_ty), mask=mask)


def _normalize_dim(inp, dim):
    # ``maybe_wrap_dim`` treats a 0-dim tensor as if it had one dimension, so
    # a scalar accepts dim=0 as well as dim=-1.
    ndim = max(inp.ndim, 1)
    if dim < -ndim or dim >= ndim:
        raise IndexError(
            f"Dimension out of range (expected to be in range of [{-ndim}, "
            f"{ndim - 1}], but got {dim})"
        )
    return dim % ndim


def _resolve_dtype(inp, dtype):
    if dtype is None:
        dtype = inp.dtype
    if dtype in _INT_DTYPES or dtype == torch.bool:
        dtype = torch.float32
    return dtype


def _real_view(tensor):
    """Real, contiguous buffer the kernel can address with linear offsets."""
    tensor = tensor.contiguous()
    if tensor.is_complex():
        return torch.view_as_real(tensor)
    return tensor


# Rows longer than this are scanned in fixed-size chunks. The value is the
# largest block whose ``tl.associative_scan`` still compiles quickly (~1 s
# measured on H20); above it compile time grows steeply for no benefit, since a
# bigger block is not what makes the scan faster.
_MAX_SINGLE_BLOCK = 4096

# Elements per chunk on the chunked path. Each chunk scans one block of this
# width, and the inter-chunk carry is applied by a second pass.
_CHUNK_ELEMS = 4096

# The complex chunked path uses a narrower tile: the complex combine's compile
# time grows much more steeply with the block width than the real one's (~20 s
# at 1024 vs ~100 s at 4096, measured on H20), and the smaller tile is also
# slightly faster to run (0.0003 s vs 0.0006 s warm at N=16384). The real path
# keeps the wide tile because there the compile is ~1 s either way.
_CHUNK_ELEMS_COMPLEX = 1024


def _chunked_scan(
    src_view, dst_view, N, K, M, acc_is_fp64, inp, is_complex, real_input
):
    """Two-pass chunked scan for rows longer than ``_MAX_SINGLE_BLOCK``.

    Pass 1 scans every chunk independently and records each chunk's running
    total; pass 2 computes each chunk's carry-in from the totals of the chunks
    before it and shifts the chunk by that carry. ``logaddexp`` is associative,
    so this reproduces a whole-row scan exactly while keeping the compiled tile
    at ``_CHUNK_ELEMS`` for any row length.

    The scanned rows are the ``M*K`` pairs of the (M, N, K) factorization, so
    the grid's first axis is that product and each program derives its own row
    base from it.

    Complex inputs need the complex kernels: ``dst_view`` is then the ``(..., 2)``
    real view, and the real kernels would scan the interleaved re/im parts as
    independent real numbers instead of combining complex pairs.
    """
    rows = M * K
    chunk = min(
        _CHUNK_ELEMS_COMPLEX if is_complex else _CHUNK_ELEMS,
        triton.next_power_of_2(N),
    )
    num_chunks = triton.cdiv(N, chunk)
    total_dtype = torch.float64 if acc_is_fp64 else torch.float32
    chunk_total = torch.empty(rows, num_chunks, dtype=total_dtype, device=inp.device)

    warps = 8 if chunk > 2048 else 4
    with torch_device_fn.device(inp.device):
        if is_complex:
            # The imaginary totals are a separate buffer rather than a second
            # row of ``chunk_total``: the two are consumed as distinct kernel
            # arguments by the fan-in.
            chunk_total_i = torch.empty(
                rows, num_chunks, dtype=total_dtype, device=inp.device
            )
            _logcumsumexp_complex_chunk_kernel[(rows, num_chunks)](
                src_view,
                dst_view,
                chunk_total,
                chunk_total_i,
                N,
                K,
                num_chunks,
                CHUNK=chunk,
                IS_FP64=acc_is_fp64,
                REAL_INPUT=real_input,
                num_warps=warps,
            )
            _logcumsumexp_complex_fanin_kernel[(rows, num_chunks)](
                dst_view,
                chunk_total,
                chunk_total_i,
                N,
                K,
                num_chunks,
                CHUNK=chunk,
                IS_FP64=acc_is_fp64,
                num_warps=warps,
            )
            return
        _logcumsumexp_chunk_kernel[(rows, num_chunks)](
            src_view,
            dst_view,
            chunk_total,
            N,
            K,
            num_chunks,
            CHUNK=chunk,
            IS_FP64=acc_is_fp64,
            num_warps=warps,
        )
        _logcumsumexp_fanin_kernel[(rows, num_chunks)](
            dst_view,
            chunk_total,
            N,
            K,
            num_chunks,
            CHUNK=chunk,
            IS_FP64=acc_is_fp64,
            num_warps=warps,
        )


def _logcumsumexp_wrapper(inp, dim=1, dtype=None, out=None):
    if not isinstance(dim, int):
        raise TypeError(f"dim must be an int, but got {type(dim).__name__}")
    dim = _normalize_dim(inp, dim)

    result_dtype = _resolve_dtype(inp, dtype)
    if inp.is_complex() and not result_dtype.is_complex:
        raise RuntimeError(
            "logcumsumexp: cannot compute a complex input into the real dtype "
            f"{result_dtype}"
        )

    if out is None:
        out = torch.empty(inp.shape, dtype=result_dtype, device=inp.device)
    else:
        # ``out=`` contract: same device, same dtype, resized shape, and the
        # caller's tensor (not a replacement) comes back.
        if out.device != inp.device:
            raise RuntimeError(
                "Expected all tensors to be on the same device, but got self "
                f"is on {inp.device}, different from other tensors on {out.device}"
            )
        if out.dtype != result_dtype:
            raise RuntimeError(
                f"out must have dtype {result_dtype}, but got {out.dtype}"
            )
        if tuple(out.shape) != tuple(inp.shape):
            out.resize_(inp.shape)

    if inp.numel() == 0:
        return out

    # Factor the logical (M, N, K) scan geometry: the scanned axis is the
    # middle one, M is the product of the leading dims, K the trailing ones.
    ndim = max(inp.ndim, 1)
    shape = list(inp.shape) if inp.ndim else [1]
    M = 1
    for i in range(dim):
        M *= shape[i]
    N = shape[dim]
    K = 1
    for i in range(dim + 1, ndim):
        K *= shape[i]

    is_complex = out.is_complex()
    acc_is_fp64 = result_dtype in (torch.float64, torch.complex128)

    # A non-contiguous output cannot be addressed linearly, so compute into a
    # contiguous scratch buffer and copy back; the caller's layout and buffer
    # are preserved.
    if out.is_contiguous():
        target = out
        scratch = None
    else:
        target = torch.empty(inp.shape, dtype=result_dtype, device=inp.device)
        scratch = out

    src_view = _real_view(inp)
    dst_view = _real_view(target)

    # A single program would have to scan the whole row, and
    # ``tl.associative_scan`` compile time grows steeply with the block size
    # (measured: ~4 s at N=8192, ~24 s at 32768, ~5 min at 131072), so long rows
    # are split into fixed-size chunks instead -- the row length then only
    # selects the grid, not the compiled tile.
    if N > _MAX_SINGLE_BLOCK:
        _chunked_scan(
            src_view,
            dst_view,
            N,
            K,
            M,
            acc_is_fp64,
            inp,
            is_complex,
            not inp.is_complex(),
        )
    else:
        BLOCK_SIZE = triton.next_power_of_2(N)
        num_warps = 8 if BLOCK_SIZE > 2048 else 4
        grid = (M, K)
        with torch_device_fn.device(inp.device):
            if is_complex:
                _logcumsumexp_complex_kernel[grid](
                    src_view,
                    dst_view,
                    N,
                    K,
                    BLOCK_SIZE,
                    acc_is_fp64,
                    not inp.is_complex(),
                    num_warps=num_warps,
                )
            else:
                _logcumsumexp_kernel[grid](
                    src_view,
                    dst_view,
                    N,
                    K,
                    BLOCK_SIZE,
                    acc_is_fp64,
                    num_warps=num_warps,
                )

    if scratch is not None:
        scratch.copy_(target)
        return scratch
    return out


def _logcumsumexp(inp, dim=1, *, dtype=None):
    logger.debug("GEMS _LOGCUMSUMEXP")
    return _logcumsumexp_wrapper(inp, dim, dtype)


def _logcumsumexp_out(inp, dim=1, *, dtype=None, out):
    logger.debug("GEMS _LOGCUMSUMEXP_OUT")
    return _logcumsumexp_wrapper(inp, dim, dtype, out)
