# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)

# `aten::_philox_normal_` is part of PyTorch's stateless Philox RNG family,
# which landed upstream after the 2.10 release. Builds that predate it ship no
# schema for the operator, and FlagGems' registrar refuses to install an
# implementation for an unknown schema. Define the upstream signature verbatim
# when it is missing so the operator can still be registered and exercised;
# on newer torch builds the guard short-circuits.
_PHILOX_NORMAL_SCHEMA = (
    "(Tensor(a!) self, Tensor key, float mean=0, float std=1) -> Tensor(a!)"
)


def _ensure_philox_normal_schema():
    if hasattr(torch.ops.aten, "_philox_normal_"):
        return
    try:
        torch.library.define("aten::_philox_normal_", _PHILOX_NORMAL_SCHEMA)
    except Exception as exc:  # pragma: no cover - depends on the torch build
        logger.warning("Unable to define aten::_philox_normal_: %s", exc)


_ensure_philox_normal_schema()


@triton.jit
def _box_muller_f32(r0, r1, r2, r3):
    """Pair four Philox words into four standard normals, in float32.

    Mirrors ``box_muller_float`` from cuda/PhiloxDistribution.cu: each word
    becomes a uniform in (0, 1] through the fused multiply-add
    ``fmaf(word, 2**-32, 2**-33)``, odd-indexed words turn into angles and
    even-indexed ones into radii, and words 0/1 and 2/3 form the two
    (cosine, sine) pairs. Both constants are powers of two, so the mapping is
    exact.
    """
    u1 = tl.fma(r0.to(tl.float32), 2.3283064365386963e-10, 1.1641532182693481e-10)
    u2 = tl.fma(r1.to(tl.float32), 2.3283064365386963e-10, 1.1641532182693481e-10)
    u3 = tl.fma(r2.to(tl.float32), 2.3283064365386963e-10, 1.1641532182693481e-10)
    u4 = tl.fma(r3.to(tl.float32), 2.3283064365386963e-10, 1.1641532182693481e-10)

    radius1 = tl.sqrt(-2.0 * tl.log(u1))
    radius2 = tl.sqrt(-2.0 * tl.log(u3))
    theta1 = 6.2831853071795864 * u2
    theta2 = 6.2831853071795864 * u4

    return (
        radius1 * tl.cos(theta1),
        radius1 * tl.sin(theta1),
        radius2 * tl.cos(theta2),
        radius2 * tl.sin(theta2),
    )


@triton.jit
def _box_muller_f64(r0, r1, r2, r3):
    """Pair four Philox words into two standard normals, in float64.

    Mirrors ``box_muller_double``: each normal spends two words, packed into
    roughly 64 bits of uniform randomness instead of 32, so one Philox call
    yields two samples rather than four.
    """
    m = 2.3283064365386963e-10
    u1 = tl.fma(r0.to(tl.float64), m, r1.to(tl.float64) * m * m + m * m * 0.5)
    u2 = tl.fma(r2.to(tl.float64), m, r3.to(tl.float64) * m * m + m * m * 0.5)

    radius = tl.sqrt(-2.0 * tl.log(u1))
    theta = 6.2831853071795864 * u2

    return radius * tl.cos(theta), radius * tl.sin(theta)


@triton.jit
def _philox_normal_kernel(
    out_ptr,
    key_ptr,
    N,
    mean,
    std,
    BLOCK: tl.constexpr,
):
    """Fill ``out_ptr`` with normal samples from a stateless Philox stream.

    ``key_ptr`` addresses a ``(seed, offset)`` pair. Output element ``i`` comes
    from the ``i // 4``-th Philox 4x32 counter value, so each lane owns one
    counter and writes the four normals it yields. ``mean``/``std`` are the
    float32 scalars ATen uses as its accumulator for every 16/32-bit output.
    """
    seed = tl.load(key_ptr).to(tl.uint64)
    offset = tl.load(key_ptr + 1).to(tl.uint64)
    # tl.cast rather than ``N.to``: Triton specializes small integer arguments
    # such as 1 into constexprs, which have no ``.to``.
    N = tl.cast(N, tl.int64)
    # Element counts can exceed 2**31, so every offset stays 64-bit; an int32
    # product here would wrap and let the masked stores run past the buffer.
    chunk = (tl.program_id(0).to(tl.int64)) * BLOCK + tl.arange(0, BLOCK).to(tl.int64)
    counter = offset + chunk.to(tl.uint64)
    c0 = (counter & 0xFFFFFFFF).to(tl.uint32)
    c1 = ((counter >> 32) & 0xFFFFFFFF).to(tl.uint32)
    zero = c0 * 0
    r0, r1, r2, r3 = tl.philox(seed, c0, c1, zero, zero)

    n0, n1, n2, n3 = _box_muller_f32(r0, r1, r2, r3)
    dtype = out_ptr.dtype.element_ty
    base = chunk * 4
    tl.store(out_ptr + base, tl.fma(n0, std, mean).to(dtype), mask=base < N)
    tl.store(out_ptr + base + 1, tl.fma(n1, std, mean).to(dtype), mask=base + 1 < N)
    tl.store(out_ptr + base + 2, tl.fma(n2, std, mean).to(dtype), mask=base + 2 < N)
    tl.store(out_ptr + base + 3, tl.fma(n3, std, mean).to(dtype), mask=base + 3 < N)


@triton.jit
def _philox_normal_kernel_f64(
    out_ptr,
    key_ptr,
    params_ptr,
    N,
    BLOCK: tl.constexpr,
):
    """float64 variant of ``_philox_normal_kernel``.

    ``params_ptr`` addresses a ``(mean, std)`` pair of doubles. They arrive as
    a device tensor rather than Python floats because Triton narrows float
    kernel arguments to float32, which would drop the low mantissa bits of an
    arbitrary mean/std.
    """
    seed = tl.load(key_ptr).to(tl.uint64)
    offset = tl.load(key_ptr + 1).to(tl.uint64)
    mean = tl.load(params_ptr)
    std = tl.load(params_ptr + 1)
    # tl.cast rather than ``N.to``: Triton specializes small integer arguments
    # such as 1 into constexprs, which have no ``.to``.
    N = tl.cast(N, tl.int64)
    chunk = (tl.program_id(0).to(tl.int64)) * BLOCK + tl.arange(0, BLOCK).to(tl.int64)
    counter = offset + chunk.to(tl.uint64)
    c0 = (counter & 0xFFFFFFFF).to(tl.uint32)
    c1 = ((counter >> 32) & 0xFFFFFFFF).to(tl.uint32)
    zero = c0 * 0
    r0, r1, r2, r3 = tl.philox(seed, c0, c1, zero, zero)

    n0, n1 = _box_muller_f64(r0, r1, r2, r3)
    base = chunk * 2
    tl.store(out_ptr + base, tl.fma(n0, std, mean), mask=base < N)
    tl.store(out_ptr + base + 1, tl.fma(n1, std, mean), mask=base + 1 < N)


def _launch(out, key, mean, std):
    n = out.numel()
    if out.dtype == torch.float64:
        # ATen accumulates 8-byte outputs in double, so the parameters are
        # cast to double before they reach the kernel.
        params = torch.tensor([mean, std], dtype=torch.float64, device=out.device)
        # Two elements per Philox call, so each lane covers half as much as in
        # the 16/32-bit path.
        grid = (triton.cdiv(n, 128 * 2),)
        with torch_device_fn.device(out.device):
            _philox_normal_kernel_f64[grid](out, key, params, n, BLOCK=128, num_warps=4)
        return
    grid = (triton.cdiv(n, 512 * 4),)
    with torch_device_fn.device(out.device):
        _philox_normal_kernel[grid](out, key, n, mean, std, BLOCK=512, num_warps=4)


def _check_args(self, key):
    if not self.is_floating_point():
        raise RuntimeError(
            f"_philox_normal_: self must be a floating point tensor, got {self.dtype}"
        )
    if key.dtype != torch.uint64:
        raise RuntimeError(
            f"_philox_normal_: key must have dtype uint64, got {key.dtype}"
        )
    if self.device != key.device:
        raise RuntimeError(
            f"_philox_normal_: self and key must be on the same device, got "
            f"{self.device} and {key.device}"
        )
    if key.dim() < 1 or key.size(-1) != 2:
        raise RuntimeError(
            f"_philox_normal_: key must have shape (2,) or (*batch, 2), got "
            f"{tuple(key.shape)}"
        )
    if key.dim() > 1 and key.dim() != self.dim() + 1:
        raise RuntimeError(
            f"_philox_normal_: batched key must have ndim == output ndim + 1, got "
            f"key shape {tuple(key.shape)} with output shape {tuple(self.shape)}"
        )


def _batched_key_plan(out, key):
    """Split a batched key into per-key output blocks and key indices.

    ATen derives the elements one key owns by counting the output's trailing
    dimensions that the key leaves unsized (``key.size(i) == 1``); a key with
    shape ``(4, 1, 1, 2)`` against output ``(4, 10, 100)`` therefore feeds 1000
    elements. The remaining key dimensions broadcast, so the key index for a
    block is the flat index of a zero-based multi-index along those dims.
    """
    elems_per_key = 1
    key_dims = out.dim()
    for i in range(out.dim() - 1, -1, -1):
        if key.size(i) != 1:
            break
        elems_per_key *= out.size(i)
        key_dims -= 1

    key_batch = tuple(key.shape[:key_dims])
    out_batch = tuple(out.shape[:key_dims])
    for ks, os_ in zip(key_batch, out_batch):
        if ks != os_ and ks != 1:
            raise RuntimeError(
                f"_philox_normal_: key batch shape {key_batch} is not "
                f"broadcastable with output shape {out_batch}"
            )

    num_blocks = out.numel() // elems_per_key
    # Walk the batch dims in output order, advancing the key's flat index only
    # where the key is actually sized (broadcast dims keep their index).
    strides = []
    acc = 1
    for ks in reversed(key_batch):
        strides.append(0 if ks == 1 else acc)
        acc *= ks
    strides.reverse()

    block = []
    for b in range(num_blocks):
        idx = 0
        rem = b
        for dim in range(key_dims - 1, -1, -1):
            size = out_batch[dim]
            coord = rem % size if size else 0
            rem //= size if size else 1
            idx += coord * strides[dim]
        block.append(idx)
    return elems_per_key, block


def _philox_normal_(self, key, mean=0.0, std=1.0):
    logger.debug("GEMS _PHILOX_NORMAL_")
    _check_args(self, key)
    if self.numel() == 0:
        return self

    key = key.contiguous()
    # Non-contiguous outputs are filled through a contiguous staging buffer and
    # copied back, so the kernel can rely on plain linear indexing.
    contiguous = self.is_contiguous()
    out = self if contiguous else self.contiguous()

    if key.dim() == 1:
        _launch(out, key, mean, std)
    else:
        elems_per_key, block_keys = _batched_key_plan(out, key)
        key_flat = key.reshape(-1, 2)
        out_flat = out.reshape(-1, elems_per_key)
        for block_idx, key_idx in enumerate(block_keys):
            _launch(out_flat[block_idx], key_flat[key_idx], mean, std)

    if not contiguous:
        self.copy_(out)
    return self
