# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

logger = logging.getLogger(__name__)


def _pin_memory(self: torch.Tensor, device=None) -> torch.Tensor:
    """Return a pinned-memory copy of a strided CPU tensor."""
    logger.debug("GEMS _PIN_MEMORY")
    if self.device.type != "cpu":
        raise RuntimeError("cannot pin a tensor that is not on the CPU")
    if device is not None and torch.device(device).type != "cuda":
        raise RuntimeError(f"{torch.device(device).type.upper()} is not an accelerator")
    if self.layout != torch.strided:
        raise RuntimeError("_pin_memory currently supports strided tensors only")

    result = torch.empty_strided(
        self.size(),
        self.stride(),
        dtype=self.dtype,
        layout=self.layout,
        device="cpu",
        pin_memory=True,
    )
    result.copy_(self)
    return result
