# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, "DEFAULT")])
@triton.jit
def saturate_weight_to_fp16_func(x):
    # Clamp values to fp16 representable range [-65504.0, 65504.0]
    # Use ALL to preserve NaN values
    x_f32 = x.to(tl.float32)
    clamped = tl.minimum(
        65504.0,
        tl.maximum(-65504.0, x_f32, propagate_nan=tl.PropagateNan.ALL),
        propagate_nan=tl.PropagateNan.ALL,
    )
    return clamped.to(x.dtype)


def _saturate_weight_to_fp16(A):
    logger.debug("GEMS _SATURATE_WEIGHT_TO_FP16")
    return saturate_weight_to_fp16_func(A)
