# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch

from flag_gems.ops.flash_attention_backward import _parse_philox, flash_attn_backward

logger = logging.getLogger(__name__)


def scaled_dot_product_fused_attention_overrideable_backward(
    grad_out,
    query,
    key,
    value,
    attn_bias,
    grad_input_mask,
    out,
    logsumexp,
    cum_seq_q,
    cum_seq_k,
    max_q,
    max_k,
    dropout_p,
    is_causal,
    philox_seed,
    philox_offset,
    *,
    scale=None,
):
    logger.debug("GEMS _scaled_dot_product_fused_attention_overrideable_backward")

    need_dq, need_dk, need_dv, need_dbias = grad_input_mask

    is_dropout = dropout_p > 0.0
    rng_tuple = None
    if is_dropout:
        if philox_seed is None or philox_offset is None:
            raise ValueError(
                "philox_seed and philox_offset are required when dropout_p > 0"
            )
        rng_tuple = _parse_philox(philox_seed, philox_offset)

    use_varlen = (cum_seq_q is not None) and (cum_seq_k is not None)
    bias_req_grad = bool(need_dbias) and (attn_bias is not None)

    if use_varlen:
        # Varlen inputs are (Total, H, D), already the layout the kernel expects.
        dQ, dK, dV, dBias = flash_attn_backward(
            grad_out,
            query,
            key,
            value,
            out,
            logsumexp.float(),
            cu_seq_q=cum_seq_q,
            cu_seq_k=cum_seq_k,
            max_seqlen_q=int(max_q),
            max_seqlen_k=int(max_k),
            is_dropout=is_dropout,
            dropout_p=dropout_p,
            rng_state=rng_tuple,
            is_causal=is_causal,
            softmax_scale=scale,
            attn_bias=attn_bias,
            bias_requires_grad=bias_req_grad,
        )
        if not need_dq:
            dQ = torch.zeros_like(query)
        if not need_dk:
            dK = torch.zeros_like(key)
        if not need_dv:
            dV = torch.zeros_like(value)
        if not bias_req_grad:
            dBias = None
        return dQ, dK, dV, dBias

    # The forward's meta registration fixes the dense layout to BHSD
    # (query: B x H x S_q x D, logsumexp: B x H x S_q); permute to the
    # kernel's BSHD layout and permute the gradients back.
    grad_out_bshd = grad_out.permute(0, 2, 1, 3).contiguous()
    query_bshd = query.permute(0, 2, 1, 3).contiguous()
    key_bshd = key.permute(0, 2, 1, 3).contiguous()
    value_bshd = value.permute(0, 2, 1, 3).contiguous()
    out_bshd = out.permute(0, 2, 1, 3).contiguous()

    dQ_bshd, dK_bshd, dV_bshd, dBias = flash_attn_backward(
        grad_out_bshd,
        query_bshd,
        key_bshd,
        value_bshd,
        out_bshd,
        logsumexp.float(),
        cu_seq_q=None,
        cu_seq_k=None,
        max_seqlen_q=int(max_q),
        max_seqlen_k=int(max_k),
        is_dropout=is_dropout,
        dropout_p=dropout_p,
        rng_state=rng_tuple,
        is_causal=is_causal,
        softmax_scale=scale,
        attn_bias=attn_bias,
        bias_requires_grad=bias_req_grad,
    )

    dQ = dQ_bshd.permute(0, 2, 1, 3).contiguous()
    dK = dK_bshd.permute(0, 2, 1, 3).contiguous()
    dV = dV_bshd.permute(0, 2, 1, 3).contiguous()

    if not need_dq:
        dQ = torch.zeros_like(query)
    if not need_dk:
        dK = torch.zeros_like(key)
    if not need_dv:
        dV = torch.zeros_like(value)
    if not bias_req_grad:
        dBias = None

    return dQ, dK, dV, dBias
