# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

from flag_gems.ops.attention import flash_attention_forward

logger = logging.getLogger(__name__)


def _materialize_bhsd(t):
    """Return ``t`` in the (B, H, S, D)-contiguous layout.

    The FlashAttention kernel receives explicit strides, but it does not
    produce correct results for every stride pattern: a value tensor that is
    a transposed view of a (B, S, H, D) buffer (the layout transformers
    produces via ``k_proj(x).view(...).transpose(1, 2)``) is read wrongly
    (see #5896). Materialising non-contiguous inputs keeps the kernel on the
    layout it is validated against; contiguous inputs are passed through.
    """
    return t if t.is_contiguous() else t.contiguous()


def _scaled_dot_product_flash_attention(
    query,
    key,
    value,
    dropout_p=0.0,
    is_causal=False,
    return_debug_mask=False,
    *,
    scale=None,
):
    """Run scaled dot product FlashAttention through the existing implementation."""
    logger.debug("GEMS _SCALED_DOT_PRODUCT_FLASH_ATTENTION")
    query = _materialize_bhsd(query)
    key = _materialize_bhsd(key)
    value = _materialize_bhsd(value)
    max_q = query.shape[2]
    max_k = key.shape[2]
    output, logsumexp, rng_state, unused, debug_mask = flash_attention_forward(
        query.transpose(1, 2),
        key.transpose(1, 2),
        value.transpose(1, 2),
        None,
        None,
        max_q,
        max_k,
        dropout_p,
        is_causal,
        return_debug_mask,
        scale=scale,
    )
    return (
        output.transpose(1, 2),
        logsumexp,
        None,
        None,
        max_q,
        max_k,
        rng_state,
        unused,
        debug_mask,
    )
