# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from typing import List, Tuple, Union

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def stack_copy_func_kernel_4(
    out_ptr,
    in_ptr_a,
    in_ptr_b,
    in_ptr_c,
    in_ptr_d,
    dim_size_out,
    dim_prod_post,
    dim_offset_a,
    dim_offset_b,
    dim_offset_c,
    dim_offset_d,
    total_elements_a,
    total_elements_b,
    total_elements_c,
    total_elements_d,
    BLOCK_X: tl.constexpr,
):
    pid_x = tl.program_id(0)
    pid_y = tl.program_id(1)

    if pid_y == 0:
        in_ptr = in_ptr_a
        dim_offset = dim_offset_a
        total_elements = total_elements_a
    elif pid_y == 1:
        in_ptr = in_ptr_b
        dim_offset = dim_offset_b
        total_elements = total_elements_b
    elif pid_y == 2:
        in_ptr = in_ptr_c
        dim_offset = dim_offset_c
        total_elements = total_elements_c
    else:
        in_ptr = in_ptr_d
        dim_offset = dim_offset_d
        total_elements = total_elements_d

    block_start = pid_x.to(tl.int64) * BLOCK_X
    offsets = tl.arange(0, BLOCK_X).to(tl.int64)
    idx = block_start + offsets
    scalar_zero = offsets * 0

    dim_size_out = dim_size_out + scalar_zero
    dim_prod_post = dim_prod_post + scalar_zero
    dim_offset = dim_offset + scalar_zero
    total_elements = total_elements + scalar_zero

    mask = idx < total_elements

    pre_idx = idx // dim_prod_post
    post_idx = idx % dim_prod_post

    out_idx = (
        pre_idx * dim_size_out * dim_prod_post + dim_offset * dim_prod_post + post_idx
    )

    data = tl.load(in_ptr + idx, mask=mask)
    tl.store(out_ptr + out_idx, data, mask=mask)


def _stack(
    tensors: Union[Tuple[torch.Tensor, ...], List[torch.Tensor]], dim: int = 0
) -> torch.Tensor:
    logger.debug("GEMS _STACK")

    if len(tensors) == 0:
        raise RuntimeError("stack expected a non-empty TensorList")

    inp_shapes = [list(_.shape) for _ in tensors]
    inp0_shape = inp_shapes[0]
    # Validate ``dim`` against tensors[0] unconditionally: with a single input
    # the per-entry loop below never runs and an out-of-range dim would be
    # silently accepted instead of matching ATen.
    ndim0 = tensors[0].dim()
    if (dim < -ndim0 - 1) or (dim > ndim0):
        raise IndexError(
            "Dimension out of range (expected to be in range of [{}, {}], but got {})".format(
                -ndim0 - 1, ndim0, dim
            )
        )
    for i, s in enumerate(inp_shapes[1:]):
        ndim = tensors[i + 1].dim()
        if (dim < -ndim - 1) or (dim > ndim):
            raise IndexError(
                "Dimension out of range (expected to be in range of [{}, {}], but got {})".format(
                    -ndim - 1, ndim, dim
                )
            )
        if s != inp0_shape:
            raise RuntimeError(
                f"stack expects each tensor to be equal size, but got {inp0_shape} at entry 0 and {s} at entry {i + 1}"
            )

    if dim < 0:
        dim = dim + len(inp0_shape) + 1

    # Type promotion: find the common dtype for all tensors
    dtypes = [t.dtype for t in tensors]
    dtype = dtypes[0]
    for dt in dtypes[1:]:
        dtype = torch.promote_types(dtype, dt)
    # Triton has no complex scalar types. aten::_stack accepts complex dtypes,
    # so operate on the real view of each input and reinterpret the stacked
    # result back to complex at the end, matching the native contract.
    is_complex = dtype.is_complex
    if is_complex:
        complex_dtype = dtype
        dtype = torch.view_as_real(torch.empty((), dtype=dtype, device="cpu")).dtype
        tensors = [torch.view_as_real(t.to(complex_dtype)) for t in tensors]
    # Convert all tensors to the result dtype if needed
    tensors = [t.to(dtype) if t.dtype != dtype else t for t in tensors]
    device = tensors[0].device
    # Every path below works on the (possibly real-view) input shapes, so the
    # stacked axis and trailing real dimension are handled uniformly.
    work_shape = list(tensors[0].shape)
    out_shape = work_shape[:dim] + [len(tensors)] + work_shape[dim:]
    # Allocate via ``empty_strided`` with contiguous strides to bypass the
    # GEMS ``aten::empty.memory_format`` override, which would launch a Triton
    # zero-init kernel. The stack kernel writes every output element (each
    # input's slot along ``dim`` is fully populated), so an uninitialized
    # allocation is safe and removes the fixed zero-init overhead.
    contig_strides = []
    stride = 1
    for dim_sz in reversed(out_shape):
        contig_strides.append(stride)
        stride *= dim_sz
    contig_strides.reverse()
    out = torch.empty_strided(out_shape, contig_strides, dtype=dtype, device=device)

    dim_prod_post = 1
    for s in work_shape[dim:]:
        dim_prod_post *= s

    # Zero-sized inputs (e.g. shape (3, 0)) give a zero-volume output; return
    # the correctly shaped empty tensor without launching a kernel, since a
    # zero-volume grid would be an invalid Triton launch.
    if out.numel() == 0:
        return torch.view_as_complex(out) if is_complex else out

    # One thread per output element; 1024 is a standard block size that keeps
    # the launch grid small for the typical stack buffer sizes.
    BLOCK = 1024
    i = 0
    while i < len(tensors):
        tensors_in_batch = tensors[i : i + 4]
        num_tensors_in_batch = len(tensors_in_batch)

        args = []
        total_elements_list = []

        for j in range(4):
            if j < num_tensors_in_batch:
                tensor = tensors_in_batch[j].contiguous()
                total_elements = tensor.numel()
                args.extend([tensor, i + j, total_elements])
                total_elements_list.append(total_elements)
            else:
                args.extend([tensors_in_batch[0], 0, 0])
                total_elements_list.append(0)

        dim_size_out = len(tensors)

        grid_y = num_tensors_in_batch
        max_elements_in_batch = max(total_elements_list) if total_elements_list else 0
        grid = (triton.cdiv(max_elements_in_batch, BLOCK), grid_y)

        (
            tensor_a,
            dim_offset_a,
            total_elements_a,
            tensor_b,
            dim_offset_b,
            total_elements_b,
            tensor_c,
            dim_offset_c,
            total_elements_c,
            tensor_d,
            dim_offset_d,
            total_elements_d,
        ) = args

        stack_copy_func_kernel_4[grid](
            out,
            tensor_a,
            tensor_b,
            tensor_c,
            tensor_d,
            dim_size_out,
            dim_prod_post,
            dim_offset_a,
            dim_offset_b,
            dim_offset_c,
            dim_offset_d,
            total_elements_a,
            total_elements_b,
            total_elements_c,
            total_elements_d,
            BLOCK_X=BLOCK,
        )
        i += num_tensors_in_batch

    if is_complex:
        out = torch.view_as_complex(out)
    return out
