# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems import runtime

logger = logging.getLogger(__name__)


@triton.jit
def bartlett_window_kernel(
    output_ptr,
    N_compute,  # N used for formula (window_length+1 if periodic, else window_length)
    window_length,  # actual output length
    BLOCK_SIZE: tl.constexpr,
    COMPUTE_DTYPE: tl.constexpr,
):
    pid = tl.program_id(0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < window_length

    # Accumulate in the output's precision class so float64 keeps full precision
    n = offsets.to(COMPUTE_DTYPE)
    N_minus_1 = (N_compute - 1).to(COMPUTE_DTYPE)

    # w[n] = 1 - |2*n/(N-1) - 1|
    val = 1.0 - tl.abs(2.0 * n / N_minus_1 - 1.0)

    tl.store(output_ptr + offsets, val, mask=mask)


def bartlett_window(
    window_length,
    periodic=True,
    *,
    dtype=None,
    layout=torch.strided,
    device=None,
    requires_grad=False,
):
    logger.debug("GEMS BARTLETT_WINDOW")
    if dtype is None:
        dtype = torch.get_default_dtype()
    assert dtype in (
        torch.float16,
        torch.float32,
        torch.bfloat16,
        torch.float64,
    ), f"bartlett_window: unsupported dtype {dtype}"

    if layout != torch.strided:
        raise ValueError("Only strided layout is supported for bartlett_window.")

    if device is None:
        device = torch.device(runtime.device.name)
    else:
        device = torch.device(device)

    # CPU fallback: Triton kernels require a device-resident output tensor.
    # Compute in float64 then cast, mirroring the kernel's accumulation precision —
    # torch's low-precision path accumulates in the output dtype and drifts by
    # several ULP in the window tail, which would make CPU and device results differ.
    if device.type == "cpu":
        out = torch.bartlett_window(
            window_length,
            periodic=periodic,
            dtype=torch.float64,
            layout=layout,
            device=device,
        ).to(dtype)
        return out.requires_grad_(requires_grad)

    if window_length <= 0:
        return torch.empty(0, dtype=dtype, device=device, requires_grad=requires_grad)
    if window_length == 1:
        return torch.ones(1, dtype=dtype, device=device, requires_grad=requires_grad)

    # For periodic window, compute symmetric window of length+1, then take first window_length elements
    if periodic:
        N_compute = window_length + 1
    else:
        N_compute = window_length

    output = torch.empty(
        window_length, dtype=dtype, device=device, requires_grad=requires_grad
    )

    # 1024 balances occupancy and register usage for 1-D window generation
    BLOCK_SIZE = 1024
    grid = ((window_length + BLOCK_SIZE - 1) // BLOCK_SIZE,)

    # float64 output needs float64 math; lower precisions are fine computed in float32
    compute_dtype = tl.float64 if dtype == torch.float64 else tl.float32

    bartlett_window_kernel[grid](
        output,
        N_compute,
        window_length,
        BLOCK_SIZE=BLOCK_SIZE,
        COMPUTE_DTYPE=compute_dtype,
    )

    return output
