# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def batch_norm_stats_kernel_multi_channel(
    input_pointer,
    mean_pointer,
    invstd_pointer,
    batch_dim,
    channel_dim,
    spatial_dim,
    input_batch_stride,
    input_feat_stride,
    input_spatial_stride,
    eps,
    BLOCK_B: tl.constexpr,
    BLOCK_S: tl.constexpr,
    CHANNELS_PER_PROG: tl.constexpr,
):
    """Kernel optimized for large-C small-spatial shapes.

    Each program handles CHANNELS_PER_PROG channels sequentially.
    Uses a 2D tile [BLOCK_B, BLOCK_S] over (batch, spatial) for each channel.
    """
    pid = tl.program_id(axis=0)
    feat_start = pid * CHANNELS_PER_PROG

    count = batch_dim * spatial_dim
    fcount = count.to(tl.float32)

    spatial_offsets = tl.arange(0, BLOCK_S)
    spatial_mask = spatial_offsets < spatial_dim

    m_num_steps = tl.cdiv(batch_dim, BLOCK_B)

    for _c in tl.static_range(CHANNELS_PER_PROG):
        feat_idx = feat_start + _c
        if feat_idx < channel_dim:
            _sum = tl.zeros([BLOCK_B, BLOCK_S], dtype=tl.float32)
            _sum_sq = tl.zeros([BLOCK_B, BLOCK_S], dtype=tl.float32)

            base_ptr = input_pointer + feat_idx * input_feat_stride

            for m_step in range(0, m_num_steps):
                batch_offset = m_step * BLOCK_B + tl.arange(0, BLOCK_B)
                batch_mask = batch_offset < batch_dim

                mask = batch_mask[:, None] & spatial_mask[None, :]

                curr_ptr = (
                    base_ptr
                    + input_batch_stride * batch_offset[:, None]
                    + input_spatial_stride * spatial_offsets[None, :]
                )

                x = tl.load(curr_ptr, mask=mask, other=0.0).to(tl.float32)
                _sum += tl.where(mask, x, 0.0)
                _sum_sq += tl.where(mask, x * x, 0.0)

            total_sum = tl.sum(_sum)
            total_sum_sq = tl.sum(_sum_sq)

            mean = total_sum / fcount
            var = total_sum_sq / fcount - mean * mean
            invstd = 1.0 / tl.sqrt(var + eps)

            tl.store(mean_pointer + feat_idx, mean)
            tl.store(invstd_pointer + feat_idx, invstd)


@libentry()
@triton.autotune(
    configs=runtime.get_tuned_config("batch_norm"),
    key=["batch_dim", "spatial_dim"],
)
@triton.heuristics(runtime.get_heuristic_config("batch_norm"))
@triton.jit
def batch_norm_stats_kernel(
    input_pointer,
    mean_pointer,
    invstd_pointer,
    batch_dim,
    spatial_dim,
    input_batch_stride,
    input_feat_stride,
    input_spatial_stride,
    eps,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    # Each program handles one channel
    feat_pid = tl.program_id(axis=0)

    # Accumulate sum and sum_sq using tiled reduction over batch and spatial dims
    _sum = tl.zeros([BLOCK_M, BLOCK_N], dtype=tl.float32)
    _sum_sq = tl.zeros([BLOCK_M, BLOCK_N], dtype=tl.float32)

    m_num_steps = tl.cdiv(batch_dim, BLOCK_M)
    n_num_steps = tl.cdiv(spatial_dim, BLOCK_N)

    for m_step in range(0, m_num_steps):
        batch_offset = m_step * BLOCK_M + tl.arange(0, BLOCK_M)
        batch_mask = batch_offset < batch_dim

        for n_step in range(0, n_num_steps):
            spatial_offset = n_step * BLOCK_N + tl.arange(0, BLOCK_N)
            spatial_mask = spatial_offset < spatial_dim

            mask = batch_mask[:, None] & spatial_mask[None, :]

            curr_input_pointer = (
                input_pointer
                + input_feat_stride * feat_pid
                + input_batch_stride * batch_offset[:, None]
                + input_spatial_stride * spatial_offset[None, :]
            )

            x = tl.load(curr_input_pointer, mask=mask, other=0.0).to(tl.float32)
            _sum += tl.where(mask, x, 0.0)
            _sum_sq += tl.where(mask, x * x, 0.0)

    # Reduce across the block
    total_sum = tl.sum(_sum)
    total_sum_sq = tl.sum(_sum_sq)

    count = (batch_dim * spatial_dim).to(tl.float32)
    mean = total_sum / count
    var = total_sum_sq / count - mean * mean
    invstd = 1.0 / tl.sqrt(var + eps)

    # Store results
    tl.store(mean_pointer + feat_pid, mean)
    tl.store(invstd_pointer + feat_pid, invstd)


def batch_norm_stats(input, eps):
    """Compute batch normalization statistics (mean and invstd) per channel.

    Args:
        input: Tensor of shape (N, C, *spatial_dims)
        eps: Small constant for numerical stability

    Returns:
        Tuple of (mean, invstd), each of shape (C,)
    """
    logger.debug("GEMS BATCH_NORM_STATS")

    assert input.ndim >= 2, "Input must have at least 2 dimensions (N, C, ...)"

    # Reshape to 3D: (N, C, spatial)
    N = input.shape[0]
    C = input.shape[1]

    if input.ndim == 2:
        input_3d = input.unsqueeze(-1).contiguous()
    elif input.ndim >= 4:
        input_3d = input.flatten(2, -1).contiguous()
    else:
        input_3d = input.contiguous()

    spatial = input_3d.shape[2]

    # Output tensors
    mean = torch.empty(C, dtype=torch.float32, device=input.device)
    invstd = torch.empty(C, dtype=torch.float32, device=input.device)

    count = N * spatial

    with torch_device_fn.device(input.device):
        # Use multi-channel kernel when C is large, per-channel work is small,
        # and spatial > 1 to ensure good memory locality within each tile row.
        if C >= 256 and count <= 4096 and spatial >= 2:
            # Determine channels per program to balance grid size
            if C >= 2048:
                channels_per_prog = 8
            elif C >= 1024:
                channels_per_prog = 4
            else:
                channels_per_prog = 2

            # Block sizes for the 2D (batch, spatial) tile
            block_b = min(2048, triton.next_power_of_2(N))
            block_s = triton.next_power_of_2(spatial)
            # Cap total tile elements
            max_tile = 2**14
            block_s = min(block_s, max(1, max_tile // block_b))

            num_warps = 4
            tile_elems = block_b * block_s
            if tile_elems >= 4096:
                num_warps = 8
            elif tile_elems <= 512:
                num_warps = 2

            grid = (triton.cdiv(C, channels_per_prog),)

            batch_norm_stats_kernel_multi_channel[grid](
                input_3d,
                mean,
                invstd,
                N,
                C,
                spatial,
                input_3d.stride(0),
                input_3d.stride(1),
                input_3d.stride(2),
                eps,
                BLOCK_B=block_b,
                BLOCK_S=block_s,
                CHANNELS_PER_PROG=channels_per_prog,
                num_warps=num_warps,
            )
        else:
            # Standard path: one channel per program with autotune
            batch_norm_stats_kernel[(C,)](
                input_3d,
                mean,
                invstd,
                N,
                spatial,
                input_3d.stride(0),
                input_3d.stride(1),
                input_3d.stride(2),
                eps,
            )

    return mean, invstd
