# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl
from torch import Tensor

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry, libtuner

logger = logging.getLogger(__name__)


@libentry()
@libtuner(
    configs=[
        triton.Config({"BLOCK_SIZE": 512}, num_warps=4, num_stages=2),
        triton.Config({"BLOCK_SIZE": 1024}, num_warps=4, num_stages=2),
        triton.Config({"BLOCK_SIZE": 1024}, num_warps=8, num_stages=1),
        triton.Config({"BLOCK_SIZE": 2048}, num_warps=8, num_stages=1),
        triton.Config({"BLOCK_SIZE": 2048}, num_warps=8, num_stages=2),
        triton.Config({"BLOCK_SIZE": 4096}, num_warps=16, num_stages=1),
    ],
    key=["n_inner"],
)
@triton.jit
def batch_norm_backward_elemt_kernel(
    grad_out_ptr,
    input_ptr,
    mean_ptr,
    invstd_ptr,
    weight_ptr,
    sum_dy_ptr,
    sum_dy_xmu_ptr,
    count_ptr,
    grad_input_ptr,
    n_inner,
    spatial_size,
    chan_stride,
    HAS_WEIGHT: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """
    Per-channel batch norm backward element-wise gradient kernel.

    Grid is 2D: (C, cdiv(N*spatial, BLOCK_SIZE)).
    - axis 0 selects the channel
    - axis 1 tiles over the flattened batch*spatial dimension

    For NCHW contiguous layout, each channel c has N contiguous spatial
    chunks of size S, separated by stride C*S. We flatten the N*S elements
    per channel into a 1D index and compute the actual memory offset as:
      batch_idx = flat_idx // S
      spatial_idx = flat_idx % S
      offset = batch_idx * C * S + c * S + spatial_idx

    Args (kernel):
      n_inner: N * spatial_size (elements per channel)
      spatial_size: product of spatial dims
      chan_stride: C * spatial_size (batch stride in flat memory)

    Per-channel statistics are loaded once per program (scalar).
    """
    c = tl.program_id(0)
    pid_block = tl.program_id(1)

    # Load count once and compute inv_count on device (cudagraph-safe)
    inv_count = 1.0 / tl.load(count_ptr).to(tl.float32)

    # Load per-channel statistics once (scalar per program)
    mean = tl.load(mean_ptr + c).to(tl.float32)
    invstd = tl.load(invstd_ptr + c).to(tl.float32)
    sum_dy = tl.load(sum_dy_ptr + c).to(tl.float32)
    sum_dy_xmu = tl.load(sum_dy_xmu_ptr + c).to(tl.float32)

    if HAS_WEIGHT:
        weight = tl.load(weight_ptr + c).to(tl.float32)
    else:
        weight = 1.0

    # Precompute channel-level constant
    invstd_sq_sum_dy_xmu = invstd * invstd * sum_dy_xmu
    w_invstd = weight * invstd

    # Tile over flattened (batch * spatial) dimension
    flat_offsets = pid_block * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = flat_offsets < n_inner

    # Convert flat index to memory offset in NCHW layout
    batch_idx = flat_offsets // spatial_size
    spatial_idx = flat_offsets % spatial_size
    mem_offsets = batch_idx * chan_stride + c * spatial_size + spatial_idx

    # Coalesced loads (spatial elements within a batch are contiguous)
    grad_out = tl.load(grad_out_ptr + mem_offsets, mask=mask, other=0.0).to(tl.float32)
    inp = tl.load(input_ptr + mem_offsets, mask=mask, other=0.0).to(tl.float32)

    # Fused element-wise gradient computation in fp32
    xmu = inp - mean
    result = w_invstd * (grad_out - (sum_dy + xmu * invstd_sq_sum_dy_xmu) * inv_count)

    tl.store(grad_input_ptr + mem_offsets, result, mask=mask)


def batch_norm_backward_elemt(
    grad_out: Tensor,
    input: Tensor,
    mean: Tensor,
    invstd: Tensor,
    weight: Tensor,
    sum_dy: Tensor,
    sum_dy_xmu: Tensor,
    count: Tensor,
) -> Tensor:
    """
    Compute batch normalization backward element-wise gradient.

    Args:
        grad_out: Gradient of output (N, C, *)
        input: Input tensor (N, C, *)
        mean: Mean per channel (C,)
        invstd: Inverse standard deviation per channel (C,)
        weight: Weight per channel (C,) or None
        sum_dy: Sum of grad_out per channel (C,)
        sum_dy_xmu: Sum of grad_out * (input - mean) per channel (C,)
        count: Number of elements per channel (scalar tensor)

    Returns:
        grad_input: Gradient w.r.t. input (N, C, *)
    """
    logger.debug("GEMS BATCH_NORM_BACKWARD_ELEMT")

    # Ensure contiguous memory layout
    grad_out = grad_out.contiguous()
    input = input.contiguous()
    mean = mean.contiguous()
    invstd = invstd.contiguous()
    sum_dy = sum_dy.contiguous()
    sum_dy_xmu = sum_dy_xmu.contiguous()

    # Get dimensions
    C = input.shape[1]
    N = input.shape[0]
    # Compute spatial size from shape (no tensor ops, cudagraph-safe)
    spatial_size = 1
    for i in range(2, input.ndim):
        spatial_size *= input.shape[i]
    # n_inner = number of elements per channel = N * spatial_size
    n_inner = N * spatial_size
    # chan_stride = stride between batch elements in flat memory = C * spatial_size
    chan_stride = C * spatial_size

    # Handle optional weight
    has_weight = weight is not None
    if not has_weight:
        weight = torch.empty(0, dtype=input.dtype, device=input.device)
    else:
        weight = weight.contiguous()

    # Allocate output
    grad_input = torch.empty_like(input)

    # 2D grid: (C, cdiv(n_inner, BLOCK_SIZE))
    with torch_device_fn.device(input.device):
        batch_norm_backward_elemt_kernel[
            lambda meta: (C, triton.cdiv(n_inner, meta["BLOCK_SIZE"]))
        ](
            grad_out,
            input,
            mean,
            invstd,
            weight,
            sum_dy,
            sum_dy_xmu,
            count,
            grad_input,
            n_inner,
            spatial_size,
            chan_stride,
            HAS_WEIGHT=has_weight,
        )

    return grad_input
