# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def bitwise_right_shift_kernel(a, b):
    return a >> b


@pointwise_dynamic(is_tensor=[True, False], promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def bitwise_right_shift_ts_kernel(a, b):
    return a >> b


@pointwise_dynamic(is_tensor=[False, True], promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def bitwise_right_shift_st_kernel(a, b):
    return a >> b


def _right_shift_kernel_for(self, other):
    """Pick the kernel matching the (Tensor/Scalar) argument combination.

    ATen exposes tensor-tensor, tensor-scalar and scalar-tensor overloads;
    ``Scalar_Tensor`` is a composite that forwards its Scalar ``self``
    unchanged, so a single all-tensor kernel cannot serve it.
    """
    if isinstance(self, torch.Tensor):
        if isinstance(other, torch.Tensor):
            return bitwise_right_shift_kernel
        return bitwise_right_shift_ts_kernel
    return bitwise_right_shift_st_kernel


def bitwise_right_shift(self, other, *, out=None):
    logger.debug("GEMS BITWISE_RIGHT_SHIFT")
    kernel = _right_shift_kernel_for(self, other)
    if out is None:
        return kernel(self, other)
    kernel(self, other, out0=out)
    return out


def bitwise_right_shift_(self, other, *, out=None):
    logger.debug("GEMS BITWISE_RIGHT_SHIFT_")
    kernel = _right_shift_kernel_for(self, other)
    return kernel(self, other, out0=self)
