# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems import runtime

logger = logging.getLogger(__name__)


@triton.autotune(
    configs=runtime.get_tuned_config("conv_tbc"), key=["M", "N", "Cin", "kW"]
)
@triton.jit
def conv_tbc_kernel(
    inp_ptr,
    weight_ptr,
    bias_ptr,
    out_ptr,
    M,  # Tout * B
    N,  # Cout
    Cin,
    kW,
    B,
    T,
    pad,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    BLOCK_K: tl.constexpr,
):
    # out[m, n] = bias[n] + sum_k sum_ci inp_row(m, k)[ci] * weight[k, ci, n]
    # where m = to * B + b, and the input row for offset k is m + (k - pad) * B
    # (this shift preserves the batch index b automatically).
    pid_m = tl.program_id(0)
    pid_n = tl.program_id(1)

    offs_m = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    offs_n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    offs_k = tl.arange(0, BLOCK_K)

    m_mask = offs_m < M
    n_mask = offs_n < N

    acc = tl.zeros((BLOCK_M, BLOCK_N), dtype=tl.float32)

    num_k = tl.cdiv(Cin, BLOCK_K)
    for k in range(kW):
        # flattened input row index for this kernel tap
        in_row = offs_m + (k - pad) * B
        row_valid = m_mask & (in_row >= 0) & (in_row < T * B)

        w_base = k * Cin * N
        for ki in range(num_k):
            ck = ki * BLOCK_K + offs_k
            k_mask = ck < Cin

            a_off = in_row[:, None] * Cin + ck[None, :]
            a = tl.load(
                inp_ptr + a_off,
                mask=row_valid[:, None] & k_mask[None, :],
                other=0.0,
            )

            w_off = w_base + ck[:, None] * N + offs_n[None, :]
            w = tl.load(
                weight_ptr + w_off,
                mask=k_mask[:, None] & n_mask[None, :],
                other=0.0,
            )

            acc += tl.dot(a, w, allow_tf32=False)

    bias = tl.load(bias_ptr + offs_n, mask=n_mask, other=0.0).to(tl.float32)
    acc += bias[None, :]

    out_off = offs_m[:, None] * N + offs_n[None, :]
    tl.store(
        out_ptr + out_off,
        acc.to(out_ptr.dtype.element_ty),
        mask=m_mask[:, None] & n_mask[None, :],
    )


def _conv_tbc(input, weight, bias, pad, out=None):
    assert input.dim() == 3, "Input must be 3-dimensional (Time, Batch, Channels)"
    assert weight.dim() == 3, "Weight must be 3-dimensional (kW, Cin, Cout)"

    input = input.contiguous()
    weight = weight.contiguous()
    bias = bias.contiguous()

    T, B, Cin = input.shape
    kW, Cin_w, Cout = weight.shape
    assert Cin == Cin_w, "Input channels must match weight input channels"

    Tout = T + 2 * pad - kW + 1

    if out is None:
        out = torch.empty((Tout, B, Cout), dtype=input.dtype, device=input.device)

    if Tout <= 0:
        return out

    M = Tout * B
    N = Cout

    grid = lambda meta: (  # noqa: E731
        triton.cdiv(M, meta["BLOCK_M"]),
        triton.cdiv(N, meta["BLOCK_N"]),
    )
    conv_tbc_kernel[grid](
        input,
        weight,
        bias,
        out,
        M,
        N,
        Cin,
        kW,
        B,
        T,
        pad,
    )
    return out


def conv_tbc(input, weight, bias, pad=0):
    logger.debug("GEMS CONV_TBC")
    return _conv_tbc(input, weight, bias, pad)


def conv_tbc_out(input, weight, bias, pad=0, *, out):
    logger.debug("GEMS CONV_TBC_OUT")
    return _conv_tbc(input, weight, bias, pad, out=out)
