# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing permissions
# and limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch

logger = logging.getLogger(__name__)


def dim(self: torch.Tensor) -> int:
    """Return the number of dimensions (rank) of ``self``.

    Mirrors ``aten::dim(Tensor self) -> int``. This is a pure layout-metadata
    query: the result is the size of the tensor's sizes/strides array and
    never depends on stored element data, so it is read from TensorImpl
    properties without any device work and without a Triton kernel.

    The read is deliberately written as ``self.ndim`` rather than
    ``len(self.shape)`` or ``len(self.stride())``: ``shape``/``size`` raise
    for nested tensors and ``stride`` raises for sparse compressed layouts,
    while ``ndim`` reproduces native ``dim()`` on every layout this build
    supports (strided, sparse COO including hybrid, sparse compressed
    CSR/CSC/BSR/BSC, and nested). Verified dispatcher-free by instrumenting
    the read under ``TorchDispatchMode``.

    Re-dispatching ``dim`` from inside this function is avoided: it would
    recurse if the operator ever becomes dispatchable on a backend key (the
    precedent is ``dense_dim``, whose in-impl ``self.dense_dim()`` call
    recursed once registered). ``self.ndim`` is a TensorImpl property read,
    so it cannot re-enter this implementation.

    Semantics (verified against native ATen on H20): the rank is
    layout-independent. ``dim()``, ``ndim`` and ``ndimension`` are aliases
    returning the same plain ``int``.
    """
    logger.debug("GEMS DIM")
    return self.ndim
