# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def _embedding_bag_kernel(
    out_ptr,
    weight_ptr,
    indices_ptr,
    offsets_ptr,
    offset2bag_ptr,
    bag_size_ptr,
    max_indices_ptr,
    per_sample_weights_ptr,
    embedding_dim,
    num_samples,
    num_bags,
    MODE: tl.constexpr,
    HAS_PSW: tl.constexpr,
    INCLUDE_LAST_OFFSET: tl.constexpr,
    BLOCK: tl.constexpr,
):
    bag_idx = tl.program_id(0)
    col_block = tl.program_id(1)

    cols = col_block * BLOCK + tl.arange(0, BLOCK)
    col_mask = cols < embedding_dim

    start = tl.load(offsets_ptr + bag_idx).to(tl.int32)
    if INCLUDE_LAST_OFFSET:
        end = tl.load(offsets_ptr + bag_idx + 1).to(tl.int32)
    elif bag_idx + 1 < num_bags:
        end = tl.load(offsets_ptr + bag_idx + 1).to(tl.int32)
    else:
        end = num_samples

    count = end - start

    if MODE == 0 or MODE == 1:
        # sum (0) / mean (1): accumulate gathered rows, divide by count for mean
        acc = tl.zeros([BLOCK], dtype=tl.float32)
        for i in range(0, count):
            sample_idx = start + i
            row_idx = tl.load(indices_ptr + sample_idx).to(tl.int64)
            w = tl.load(
                weight_ptr + row_idx * embedding_dim + cols, mask=col_mask, other=0.0
            ).to(tl.float32)
            if HAS_PSW:
                psw = tl.load(per_sample_weights_ptr + sample_idx).to(tl.float32)
                w = w * psw
            acc += w
        if MODE == 1:
            inv = 1.0 / count.to(tl.float32)
            acc = acc * inv
        tl.store(
            out_ptr + bag_idx * embedding_dim + cols,
            acc.to(out_ptr.dtype.element_ty),
            mask=col_mask,
        )
        tl.store(
            max_indices_ptr + bag_idx * embedding_dim + cols,
            tl.zeros([BLOCK], dtype=tl.int64),
            mask=col_mask,
        )
    else:
        # max (2): track running max value and the source row per column
        acc = tl.full([BLOCK], float("-inf"), dtype=tl.float32)
        best_idx = tl.full([BLOCK], dtype=tl.int64, value=0)
        for i in range(0, count):
            sample_idx = start + i
            row_idx = tl.load(indices_ptr + sample_idx).to(tl.int64)
            w = tl.load(
                weight_ptr + row_idx * embedding_dim + cols,
                mask=col_mask,
                other=float("-inf"),
            ).to(tl.float32)
            is_gt = w > acc
            acc = tl.where(is_gt, w, acc)
            best_idx = tl.where(is_gt, row_idx, best_idx)
        tl.store(
            out_ptr + bag_idx * embedding_dim + cols,
            acc.to(out_ptr.dtype.element_ty),
            mask=col_mask,
        )
        tl.store(
            max_indices_ptr + bag_idx * embedding_dim + cols, best_idx, mask=col_mask
        )

    tl.store(bag_size_ptr + bag_idx, count.to(tl.int64))

    # Only col_block 0 fills offset2bag to avoid redundant writes across tiles
    if col_block == 0:
        for i in range(0, count):
            sample_idx = start + i
            tl.store(offset2bag_ptr + sample_idx, bag_idx.to(tl.int64))


def embedding_bag(
    weight,
    indices,
    offsets,
    scale_grad_by_freq=False,
    mode=0,
    sparse=False,
    per_sample_weights=None,
    include_last_offset=False,
):
    logger.debug("GEMS EMBEDDING_BAG")
    if weight.dtype not in (torch.float16, torch.bfloat16, torch.float32):
        raise TypeError(
            "embedding_bag supports only float16, bfloat16, and float32 weights, "
            f"got {weight.dtype}"
        )

    num_weights, embedding_dim = weight.shape
    num_samples = indices.shape[0]
    num_offsets = offsets.shape[0]
    if include_last_offset:
        num_bags = num_offsets - 1
    else:
        num_bags = num_offsets

    output = torch.empty(
        (num_bags, embedding_dim), dtype=weight.dtype, device=weight.device
    )
    offset2bag = torch.zeros((num_samples,), dtype=torch.int64, device=weight.device)
    bag_size = torch.empty((num_bags,), dtype=torch.int64, device=weight.device)
    max_indices = torch.zeros(
        (num_bags, embedding_dim), dtype=torch.int64, device=weight.device
    )

    has_psw = per_sample_weights is not None
    psw = (
        per_sample_weights
        if has_psw
        else torch.empty(0, dtype=weight.dtype, device=weight.device)
    )

    # BLOCK tiles the embedding dimension; cap at 1024 to bound register use.
    BLOCK = triton.next_power_of_2(embedding_dim)
    BLOCK = min(BLOCK, 1024)
    num_col_blocks = triton.cdiv(embedding_dim, BLOCK)
    grid = (num_bags, num_col_blocks)

    _embedding_bag_kernel[grid](
        output,
        weight,
        indices,
        offsets,
        offset2bag,
        bag_size,
        max_indices,
        psw,
        embedding_dim,
        num_samples,
        num_bags,
        MODE=mode,
        HAS_PSW=has_psw,
        INCLUDE_LAST_OFFSET=include_last_offset,
        BLOCK=BLOCK,
        # num_warps=1: memory-bound gather benefits from SM occupancy over
        # warp-level parallelism (KernelGen tuned, +18.5% on H20-3e).
        num_warps=1,
    )

    return output, offset2bag, bag_size, max_indices
