# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def hspmm_kernel(
    row_ptr,
    col_ptr,
    val_ptr,
    mat2_ptr,
    out_val_ptr,
    nnz,
    N,
    mat2_stride_0,
    mat2_stride_1,
    BLOCK_N: tl.constexpr,
):
    """
    Hybrid sparse-dense matrix multiply kernel.
    Each program processes one nnz entry: loads val[pid] and mat2[col[pid], :],
    computes val[pid] * mat2[col[pid], :], and writes to out_val[pid, :].
    """
    pid = tl.program_id(0)
    if pid >= nnz:
        return

    # Load the scalar value and column index for this nnz entry
    val_scalar = tl.load(val_ptr + pid)
    col_idx = tl.load(col_ptr + pid)

    # Compute the base pointer for mat2[col_idx, :]
    mat2_row_ptr = mat2_ptr + col_idx * mat2_stride_0

    # Process N in blocks of BLOCK_N
    for n_start in range(0, N, BLOCK_N):
        n_offsets = n_start + tl.arange(0, BLOCK_N)
        mask = n_offsets < N

        # Load mat2[col_idx, n_start:n_start+BLOCK_N]
        mat2_vals = tl.load(
            mat2_row_ptr + n_offsets * mat2_stride_1,
            mask=mask,
            other=0.0,
        )

        # Compute val_scalar * mat2_vals
        result = val_scalar * mat2_vals

        # Store to out_val[pid, n_start:n_start+BLOCK_N]
        out_ptr = out_val_ptr + pid * N + n_offsets
        tl.store(out_ptr, result, mask=mask)


def hspmm(mat1: torch.Tensor, mat2: torch.Tensor) -> torch.Tensor:
    """
    Hybrid sparse-dense matrix multiply: mat1 (sparse COO) @ mat2 (dense).

    Args:
        mat1: Sparse COO tensor of shape (M, K)
        mat2: Dense tensor of shape (K, N)

    Returns:
        Sparse COO tensor of shape (M, N), uncoalesced (one entry per input nnz)
    """
    logger.debug("GEMS HSPMM")

    if mat1.layout != torch.sparse_coo:
        raise ValueError(f"hspmm: mat1 must be sparse COO, got {mat1.layout}")
    if not mat2.is_contiguous():
        mat2 = mat2.contiguous()

    M, K = mat1.shape
    K2, N = mat2.shape
    if K != K2:
        raise ValueError(f"hspmm: mat1.shape[1]={K} must match mat2.shape[0]={K2}")

    # Extract COO components
    indices = mat1._indices()
    values = mat1._values()
    nnz = mat1._nnz()

    if nnz == 0:
        # Empty sparse tensor: return empty result
        out_indices = torch.zeros((1, 0), dtype=torch.long, device=mat1.device)
        out_values = torch.zeros((0, N), dtype=mat2.dtype, device=mat2.device)
        return torch.sparse_coo_tensor(
            out_indices, out_values, (M, N), dtype=mat2.dtype, device=mat2.device
        )

    # For COO, indices has shape (2, nnz) or (ndim, nnz)
    # We need row and col indices
    if indices.dim() == 1:
        # 1D sparse tensor edge case
        row_indices = torch.zeros(nnz, dtype=torch.long, device=mat1.device)
        col_indices = indices
    else:
        row_indices = indices[0].contiguous()
        col_indices = indices[1].contiguous()

    # Allocate output values: shape (nnz, N)
    out_values = torch.empty((nnz, N), dtype=mat2.dtype, device=mat2.device)

    # Launch kernel: one program per nnz entry
    BLOCK_N = min(triton.next_power_of_2(N), 1024)
    grid = (nnz,)

    hspmm_kernel[grid](
        row_indices,
        col_indices,
        values,
        mat2,
        out_values,
        nnz,
        N,
        mat2.stride(0),
        mat2.stride(1),
        BLOCK_N=BLOCK_N,
    )

    # Construct output sparse COO tensor: indices are just the row indices
    # (uncoalesced, following CUDA aten::hspmm behavior)
    out_indices = row_indices.unsqueeze(0)

    return torch.sparse_coo_tensor(
        out_indices, out_values, (M, N), dtype=mat2.dtype, device=mat2.device
    )
