# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic, tl_extra_shim

erf = tl_extra_shim.erf
exp = tl_extra_shim.exp
pow = tl_extra_shim.pow

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def infinitely_differentiable_gelu_backward_kernel(grad, self_input):
    """
    Compute the gradient for the infinitely differentiable (erf-based) GELU.

    This is mathematically identical to gelu_backward with approximate='none',
    but exposed as a separate operator for higher-order autograd.

    Formula: grad * (cdf(x) + x * pdf(x))
    where cdf(x) = 0.5 * (1 + erf(x / sqrt(2)))
          pdf(x) = exp(-x^2 / 2) / sqrt(2 * pi)
    """
    scale1: tl.constexpr = 0.7071067811  # 1 / sqrt(2)
    scale2: tl.constexpr = 0.3989422803  # 1 / sqrt(2 * pi)
    x_fp32 = self_input.to(tl.float32)
    dydx = (
        scale2 * x_fp32 * exp(-pow(scale1 * x_fp32, 2))
        + 0.5 * erf(scale1 * x_fp32)
        + 0.5
    )
    dx = dydx * grad
    return dx


def infinitely_differentiable_gelu_backward(grad, self_input):
    """
    Backward pass for the infinitely differentiable (erf-based) GELU activation.

    Args:
        grad: Gradient from upstream, same shape and dtype as self_input
        self_input: Forward pass input tensor

    Returns:
        Gradient with respect to self_input
    """
    logger.debug("GEMS INFINITELY_DIFFERENTIABLE_GELU_BACKWARD")
    return infinitely_differentiable_gelu_backward_kernel(grad, self_input)
