# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl
from triton.language.extra import libdevice

from flag_gems import runtime
from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as ext

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def kaiser_window_kernel(
    out_ptr,
    window_length,
    half_length,
    beta,
    IS_FP64: tl.constexpr,
    IS_LOW_PRECISION: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    pid = ext.program_id(0)
    idx = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = idx < window_length

    out_dtype = out_ptr.dtype.element_ty

    if IS_FP64:
        # fp64 keeps full precision end to end; tl.sqrt and libdevice.cyl_bessel_i0
        # both have native double-precision paths.
        n = idx.to(tl.float64)
        half = tl.full((), 0.0, tl.float64) + half_length
        b = tl.full((), 0.0, tl.float64) + beta
        x = (n - half) / half
        val = libdevice.cyl_bessel_i0(b * tl.sqrt(tl.maximum(1.0 - x * x, 0.0)))
        val = val / libdevice.cyl_bessel_i0(b)
    else:
        if IS_LOW_PRECISION:
            # torch rounds the element index into the *output* dtype before the
            # arithmetic, which is observable for float16 / bfloat16 once the
            # index exceeds 2048 (bfloat16) / 16384 (float16): the rounded index
            # shifts the sample position and the resulting value. Reproduce it so
            # the low-precision windows stay within the CI tolerance without a
            # dtype-dependent fudge factor.
            n = idx.to(out_dtype).to(tl.float32)
        else:
            n = idx.to(tl.float32)
        x = (n - half_length) / half_length
        val = libdevice.cyl_bessel_i0(beta * tl.sqrt(tl.maximum(1.0 - x * x, 0.0)))
        val = val / libdevice.cyl_bessel_i0(beta)

    tl.store(out_ptr + idx, val.to(out_dtype), mask=mask)


def kaiser_window(
    window_length,
    periodic=True,
    beta=12.0,
    *,
    dtype=None,
    layout=torch.strided,
    device=None,
    pin_memory=None,
):
    logger.debug("GEMS KAISER_WINDOW")
    assert window_length >= 0, "window_length must be non-negative"

    if dtype is None:
        dtype = torch.get_default_dtype()
    assert dtype.is_floating_point, "kaiser_window only supports floating point dtype"

    if layout != torch.strided:
        raise ValueError("Only strided layout is supported for kaiser_window.")

    if device is None:
        device = torch.device(runtime.device.name)

    out = torch.empty(
        (window_length,),
        dtype=dtype,
        layout=layout,
        device=device,
        pin_memory=pin_memory,
    )

    if window_length == 0:
        return out
    if window_length == 1:
        return torch.fill(out, 1.0)

    # N is the effective full size: window_length + 1 would be used by a periodic
    # *sampling* convention, but aten uses N = window_length - 1 for the symmetric
    # window and N = window_length for the periodic one.
    full_length = window_length if periodic else window_length - 1

    # 1024 elements per program: a standard 1D launch block that balances
    # occupancy against register pressure for this elementwise Bessel fill.
    BLOCK_SIZE = 1024
    grid = (triton.cdiv(window_length, BLOCK_SIZE),)
    kaiser_window_kernel[grid](
        out,
        window_length,
        full_length / 2.0,
        float(beta),
        dtype == torch.float64,
        dtype in (torch.float16, torch.bfloat16),
        BLOCK_SIZE=BLOCK_SIZE,
    )
    return out


def kaiser_window_periodic(
    window_length,
    periodic,
    *,
    dtype=None,
    layout=torch.strided,
    device=None,
    pin_memory=None,
):
    return kaiser_window(
        window_length,
        periodic,
        dtype=dtype,
        layout=layout,
        device=device,
        pin_memory=pin_memory,
    )


def kaiser_window_beta(
    window_length,
    periodic,
    beta,
    *,
    dtype=None,
    layout=torch.strided,
    device=None,
    pin_memory=None,
):
    return kaiser_window(
        window_length,
        periodic,
        beta,
        dtype=dtype,
        layout=layout,
        device=device,
        pin_memory=pin_memory,
    )
