# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from enum import Enum

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


class Reduction(Enum):
    NONE = 0
    MEAN = 1
    SUM = 2


@triton.jit
def _kl_div_kernel(
    inp,
    target,
    out,
    n_elements,
    log_target: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    inp_val = tl.load(inp + offsets, mask=mask, other=0.0).to(tl.float32)
    target_val = tl.load(target + offsets, mask=mask, other=0.0).to(tl.float32)

    if log_target:
        loss = tl.exp(target_val) * (target_val - inp_val)
    else:
        # Matches ATen: result = xlogy(target, target) - target * input,
        # with xlogy(0, y) = 0 for any y.
        log_target_val = tl.log(target_val)
        xlogy = tl.where(target_val == 0.0, 0.0, target_val * log_target_val)
        loss = xlogy - target_val * inp_val

    tl.store(out + offsets, loss, mask=mask)


@triton.jit
def _kl_div_partial_sum_kernel(
    inp,
    target,
    mid,
    n_elements,
    reduction: tl.constexpr,
    log_target: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    inp_val = tl.load(inp + offsets, mask=mask, other=0.0).to(tl.float32)
    target_val = tl.load(target + offsets, mask=mask, other=0.0).to(tl.float32)

    if log_target:
        loss = tl.exp(target_val) * (target_val - inp_val)
    else:
        log_target_val = tl.log(target_val)
        xlogy = tl.where(target_val == 0.0, 0.0, target_val * log_target_val)
        loss = xlogy - target_val * inp_val

    loss = tl.where(mask, loss, 0.0)
    acc = tl.sum(loss, axis=0)
    if reduction == 1:
        acc = acc / n_elements
    tl.store(mid + pid, acc)


@triton.jit
def _kl_div_sum_kernel(mid, out, mid_size, BLOCK_MID: tl.constexpr):
    offsets = tl.arange(0, BLOCK_MID)
    mask = offsets < mid_size
    vals = tl.load(mid + offsets, mask=mask, other=0.0).to(tl.float32)
    acc = tl.sum(vals, axis=0)
    tl.store(out, acc)


def _check_tensors(input: torch.Tensor, target: torch.Tensor):
    if input.device != target.device:
        raise AssertionError("kl_div: input and target must be on the same device.")
    if input.device.type != "cuda":
        raise AssertionError("kl_div: input and target must be CUDA tensors.")
    input, target = torch.broadcast_tensors(input, target)
    return input.contiguous(), target.contiguous()


def kl_div(
    input: torch.Tensor,
    target: torch.Tensor,
    reduction=1,
    *,
    log_target=False,
) -> torch.Tensor:
    logger.debug("GEMS KL_DIV")
    input, target = _check_tensors(input, target)
    n_elements = input.numel()
    log_target = bool(log_target)

    if reduction == Reduction.NONE.value:
        out = torch.empty_like(input)
        if n_elements > 0:
            grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
            with torch_device_fn.device(input.device):
                _kl_div_kernel[grid](
                    input,
                    target,
                    out,
                    n_elements,
                    log_target=log_target,
                    # 1D elementwise-then-reduce kernel; 1024 gives a full warp-
                    # aligned block that saturates memory bandwidth on the GPU.
                    BLOCK_SIZE=1024,
                )
        return out

    if n_elements == 0:
        # Follow ATen: sum -> 0, mean -> NaN
        if reduction == Reduction.SUM.value:
            return torch.zeros((), device=input.device, dtype=input.dtype)
        return torch.full((), float("nan"), device=input.device, dtype=input.dtype)

    block_size = 1024
    mid_size = triton.cdiv(n_elements, block_size)
    block_mid = triton.next_power_of_2(mid_size)
    mid = torch.empty((mid_size,), device=input.device, dtype=torch.float32)
    out = torch.empty((), device=input.device, dtype=input.dtype)

    with torch_device_fn.device(input.device):
        _kl_div_partial_sum_kernel[(mid_size,)](
            input,
            target,
            mid,
            n_elements,
            reduction=reduction,
            log_target=log_target,
            BLOCK_SIZE=block_size,
        )
        _kl_div_sum_kernel[(1,)](mid, out, mid_size, BLOCK_MID=block_mid)
    return out
