# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging
from collections import namedtuple

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)

LinalgInvExResult = namedtuple("LinalgInvExResult", ["inverse", "info"])


@libentry()
@triton.jit
def _linalg_inv_kernel(
    A,
    INV,
    INFO,
    PIVOTS,
    N: tl.constexpr,
    BLOCK_N: tl.constexpr,
    COL_TILE: tl.constexpr,
):
    """Fused LU factorization + triangular solve for matrix inversion.

    Each program instance handles one matrix in the batch.
    Phase 1: PA=LU with partial pivoting.
    Phase 2: Solve LU*X = P*I in tiles of COL_TILE columns.
    """
    pid = tl.program_id(0)
    rows = tl.arange(0, BLOCK_N)
    cols = tl.arange(0, BLOCK_N)

    # Load input matrix
    offsets = pid * N * N + rows[:, None] * N + cols[None, :]
    mask = (rows[:, None] < N) & (cols[None, :] < N)
    work = tl.load(A + offsets, mask=mask, other=0.0).to(tl.float32)

    pivot_base = pid * N
    singular = 0
    col_mask = cols[None, :] < N

    # Phase 1: LU factorization with partial pivoting
    for j_ind in tl.range(0, N):
        # Find pivot — extract column j_ind via axis=1 sum (avoids tl.trans)
        col_j = tl.sum(tl.where(cols[None, :] == j_ind, work, 0.0), axis=1)
        abs_col = tl.abs(col_j)
        abs_col = tl.where(rows < j_ind, -1.0, abs_col)
        abs_col = tl.where(rows < N, abs_col, -1.0)
        pivot_val = tl.max(abs_col, axis=0)
        pivot_row = tl.min(tl.where(abs_col == pivot_val, rows, BLOCK_N), axis=0)

        # Store pivot to scratch
        tl.store(PIVOTS + pivot_base + j_ind, pivot_row)

        # Swap rows
        row_j = tl.sum(tl.where(rows[:, None] == j_ind, work, 0.0), axis=0)
        row_p = tl.sum(tl.where(rows[:, None] == pivot_row, work, 0.0), axis=0)
        work = tl.where((rows[:, None] == j_ind) & col_mask, row_p, work)
        work = tl.where((rows[:, None] == pivot_row) & col_mask, row_j, work)

        # Pivot value
        pivot = tl.sum(
            tl.sum(
                tl.where(
                    (rows[:, None] == j_ind) & (cols[None, :] == j_ind),
                    work,
                    0.0,
                ),
                axis=0,
            ),
            axis=0,
        )

        singular = tl.where((pivot == 0.0) & (singular == 0), j_ind + 1, singular)

        # Multipliers — extract column j_ind via axis=1 sum
        col_vals = tl.sum(tl.where(cols[None, :] == j_ind, work, 0.0), axis=1)
        safe_pivot = tl.where(pivot == 0.0, 1.0, pivot)
        multipliers = tl.where(rows > j_ind, col_vals / safe_pivot, 0.0)

        work = tl.where(
            (rows[:, None] > j_ind) & (cols[None, :] == j_ind),
            multipliers[:, None],
            work,
        )

        # Trailing update
        u_row = tl.sum(tl.where(rows[:, None] == j_ind, work, 0.0), axis=0)
        update_mask = (rows[:, None] > j_ind) & (cols[None, :] > j_ind)
        work = tl.where(update_mask, work - multipliers[:, None] * u_row[None, :], work)

    # Phase 2: Solve in column tiles
    tile_cols = tl.arange(0, COL_TILE)

    for tile_start in tl.range(0, N, COL_TILE):
        # Identity tile
        rhs = tl.where(rows[:, None] == (tile_start + tile_cols[None, :]), 1.0, 0.0)

        # Apply permutation
        for j_perm in tl.range(0, N):
            piv_row = tl.load(PIVOTS + pivot_base + j_perm)
            rhs_row_j = tl.sum(tl.where(rows[:, None] == j_perm, rhs, 0.0), axis=0)
            rhs_row_p = tl.sum(tl.where(rows[:, None] == piv_row, rhs, 0.0), axis=0)
            tile_mask = tile_cols[None, :] < COL_TILE
            rhs = tl.where(
                (rows[:, None] == j_perm) & tile_mask,
                rhs_row_p[None, :],
                rhs,
            )
            rhs = tl.where(
                (rows[:, None] == piv_row) & tile_mask,
                rhs_row_j[None, :],
                rhs,
            )

        # Forward substitution
        for j_fwd in tl.range(0, N):
            l_col = tl.sum(tl.where(cols[None, :] == j_fwd, work, 0.0), axis=1)
            l_col = tl.where(rows > j_fwd, l_col, 0.0)
            rhs_row_j = tl.sum(tl.where(rows[:, None] == j_fwd, rhs, 0.0), axis=0)
            rhs = rhs - l_col[:, None] * rhs_row_j[None, :]

        # Back substitution
        for j_rev in tl.range(0, N):
            j_back = N - 1 - j_rev
            diag_val = tl.sum(
                tl.sum(
                    tl.where(
                        (rows[:, None] == j_back) & (cols[None, :] == j_back),
                        work,
                        0.0,
                    ),
                    axis=0,
                ),
                axis=0,
            )
            safe_diag = tl.where(diag_val == 0.0, 1.0, diag_val)
            rhs_row_j = tl.sum(tl.where(rows[:, None] == j_back, rhs, 0.0), axis=0)
            scaled_row = rhs_row_j / safe_diag
            tile_mask = tile_cols[None, :] < COL_TILE
            rhs = tl.where(
                (rows[:, None] == j_back) & tile_mask,
                scaled_row[None, :],
                rhs,
            )
            u_col = tl.sum(tl.where(cols[None, :] == j_back, work, 0.0), axis=1)
            u_col = tl.where(rows < j_back, u_col, 0.0)
            rhs = rhs - u_col[:, None] * scaled_row[None, :]

        # Store tile
        out_offsets = (
            pid * N * N + rows[:, None] * N + (tile_start + tile_cols[None, :])
        )
        out_mask = (rows[:, None] < N) & ((tile_start + tile_cols[None, :]) < N)
        tl.store(INV + out_offsets, rhs, mask=out_mask)

    # Store info
    tl.store(INFO + pid, singular)


def linalg_inv_ex(A, *, check_errors=False):
    """Compute the inverse of a square matrix.

    Args:
        A: Input tensor of shape (*, n, n).
        check_errors: If True, raises an error if the matrix is singular.

    Returns:
        A namedtuple (inverse, info) where:
        - inverse: The inverse matrix of shape (*, n, n).
        - info: An int32 tensor. 0 indicates success; a positive integer i
          indicates that the i-th diagonal element of U in the LU
          decomposition is exactly zero.
    """
    logger.debug("GEMS LINALG_INV_EX")
    assert A.ndim >= 2, "Input must be at least 2D"
    n = A.shape[-1]
    assert A.shape[-2] == n, "Input must be a square matrix"
    assert A.dtype in (
        torch.float32,
        torch.float64,
    ), f"linalg_inv_ex: unsupported dtype {A.dtype}, requires float32 or float64"

    device = A.device
    dtype = A.dtype
    batch_shape = A.shape[:-2]
    batch_size = 1
    for s in batch_shape:
        batch_size *= s

    # Flatten batch dimensions
    A_flat = A.contiguous().reshape(batch_size, n, n)

    block_n = triton.next_power_of_2(n)
    # Minimum block size of 4 to avoid Triton codegen edge cases with tiny blocks
    block_n = max(block_n, 4)

    # Choose COL_TILE to control register pressure during solve phase.
    # Registers for solve tile: BLOCK_N * COL_TILE floats.
    # Keep total (work + rhs) under reasonable limit.
    if block_n <= 32:
        col_tile = block_n
        nw = 4
    elif block_n <= 64:
        col_tile = 32
        nw = 4
    elif block_n <= 128:
        col_tile = 16
        nw = 8
    else:
        col_tile = 8
        nw = 16

    # Ensure col_tile divides evenly into block_n for tiling
    col_tile = min(col_tile, block_n)

    inverse = torch.empty(batch_size, n, n, dtype=torch.float32, device=device)
    info = torch.empty(batch_size, dtype=torch.int32, device=device)
    pivots = torch.empty(batch_size, n, dtype=torch.int32, device=device)

    grid = (batch_size,)

    with torch_device_fn.device(device):
        _linalg_inv_kernel[grid](
            A_flat,
            inverse,
            info,
            pivots,
            N=n,
            BLOCK_N=block_n,
            COL_TILE=col_tile,
            num_warps=nw,
        )

    # Reshape back to original batch shape
    inverse = inverse.reshape(*batch_shape, n, n).to(dtype)
    info = info.reshape(list(batch_shape))

    if check_errors and torch.any(info != 0):
        raise torch.linalg.LinAlgError(
            "torch.linalg.inv_ex: The diagonal element of the LU "
            "decomposition is zero."
        )

    return LinalgInvExResult(inverse, info)
