# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
#
# Triton implementation of linalg_solve_ex.
# Solves AX = B via fused LU decomposition + triangular solves in a single kernel.
# Returns (result, info) where info indicates singularity status.
import logging
import math

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.autotune(
    configs=[
        triton.Config({}, num_warps=1, num_stages=1),
        triton.Config({}, num_warps=2, num_stages=1),
    ],
    key=["n", "nrhs"],
)
@triton.jit
def linalg_solve_ex_kernel(
    A,
    LU,
    B,
    X,
    INFO,
    n,
    nrhs,
    a_batch_stride,
    a_row_stride,
    lu_batch_stride,
    lu_row_stride,
    b_batch_stride,
    b_row_stride,
    x_batch_stride,
    x_row_stride,
    BLOCK_N: tl.constexpr,
    BLOCK_K: tl.constexpr,
):
    """
    Fused kernel: copy A->LU, LU decomposition with partial pivoting,
    forward substitution, backward substitution.
    Also writes info[batch_idx] = 0 on success, or pivot index on singularity.

    Each program handles one batch element.
    A columns vectorized via BLOCK_N, RHS columns vectorized via BLOCK_K.
    LU workspace is separate from A so autotune re-runs start from fresh A.
    """
    batch_idx = tl.program_id(0)

    # Vector indices
    a_cols = tl.arange(0, BLOCK_N)
    b_cols = tl.arange(0, BLOCK_K)
    a_col_mask = a_cols < n
    b_col_mask = b_cols < nrhs

    a_base = A + batch_idx * a_batch_stride
    lu_base = LU + batch_idx * lu_batch_stride
    b_base = B + batch_idx * b_batch_stride
    x_base = X + batch_idx * x_batch_stride

    # Copy A to LU workspace (vectorized over columns)
    i = 0
    while i < n:
        row = tl.load(a_base + i * a_row_stride + a_cols, mask=a_col_mask, other=0.0)
        tl.store(lu_base + i * lu_row_stride + a_cols, row, mask=a_col_mask)
        i += 1

    # Copy B to X (vectorized over RHS columns)
    i = 0
    while i < n:
        bi = tl.load(b_base + i * b_row_stride + b_cols, mask=b_col_mask, other=0.0)
        tl.store(x_base + i * x_row_stride + b_cols, bi, mask=b_col_mask)
        i += 1

    # Step 1: LU decomposition with partial pivoting on LU workspace
    # Track singularity info (first zero pivot index, 1-based)
    info_val = 0
    k = 0
    while k < n:
        # Find pivot: argmax |LU[k:n, k]|
        max_val = tl.abs(tl.load(lu_base + k * lu_row_stride + k))
        pivot_row = k
        i = k + 1
        while i < n:
            val = tl.abs(tl.load(lu_base + i * lu_row_stride + k))
            if val > max_val:
                max_val = val
                pivot_row = i
            i += 1

        # Swap rows k and pivot_row - vectorized
        if pivot_row != k:
            luk_row = tl.load(
                lu_base + k * lu_row_stride + a_cols, mask=a_col_mask, other=0.0
            )
            lup_row = tl.load(
                lu_base + pivot_row * lu_row_stride + a_cols,
                mask=a_col_mask,
                other=0.0,
            )
            tl.store(lu_base + k * lu_row_stride + a_cols, lup_row, mask=a_col_mask)
            tl.store(
                lu_base + pivot_row * lu_row_stride + a_cols,
                luk_row,
                mask=a_col_mask,
            )
            # Swap X rows
            xk = tl.load(x_base + k * x_row_stride + b_cols, mask=b_col_mask, other=0.0)
            xp = tl.load(
                x_base + pivot_row * x_row_stride + b_cols,
                mask=b_col_mask,
                other=0.0,
            )
            tl.store(x_base + k * x_row_stride + b_cols, xp, mask=b_col_mask)
            tl.store(x_base + pivot_row * x_row_stride + b_cols, xk, mask=b_col_mask)

        akk = tl.load(lu_base + k * lu_row_stride + k)

        # Check for singularity (record first zero pivot, 1-based index)
        if info_val == 0 and tl.abs(akk) == 0.0:
            info_val = k + 1

        # Load pivot row for vectorized trailing update
        ak_row = tl.load(
            lu_base + k * lu_row_stride + a_cols, mask=a_col_mask, other=0.0
        )

        # Trailing column mask (only update columns > k)
        trail_mask = (a_cols > k) & a_col_mask

        # Compute L factors and update trailing submatrix
        i = k + 1
        while i < n:
            aik = tl.load(lu_base + i * lu_row_stride + k)
            lik = aik / akk
            tl.store(lu_base + i * lu_row_stride + k, lik)
            # Vectorized: LU[i, j] -= lik * LU[k, j] for j > k
            ai_row = tl.load(
                lu_base + i * lu_row_stride + a_cols, mask=trail_mask, other=0.0
            )
            ai_row = ai_row - lik * ak_row
            tl.store(lu_base + i * lu_row_stride + a_cols, ai_row, mask=trail_mask)
            i += 1
        k += 1

    # Write info
    tl.store(INFO + batch_idx, info_val)

    # Step 2: Forward substitution Ly = Pb (vectorized over BLOCK_K)
    i = 1
    while i < n:
        xi = tl.load(x_base + i * x_row_stride + b_cols, mask=b_col_mask, other=0.0)
        j = 0
        while j < i:
            lij = tl.load(lu_base + i * lu_row_stride + j)
            xj = tl.load(x_base + j * x_row_stride + b_cols, mask=b_col_mask, other=0.0)
            xi = xi - lij * xj
            j += 1
        tl.store(x_base + i * x_row_stride + b_cols, xi, mask=b_col_mask)
        i += 1

    # Step 3: Backward substitution Ux = y (vectorized over BLOCK_K)
    i = n - 1
    while i >= 0:
        xi = tl.load(x_base + i * x_row_stride + b_cols, mask=b_col_mask, other=0.0)
        j = i + 1
        while j < n:
            uij = tl.load(lu_base + i * lu_row_stride + j)
            xj = tl.load(x_base + j * x_row_stride + b_cols, mask=b_col_mask, other=0.0)
            xi = xi - uij * xj
            j += 1
        uii = tl.load(lu_base + i * lu_row_stride + i)
        xi = xi / uii
        tl.store(x_base + i * x_row_stride + b_cols, xi, mask=b_col_mask)
        i -= 1


def linalg_solve_ex(A, B, *, left=True, check_errors=False):
    """
    Solve the linear system AX = B, returning (result, info).

    A version of linalg_solve that does not perform error checks unless
    check_errors=True. Also returns the info tensor indicating singularity.

    Args:
        A: (*, n, n) coefficient matrix
        B: (*, n, k) right-hand side matrix
        left: if True, solve AX = B
        check_errors: if True, raise error on singular matrix

    Returns:
        A named tuple (result, info) where:
        - result: (*, n, k) solution matrix
        - info: (*,) integer tensor, 0 = success, >0 = singular at that pivot
    """
    logger.debug("GEMS LINALG_SOLVE_EX")

    if not left:
        raise NotImplementedError("right=True (XA = B) is not yet supported")
    assert A.dtype in (
        torch.float32,
        torch.float64,
    ), f"linalg_solve_ex requires float32/float64, got {A.dtype}"
    if A.ndim < 2 or B.ndim < 2:
        raise ValueError("A and B must be at least 2D")
    if A.shape[-1] != A.shape[-2]:
        raise ValueError("A must be a square matrix")
    n = A.shape[-1]
    if B.shape[-2] != n:
        raise ValueError("B must have compatible dimensions with A")
    if A.numel() == 0 or B.numel() == 0:
        batch_shape = A.shape[:-2]
        info = torch.zeros(batch_shape, dtype=torch.int32, device=A.device)
        return B.clone(), info

    batch_shape = A.shape[:-2]
    batch = math.prod(batch_shape)
    nrhs = B.shape[-1]

    # Make contiguous copies
    A_work = A.reshape(batch, n, n).contiguous()
    B_work = B.reshape(batch, n, nrhs).contiguous()
    # LU workspace separate from A (safe for autotune re-runs)
    LU = torch.empty_like(A_work)
    X = torch.empty_like(B_work)
    info = torch.empty(batch, dtype=torch.int32, device=A.device)

    # BLOCK_N covers all n columns of A (power of 2)
    block_n = max(triton.next_power_of_2(n), 4)
    # BLOCK_K covers all nrhs columns (power of 2)
    block_k = max(triton.next_power_of_2(nrhs), 4)

    grid = (batch,)

    with torch.no_grad():
        linalg_solve_ex_kernel[grid](
            A_work,
            LU,
            B_work,
            X,
            info,
            n,
            nrhs,
            A_work.stride(0),
            A_work.stride(1),
            LU.stride(0),
            LU.stride(1),
            B_work.stride(0),
            B_work.stride(1),
            X.stride(0),
            X.stride(1),
            BLOCK_N=block_n,
            BLOCK_K=block_k,
        )

    result = X.reshape(B.shape)
    info = info.reshape(batch_shape)

    if check_errors and torch.any(info != 0):
        raise torch.linalg.LinAlgError(
            "linalg.solve_ex: The diagonal element of the LU decomposition is zero."
        )

    return result, info
