# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry, tl_extra_shim

tld = tl_extra_shim

logger = logging.getLogger(__name__)

# Tiled (register-resident) Jacobi covers N up to this bound; larger N uses
# the global-memory pair-wise kernel. The bound matches the register budget of
# a single program holding an N x N float32 block in SRAM.
_EIGH_TILE_MAX_N = 64


@libentry()
@triton.jit
def _eig_2x2_kernel(A, eigenvalues, eigenvectors, N, stride_a, stride_e, stride_v):
    """Compute eigenpairs of 2x2 symmetric matrices using the closed form."""
    pid = tl.program_id(0)
    if pid >= N:
        return

    # A is (N, 2, 2) stored as (N, 4): [a, d, d, b].
    a = tl.load(A + pid * stride_a + 0)
    d = tl.load(A + pid * stride_a + 1)
    b = tl.load(A + pid * stride_a + 3)

    # [a d; d b] -> eigenvalues (a+b)/2 +/- sqrt(((a-b)/2)^2 + d^2)
    trace = (a + b) / 2.0
    diff = (a - b) / 2.0
    disc = tl.sqrt(diff * diff + d * d)

    ev_max = trace + disc
    ev_min = trace - disc

    tl.store(eigenvalues + pid * stride_e + 0, ev_min)
    tl.store(eigenvalues + pid * stride_e + 1, ev_max)

    # Jacobi rotation diagonalising [a d; d b]: theta = atan2(2d, a - b) / 2.
    # The rotation is orthonormal by construction and atan2 handles every
    # degenerate case: d == 0 (theta = 0 or pi/2), a == b, all-zero. Column 0
    # is the eigenvector for ev_min, column 1 for ev_max (ascending pairing).
    theta = 0.5 * tld.atan2(2.0 * d, a - b)
    c = tl.cos(theta)
    s = tl.sin(theta)
    tl.store(eigenvectors + pid * stride_v + 2 * 0 + 0, s)
    tl.store(eigenvectors + pid * stride_v + 2 * 1 + 0, -c)
    tl.store(eigenvectors + pid * stride_v + 2 * 0 + 1, c)
    tl.store(eigenvectors + pid * stride_v + 2 * 1 + 1, s)


@libentry()
@triton.jit
def _jacobi_eigh_tile_kernel(
    A,
    V,
    W,
    N: tl.constexpr,
    SWEEPS: tl.constexpr,
    BLOCK_N: tl.constexpr,
    COMPUTE_V: tl.constexpr,
):
    """Symmetric eigendecomposition of one N x N matrix in registers via Jacobi.

    One program per batch element. The whole matrix and the accumulator V
    reside in registers; each sweep zeroes off-diagonals pair by pair.
    Eigenvalues are the final diagonal; V accumulates the rotations. When
    COMPUTE_V is False the V accumulator is skipped (eigenvalues do not depend
    on V).
    """
    batch = tl.program_id(0)
    r = tl.arange(0, BLOCK_N)
    c = tl.arange(0, BLOCK_N)
    rr = r[:, None]
    cc = c[None, :]
    mask = (rr < N) & (cc < N)
    base = A + batch * N * N

    g = tl.load(base + rr * N + cc, mask=mask, other=0.0).to(tl.float32)
    v = tl.where((rr == cc) & mask, 1.0, 0.0)
    eps = 1.0e-20

    sweep = 0
    while sweep < SWEEPS:
        p = 0
        while p < N - 1:
            q = p + 1
            while q < N:
                diag_p = tl.sum(tl.where((rr == p) & (cc == p), g, 0.0))
                diag_q = tl.sum(tl.where((rr == q) & (cc == q), g, 0.0))
                off = tl.sum(tl.where((rr == p) & (cc == q), g, 0.0))
                abs_off = tl.abs(off)
                threshold = 1.0e-7 * tl.sqrt(tl.abs(diag_p * diag_q) + eps)
                active = abs_off > threshold

                safe_off = tl.where(active, off, 1.0)
                tau = (diag_q - diag_p) / (2.0 * safe_off)
                sign_tau = tl.where(tau >= 0.0, 1.0, -1.0)
                t = sign_tau / (tl.abs(tau) + tl.sqrt(1.0 + tau * tau))
                crot = tl.rsqrt(1.0 + t * t)
                srot = t * crot
                crot = tl.where(active, crot, 1.0)
                srot = tl.where(active, srot, 0.0)

                col_p = tl.sum(tl.where(cc == p, g, 0.0), axis=1)
                col_q = tl.sum(tl.where(cc == q, g, 0.0), axis=1)
                row_p = tl.sum(tl.where(rr == p, g, 0.0), axis=0)
                row_q = tl.sum(tl.where(rr == q, g, 0.0), axis=0)

                new_col_p = crot * col_p - srot * col_q
                new_col_q = srot * col_p + crot * col_q
                new_row_p = crot * row_p - srot * row_q
                new_row_q = srot * row_p + crot * row_q
                g = tl.where(cc == p, new_col_p[:, None], g)
                g = tl.where(cc == q, new_col_q[:, None], g)
                g = tl.where(rr == p, new_row_p[None, :], g)
                g = tl.where(rr == q, new_row_q[None, :], g)

                new_pp = (
                    crot * crot * diag_p
                    - 2.0 * crot * srot * off
                    + srot * srot * diag_q
                )
                new_qq = (
                    srot * srot * diag_p
                    + 2.0 * crot * srot * off
                    + crot * crot * diag_q
                )
                g = tl.where((rr == p) & (cc == p), new_pp, g)
                g = tl.where((rr == q) & (cc == q), new_qq, g)
                g = tl.where(((rr == p) & (cc == q)) | ((rr == q) & (cc == p)), 0.0, g)

                if COMPUTE_V:
                    vec_p = tl.sum(tl.where(cc == p, v, 0.0), axis=1)
                    vec_q = tl.sum(tl.where(cc == q, v, 0.0), axis=1)
                    new_vec_p = crot * vec_p - srot * vec_q
                    new_vec_q = srot * vec_p + crot * vec_q
                    v = tl.where(cc == p, new_vec_p[:, None], v)
                    v = tl.where(cc == q, new_vec_q[:, None], v)
                q += 1
            p += 1
        sweep += 1

    diag = tl.sum(tl.where(rr == cc, g, 0.0), axis=1)
    tl.store(W + batch * N + r, diag, mask=r < N)
    if COMPUTE_V:
        tl.store(V + batch * N * N + rr * N + cc, v, mask=mask)


@libentry()
@triton.jit
def _jacobi_eigh_sort_kernel(
    W_IN,
    V_IN,
    W_OUT,
    V_OUT,
    N: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    """Sort eigenvalues ascending and permute eigenvector columns to match.

    One program per (batch, column). Each output column's rank is the number of
    input eigenvalues strictly less than it (ties broken by index), giving a
    stable ascending permutation.
    """
    batch = tl.program_id(0)
    col = tl.program_id(1)
    rows = tl.arange(0, BLOCK_N)
    row_mask = rows < N

    eval_col = tl.load(W_IN + batch * N + col)
    rank = tl.full((), 0, dtype=tl.int32)
    for other in tl.static_range(0, BLOCK_N):
        eval_other = tl.where(other < N, tl.load(W_IN + batch * N + other), 1.0e38)
        rank += (
            (eval_other < eval_col) | ((eval_other == eval_col) & (other < col))
        ).to(tl.int32)

    vec = tl.load(
        V_IN + batch * N * N + rows * N + col,
        mask=row_mask,
        other=0.0,
    )
    tl.store(W_OUT + batch * N + rank, eval_col)
    tl.store(V_OUT + batch * N * N + rows * N + rank, vec, mask=row_mask)


@libentry()
@triton.jit
def _jacobi_eigh_global_init_kernel(
    A,
    WORK,
    V,
    N: tl.constexpr,
    BLOCK_N: tl.constexpr,
    COMPUTE_V: tl.constexpr,
):
    """Copy A into the working buffer and initialise V to the identity."""
    batch = tl.program_id(0)
    r = tl.arange(0, BLOCK_N)
    c = tl.arange(0, BLOCK_N)
    rr = r[:, None]
    cc = c[None, :]
    mask = (rr < N) & (cc < N)
    a_base = A + batch * N * N
    w_base = WORK + batch * N * N
    v_base = V + batch * N * N
    val = tl.load(a_base + rr * N + cc, mask=mask, other=0.0)
    tl.store(w_base + rr * N + cc, val, mask=mask)
    if COMPUTE_V:
        ident = tl.where(rr == cc, 1.0, 0.0)
        tl.store(v_base + rr * N + cc, ident, mask=mask)


@libentry()
@triton.jit
def _jacobi_eigh_global_cs_kernel(
    WORK,
    CS,
    N,
    STEP,
    ROUND: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    """Read the rotation parameters (c, s) for one round-robin pair.

    One program per (batch, pair). Loads the 2x2 diagonal block at (p, q) of
    WORK (read-only) and writes the cosine/sine into the CS buffer. Splitting
    parameter computation from the column/row stores lets the pair's columns
    and rows be updated in two separate race-free passes.
    """
    batch = tl.program_id(0)
    pair = tl.program_id(1)
    ring = ROUND - 1
    pos_p = pair
    pos_q = ROUND - 1 - pair
    p = tl.where(pos_p == 0, 0, ((pos_p + ring - STEP - 1) % ring) + 1)
    q = tl.where(pos_q == 0, 0, ((pos_q + ring - STEP - 1) % ring) + 1)
    valid = (p < N) & (q < N)
    swap = p > q
    p2 = tl.where(swap, q, p)
    q2 = tl.where(swap, p, q)

    w_base = WORK + batch * N * N
    diag_p = tl.load(w_base + p2 * N + p2)
    diag_q = tl.load(w_base + q2 * N + q2)
    off = tl.load(w_base + p2 * N + q2)
    abs_off = tl.abs(off)
    eps = 1.0e-20
    threshold = 1.0e-7 * tl.sqrt(tl.abs(diag_p * diag_q) + eps)
    active = (abs_off > threshold) & valid

    safe_off = tl.where(active, off, 1.0)
    tau = (diag_q - diag_p) / (2.0 * safe_off)
    sign_tau = tl.where(tau >= 0.0, 1.0, -1.0)
    t = sign_tau / (tl.abs(tau) + tl.sqrt(1.0 + tau * tau))
    crot = tl.rsqrt(1.0 + t * t)
    srot = t * crot
    crot = tl.where(active, crot, 1.0)
    srot = tl.where(active, srot, 0.0)

    cs_base = CS + batch * (ROUND // 2) * 2
    tl.store(cs_base + pair * 2 + 0, crot)
    tl.store(cs_base + pair * 2 + 1, srot)


@libentry()
@triton.jit
def _jacobi_eigh_global_col_kernel(
    WORK,
    V,
    CS,
    N,
    STEP,
    ROUND: tl.constexpr,
    BLOCK_N: tl.constexpr,
    COMPUTE_V: tl.constexpr,
):
    """Apply the right rotation A := A J and accumulate V := V J.

    Each pair updates its own two columns of WORK and V. Columns touched in
    one round-robin step are disjoint across pairs, so the parallel column
    writes do not race.
    """
    batch = tl.program_id(0)
    pair = tl.program_id(1)
    rows = tl.arange(0, BLOCK_N)
    ring = ROUND - 1
    pos_p = pair
    pos_q = ROUND - 1 - pair
    p = tl.where(pos_p == 0, 0, ((pos_p + ring - STEP - 1) % ring) + 1)
    q = tl.where(pos_q == 0, 0, ((pos_q + ring - STEP - 1) % ring) + 1)
    valid = (p < N) & (q < N)
    swap = p > q
    p2 = tl.where(swap, q, p)
    q2 = tl.where(swap, p, q)

    cs_base = CS + batch * (ROUND // 2) * 2
    crot = tl.load(cs_base + pair * 2 + 0)
    srot = tl.load(cs_base + pair * 2 + 1)

    row_mask = (rows < N) & valid
    w_base = WORK + batch * N * N
    v_base = V + batch * N * N
    col_p = tl.load(w_base + rows * N + p2, mask=row_mask, other=0.0)
    col_q = tl.load(w_base + rows * N + q2, mask=row_mask, other=0.0)
    new_col_p = crot * col_p - srot * col_q
    new_col_q = srot * col_p + crot * col_q
    tl.store(w_base + rows * N + p2, new_col_p, mask=row_mask)
    tl.store(w_base + rows * N + q2, new_col_q, mask=row_mask)

    if COMPUTE_V:
        vp = tl.load(v_base + rows * N + p2, mask=row_mask, other=0.0)
        vq = tl.load(v_base + rows * N + q2, mask=row_mask, other=0.0)
        tl.store(v_base + rows * N + p2, crot * vp - srot * vq, mask=row_mask)
        tl.store(v_base + rows * N + q2, srot * vp + crot * vq, mask=row_mask)


@libentry()
@triton.jit
def _jacobi_eigh_global_row_kernel(
    WORK,
    CS,
    N,
    STEP,
    ROUND: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    """Apply the left rotation A := J^T A to complete one similarity step.

    Each pair updates its own two rows of WORK. Rows touched in one
    round-robin step are disjoint across pairs, so the parallel row writes
    do not race. Combined with the column pass this realizes A := J^T A J.
    """
    batch = tl.program_id(0)
    pair = tl.program_id(1)
    cols = tl.arange(0, BLOCK_N)
    ring = ROUND - 1
    pos_p = pair
    pos_q = ROUND - 1 - pair
    p = tl.where(pos_p == 0, 0, ((pos_p + ring - STEP - 1) % ring) + 1)
    q = tl.where(pos_q == 0, 0, ((pos_q + ring - STEP - 1) % ring) + 1)
    valid = (p < N) & (q < N)
    swap = p > q
    p2 = tl.where(swap, q, p)
    q2 = tl.where(swap, p, q)

    cs_base = CS + batch * (ROUND // 2) * 2
    crot = tl.load(cs_base + pair * 2 + 0)
    srot = tl.load(cs_base + pair * 2 + 1)

    col_mask = (cols < N) & valid
    w_base = WORK + batch * N * N
    row_p = tl.load(w_base + p2 * N + cols, mask=col_mask, other=0.0)
    row_q = tl.load(w_base + q2 * N + cols, mask=col_mask, other=0.0)
    new_row_p = crot * row_p - srot * row_q
    new_row_q = srot * row_p + crot * row_q
    tl.store(w_base + p2 * N + cols, new_row_p, mask=col_mask)
    tl.store(w_base + q2 * N + cols, new_row_q, mask=col_mask)


@libentry()
@triton.jit
def _jacobi_eigh_extract_diag_kernel(
    WORK,
    W,
    N,
    BLOCK_N: tl.constexpr,
):
    """Copy the diagonal of the converged working matrix into the eigenvalue vector."""
    batch = tl.program_id(0)
    rows = tl.arange(0, BLOCK_N)
    mask = rows < N
    val = tl.load(WORK + batch * N * N + rows * N + rows, mask=mask, other=0.0)
    tl.store(W + batch * N + rows, val, mask=mask)


@libentry()
@triton.jit
def _complex_to_real_embedding_kernel(
    A_RI,
    R,
    M: tl.constexpr,
    N: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """Embed a complex Hermitian A (n x n) into a real symmetric R (2n x 2n).

    R = [[ Re(A), -Im(A) ], [ Im(A), Re(A) ) ]]. R is real symmetric with the
    same eigenvalues as A (each with doubled multiplicity); its real
    eigenvectors [x; y] recover the complex eigenvector x + i*y.
    """
    batch = tl.program_id(0)
    offsets = tl.arange(0, BLOCK_SIZE)
    total = 4 * M * N
    mask = offsets < total
    row = offsets // (2 * N)
    col = offsets - row * (2 * N)
    src_row = tl.where(row < M, row, row - M)
    src_col = tl.where(col < N, col, col - N)
    comp = tl.where((row < M) & (col >= N), 1, 0)
    comp = tl.where((row >= M) & (col < N), 1, comp)
    vals = tl.load(
        A_RI + batch * M * N * 2 + (src_row * N + src_col) * 2 + comp,
        mask=mask,
        other=0.0,
    )
    sign = tl.where((row < M) & (col >= N), -1.0, 1.0)
    tl.store(R + batch * 4 * M * N + offsets, vals * sign, mask=mask)


@libentry()
@triton.jit
def _complex_eigh_pick_kernel(
    W_REAL,
    V_REAL,
    W,
    V_RI,
    N: tl.constexpr,
    REAL_N: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    """Recover complex eigenpairs from the real embedding's spectrum.

    The real embedding has each eigenvalue twice (multiplicity 2); we take the
    first of each pair. Each real eigenvector [x; y] (x, y in R^n) maps to the
    complex eigenvector x + i*y. Columns are re-orthonormalised (Gram-Schmidt)
    so the returned V is unitary despite the embedding's sign freedom.
    """
    batch = tl.program_id(0)
    rows = tl.arange(0, BLOCK_N)
    cols = tl.arange(0, BLOCK_N)
    row_mask = rows < N
    col_mask = cols < N
    # Even columns carry the first copy of each repeated eigenvalue.
    src_cols = cols * 2
    base = V_REAL + batch * (2 * N) * REAL_N
    vx = tl.load(
        base + rows[:, None] * REAL_N + src_cols[None, :],
        mask=row_mask[:, None] & col_mask[None, :],
        other=0.0,
    )
    vy = tl.load(
        base + (N + rows[:, None]) * REAL_N + src_cols[None, :],
        mask=row_mask[:, None] & col_mask[None, :],
        other=0.0,
    )

    out_base = V_RI + batch * N * N * 2
    offsets = rows[:, None] * N + cols[None, :]
    mask = row_mask[:, None] & col_mask[None, :]

    # Gram-Schmidt across columns for unitarity, then write real/imag interleaved.
    c = 0
    while c < N:
        cur_x = tl.sum(tl.where(cols[None, :] == c, vx, 0.0), axis=1)
        cur_y = tl.sum(tl.where(cols[None, :] == c, vy, 0.0), axis=1)
        p = 0
        while p < c:
            prev_x = tl.sum(tl.where(cols[None, :] == p, vx, 0.0), axis=1)
            prev_y = tl.sum(tl.where(cols[None, :] == p, vy, 0.0), axis=1)
            coeff_r = tl.sum(
                tl.where(row_mask, prev_x * cur_x + prev_y * cur_y, 0.0), axis=0
            )
            coeff_i = tl.sum(
                tl.where(row_mask, prev_x * cur_y - prev_y * cur_x, 0.0), axis=0
            )
            cur_x = cur_x - prev_x * coeff_r + prev_y * coeff_i
            cur_y = cur_y - prev_x * coeff_i - prev_y * coeff_r
            p += 1
        norm_sq = tl.sum(tl.where(row_mask, cur_x * cur_x + cur_y * cur_y, 0.0), axis=0)
        inv_norm = tl.rsqrt(tl.maximum(norm_sq, 1.0e-20))
        cur_x = cur_x * inv_norm
        cur_y = cur_y * inv_norm
        vx = tl.where(cols[None, :] == c, cur_x[:, None], vx)
        vy = tl.where(cols[None, :] == c, cur_y[:, None], vy)
        c += 1

    tl.store(out_base + offsets * 2, vx, mask=mask)
    tl.store(out_base + offsets * 2 + 1, vy, mask=mask)

    # Eigenvalues: take the even-indexed entries (first of each pair).
    w_idx = tl.arange(0, BLOCK_N)
    w_mask = w_idx < N
    w_vals = tl.load(W_REAL + batch * REAL_N + w_idx * 2, mask=w_mask, other=0.0)
    tl.store(W + batch * N + w_idx, w_vals, mask=w_mask)


def _symmetrise_by_uplo(A, UPLO):
    """Build a full symmetric/Hermitian matrix from the chosen triangle of A.

    eigh only uses one triangle; the other is taken as its (conjugate) transpose.
    Construction avoids triu/tril and diag_embed on the (possibly complex) tensor:
    those backend overrides are not specialised for complex dtypes. A real index
    mask selects the triangle; the diagonal is fixed in place after mirroring so
    it is not doubled.
    """
    n = A.shape[-1]
    idx = torch.arange(n, device=A.device)
    if UPLO == "U":
        tri_mask = idx[None, :] >= idx[:, None]  # upper triangle incl. diagonal
    else:
        tri_mask = idx[None, :] <= idx[:, None]  # lower triangle incl. diagonal

    tri = A * tri_mask  # bool mask broadcast; elementwise mul, no kernel override issue
    if A.is_complex():
        sym = tri + tri.mH
    else:
        sym = tri + tri.transpose(-2, -1)
    # The diagonal was mirrored (doubed); restore it from the single-triangle value.
    sym = sym.clone()
    sym.diagonal(dim1=-2, dim2=-1).copy_(tri.diagonal(dim1=-2, dim2=-1))
    return sym


def _jacobi_eigh_real(A, n, compute_v=True):
    """Real symmetric eigendecomposition via the global-memory Jacobi path.

    Each sweep drives every (p, q) pair through a round-robin ordering. Per
    step, ROUND/2 disjoint pairs are rotated in parallel through three passes
    — compute (c, s), right-rotate the columns (A := A J, V := V J), then
    left-rotate the rows (A := J^T A) — so a sweep completes in O(N) launches.

    When compute_v is False, eigenvector computation and storage are skipped;
    eigenvalues do not depend on V.
    """
    batch = A.shape[0]
    block_n = triton.next_power_of_2(n)
    sweeps = 14 if n <= 17 else 12

    W = torch.empty((batch, n), dtype=torch.float32, device=A.device)
    if compute_v:
        V = torch.empty((batch, n, n), dtype=torch.float32, device=A.device)
    else:
        # A valid-but-unused pointer: the kernels guard every V access behind
        # COMPUTE_V, so the buffer is never read or written here. Triton still
        # needs a real pointer to compile, so a single-element tensor suffices.
        V = torch.empty((1,), dtype=torch.float32, device=A.device)

    round_n = n if n % 2 == 0 else n + 1
    half = round_n // 2
    work = torch.empty((batch, n, n), dtype=torch.float32, device=A.device)
    cs = torch.empty((batch, half, 2), dtype=torch.float32, device=A.device)
    with torch_device_fn.device(A.device):
        _jacobi_eigh_global_init_kernel[(batch,)](
            A, work, V, N=n, BLOCK_N=block_n, COMPUTE_V=compute_v, num_warps=4
        )
        for _ in range(sweeps):
            for step in range(round_n - 1):
                _jacobi_eigh_global_cs_kernel[(batch, half)](
                    work,
                    cs,
                    n,
                    step,
                    ROUND=round_n,
                    BLOCK_N=block_n,
                    num_warps=4,
                )
                _jacobi_eigh_global_col_kernel[(batch, half)](
                    work,
                    V,
                    cs,
                    n,
                    step,
                    ROUND=round_n,
                    BLOCK_N=block_n,
                    COMPUTE_V=compute_v,
                    num_warps=4,
                )
                _jacobi_eigh_global_row_kernel[(batch, half)](
                    work,
                    cs,
                    n,
                    step,
                    ROUND=round_n,
                    BLOCK_N=block_n,
                    num_warps=4,
                )
        _jacobi_eigh_extract_diag_kernel[(batch,)](
            work, W, n, BLOCK_N=block_n, num_warps=4
        )
    Ws = W

    # Ascending sort of eigenvalues; permute eigenvector columns only when V
    # was computed.
    W_sorted = torch.empty_like(Ws)
    if compute_v:
        V_sorted = torch.empty_like(V)
        with torch_device_fn.device(A.device):
            _jacobi_eigh_sort_kernel[(batch, n)](
                Ws, V, W_sorted, V_sorted, N=n, BLOCK_N=block_n, num_warps=1
            )
        return W_sorted, V_sorted
    else:
        # Eigenvalues only: sort W ascending on device (no eigenvectors to
        # permute, so the sort kernel is not needed).
        W_sorted, _ = Ws.sort(dim=-1)
        V_dummy = torch.empty((0,), dtype=torch.float32, device=A.device)
        return W_sorted, V_dummy


def _jacobi_eigh_complex(A, n, compute_v=True):
    """Complex Hermitian eigendecomposition via real embedding.

    A -> real symmetric R (2n x 2n) -> real Jacobi eigh -> recover complex (W, V).
    Computed in float32; complex128 is widened only at the return cast. When
    compute_v is False the pick kernel is skipped (eigenvalues come from the
    real path alone).
    """
    batch = A.shape[0]
    a_ri = torch.view_as_real(A.contiguous()).reshape(batch, n, n, 2)
    real_n = 2 * n
    R = torch.empty((batch, real_n, real_n), dtype=torch.float32, device=A.device)
    block_embed = triton.next_power_of_2(4 * n * n)
    with torch_device_fn.device(A.device):
        _complex_to_real_embedding_kernel[(batch,)](
            a_ri, R, M=n, N=n, BLOCK_SIZE=block_embed, num_warps=1
        )

    W_real, V_real = _jacobi_eigh_real(R, real_n, compute_v=compute_v)

    # The embedding doubles each eigenvalue; take the even-indexed entries.
    w_idx = torch.arange(0, n, device=A.device) * 2
    W = W_real[..., w_idx]

    if not compute_v:
        V_dummy = torch.empty((0,), dtype=A.dtype, device=A.device)
        return W, V_dummy

    # Pick writes float32 real/imag regardless of input complex width; collect
    # into a complex64 buffer and cast to the target dtype at the return.
    V_f32 = torch.empty((batch, n, n), dtype=torch.complex64, device=A.device)
    v_ri = torch.view_as_real(V_f32.contiguous()).reshape(batch, n, n, 2)
    block_n = triton.next_power_of_2(n)
    with torch_device_fn.device(A.device):
        _complex_eigh_pick_kernel[(batch,)](
            W_real,
            V_real,
            W,
            v_ri,
            N=n,
            REAL_N=real_n,
            BLOCK_N=block_n,
            num_warps=1,
        )
    V = V_f32.to(A.dtype)
    return W, V


def linalg_eigh(A, UPLO="L", compute_v=True):
    """Eigenvalue decomposition of symmetric/Hermitian matrices on device.

    Dispatch by size (all paths are Triton kernels):
      - n == 2  : closed-form 2x2 kernel.
      - n < 2   : diagonal as eigenvalues, identity as eigenvectors.
      - 3 <= n <= 64 (real) / 2n <= 128 (complex): register-resident Jacobi.
      - larger  : global-memory pair-wise Jacobi.
    Complex inputs use a real embedding; eigenvalues are real, eigenvectors
    complex and unitary. fp16/bf16 are widened to fp32 and cast back.

    When compute_v is False, only eigenvalues are computed and eigenvectors
    are returned as an empty tensor.
    """
    logger.debug("GEMS LINALG_EIGH")

    if A.ndim < 2 or A.shape[-1] != A.shape[-2]:
        raise ValueError(f"Input matrix must be square, got shape {A.shape}")

    n = A.shape[-1]
    batch_shape = A.shape[:-2]
    out_dtype = A.dtype
    is_complex = A.is_complex()

    # Eigenvector return type for the compute_v=False case: empty, input dtype.
    empty_v = lambda: torch.empty((0,), dtype=out_dtype, device=A.device)

    if n < 2:
        # 0x0 / 1x1: eigenvalues are the diagonal, eigenvectors the identity.
        # UPLO is irrelevant here (single diagonal element); avoid constructing a
        # symmetrised matrix so no complex-host ops are needed for trivial inputs.
        # For Hermitian input the diagonal is real; take the real part. The
        # identity eigenvectors are built as real then cast, since the overridden
        # ones_like does not specialise complex dtypes.
        diag = A.diagonal(dim1=-2, dim2=-1).clone()
        if is_complex:
            w_dtype = torch.float32 if out_dtype == torch.complex64 else torch.float64
            eigenvalues = diag.real.to(w_dtype)
        else:
            eigenvalues = diag.to(out_dtype)
        if not compute_v:
            return eigenvalues, empty_v()
        # Identity eigenvectors on the input's last two dims, built in a real
        # dtype then cast (avoids complex ones_like).
        eye = torch.eye(n, dtype=torch.float32, device=A.device)
        eye_shape = (*batch_shape, n, n)
        eigenvectors = eye.expand(eye_shape).contiguous().to(out_dtype)
        return eigenvalues, eigenvectors

    # eigh uses only one triangle; build the full symmetric/Hermitian matrix.
    A_sym = _symmetrise_by_uplo(A, UPLO)

    # fp16/bf16 (real) are widened to fp32 for the Triton kernels.
    if not is_complex and out_dtype in (torch.float16, torch.bfloat16):
        A_sym = A_sym.to(torch.float32)

    if n == 2 and not is_complex:
        A_flat = A_sym.reshape(-1, 2, 2)
        eigenvalues = torch.zeros(
            A_flat.shape[0], 2, dtype=A_flat.dtype, device=A_flat.device
        )
        eigenvectors = torch.zeros_like(A_flat)
        grid = (A_flat.shape[0],)
        with torch_device_fn.device(A_sym.device):
            _eig_2x2_kernel[grid](
                A_flat,
                eigenvalues,
                eigenvectors,
                A_flat.shape[0],
                A_flat.stride(0),
                eigenvalues.stride(0),
                eigenvectors.stride(0),
            )

        eigenvalues = eigenvalues.reshape(*batch_shape, 2)
        if not compute_v:
            return eigenvalues.to(out_dtype), empty_v()

        eigenvectors = eigenvectors.reshape(*batch_shape, 2, 2)
    else:
        # General case: Jacobi (real) or real embedding (complex). Both operate
        # on a flattened (batch, n, n) layout and reshape back at the end.
        A_flat = A_sym.reshape(-1, n, n)
        if is_complex:
            W, V = _jacobi_eigh_complex(A_flat, n, compute_v=compute_v)
        else:
            W, V = _jacobi_eigh_real(A_flat, n, compute_v=compute_v)
        eigenvalues = W.reshape(*batch_shape, n)
        if compute_v:
            eigenvectors = V.reshape(*batch_shape, n, n)
        else:
            eigenvectors = empty_v()

    # Eigenvalues are always real; eigenvectors match the input dtype. For
    # complex input, complex64 -> float32 eigenvalues, complex128 -> float64.
    # For real input, eigenvalues/eigenvectors both return the input dtype
    # (fp16/bf16 results cast back from the fp32 computation above).
    if is_complex:
        w_dtype = torch.float32 if out_dtype == torch.complex64 else torch.float64
        eigenvalues = eigenvalues.to(w_dtype)
    else:
        eigenvalues = eigenvalues.to(out_dtype)
        if compute_v:
            eigenvectors = eigenvectors.to(out_dtype)

    return eigenvalues, eigenvectors
