# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
#
# Triton implementation of linalg_pinv (Moore-Penrose pseudoinverse).
# Two Triton paths, both based on one-sided Jacobi SVD:
#   * small matrices (m, n <= 32): a single fused kernel keeps the whole matrix
#     in registers and unrolls the sweeps statically.
#   * larger matrices: the matrix stays in global memory and each Jacobi round
#     rotates n/2 disjoint column pairs in parallel, so nothing is unrolled and
#     register pressure stays bounded.
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry

logger = logging.getLogger(__name__)

# Largest dimension handled by the fused register-resident kernel. Above this the
# statically unrolled sweeps blow up compile time and the matrix no longer fits
# in registers, so the blocked global-memory path takes over.
_FUSED_MAX_DIM = 32

# Cyclic one-sided Jacobi converges in well under 10 sweeps for practical inputs;
# the blocked path uses a fixed count to avoid a device-to-host sync per sweep.
_BLOCKED_NUM_SWEEPS = 10


@libentry()
@triton.jit
def _jacobi_pinv_kernel(
    A_ptr,
    OUT_ptr,
    m: tl.constexpr,
    n: tl.constexpr,
    k: tl.constexpr,
    a_batch_stride,
    out_batch_stride,
    atol_val,
    rtol_val,
    NUM_SWEEPS: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    BLOCK_K: tl.constexpr,
):
    """
    Fused Jacobi SVD + pseudoinverse kernel.
    Each program handles one batch element.
    k = min(m, n).

    Algorithm (one-sided Jacobi on columns of A):
      1. Load A (m x n) into W
      2. Initialize V = I_n
      3. For each sweep, for column pairs (p, q):
         - Compute alpha = W[:,p]^T W[:,p], beta = W[:,q]^T W[:,q], gamma = W[:,p]^T W[:,q]
         - Compute Jacobi rotation (c, s) to zero gamma
         - Rotate columns p, q of W and V
      4. After convergence: sigma_j = ||W[:,j]||, U[:,j] = W[:,j]/sigma_j
      5. pinv = V @ diag(1/S_filt) @ U^T
    """
    batch_idx = tl.program_id(0)

    a_offset = batch_idx * a_batch_stride
    out_offset = batch_idx * out_batch_stride

    # Load A into W [BLOCK_M, BLOCK_N]
    rows = tl.arange(0, BLOCK_M)
    cols = tl.arange(0, BLOCK_N)

    # Load full matrix
    W = tl.load(
        A_ptr + a_offset + rows[:, None] * n + cols[None, :],
        mask=(rows[:, None] < m) & (cols[None, :] < n),
        other=0.0,
    )

    # V = I_n [BLOCK_N, BLOCK_N]
    vcols = tl.arange(0, BLOCK_N)
    vrows = tl.arange(0, BLOCK_N)
    V = tl.where(vrows[:, None] == vcols[None, :], 1.0, 0.0).to(tl.float32)

    # Jacobi sweeps
    for _sweep in tl.static_range(0, NUM_SWEEPS):
        for p in tl.static_range(0, BLOCK_N):
            for q in tl.static_range(0, BLOCK_N):
                if q > p:
                    if p < n and q < n:
                        # Extract columns p and q from in-register W
                        # Use the in-register W
                        # Use the in-register W
                        # W[:, p] where col == p
                        mask_p = cols[None, :] == p
                        mask_q = cols[None, :] == q

                        # Extract columns via reduction
                        w_p = tl.sum(tl.where(mask_p, W, 0.0), axis=1)  # [BLOCK_M]
                        w_q = tl.sum(tl.where(mask_q, W, 0.0), axis=1)  # [BLOCK_M]

                        # Gram elements
                        alpha = tl.sum(w_p * w_p, axis=0)
                        beta = tl.sum(w_q * w_q, axis=0)
                        gamma = tl.sum(w_p * w_q, axis=0)

                        # Skip if off-diagonal is tiny
                        scale = tl.maximum(alpha, beta) + 1e-30
                        should_rotate = tl.abs(gamma) > 1e-10 * scale

                        # Jacobi rotation: zero the off-diagonal
                        diff = beta - alpha
                        tau = diff / (2.0 * gamma + 1e-30)
                        sign_tau = tl.where(tau >= 0.0, 1.0, -1.0)
                        t = sign_tau / (tl.abs(tau) + tl.sqrt(tau * tau + 1.0))
                        c = 1.0 / tl.sqrt(1.0 + t * t)
                        s = t * c

                        c = tl.where(should_rotate, c, 1.0)
                        s = tl.where(should_rotate, s, 0.0)

                        # Rotate W: W[:, p] = c*w_p - s*w_q, W[:, q] = s*w_p + c*w_q
                        new_wp = c * w_p - s * w_q
                        new_wq = s * w_p + c * w_q

                        W = tl.where(mask_p, new_wp[:, None], W)
                        W = tl.where(mask_q, new_wq[:, None], W)

                        # Rotate V: V[:, p], V[:, q]
                        vmask_p = vcols[None, :] == p
                        vmask_q = vcols[None, :] == q
                        v_p = tl.sum(tl.where(vmask_p, V, 0.0), axis=1)  # [BLOCK_N]
                        v_q = tl.sum(tl.where(vmask_q, V, 0.0), axis=1)  # [BLOCK_N]
                        new_vp = c * v_p - s * v_q
                        new_vq = s * v_p + c * v_q
                        V = tl.where(vmask_p, new_vp[:, None], V)
                        V = tl.where(vmask_q, new_vq[:, None], V)

    # Compute singular values and pseudoinverse
    # sigma_j = ||W[:, j]||, U[:, j] = W[:, j] / sigma_j
    # pinv[i, j] = sum_l V[i, l] * (1/sigma_l) * U[j, l]  (where sigma_l > thr)

    # First find sigma_max for threshold
    sigma_max = tl.zeros([1], dtype=tl.float32)
    for j in tl.static_range(0, BLOCK_N):
        if j < n:
            mask_j = cols[None, :] == j
            w_j = tl.sum(tl.where(mask_j, W, 0.0), axis=1)
            sj = tl.sqrt(tl.sum(w_j * w_j, axis=0))
            sigma_max = tl.maximum(sigma_max, sj)

    thr = tl.maximum(atol_val, sigma_max * rtol_val)

    # Accumulate pinv = V @ diag(1/s_filt) @ U^T
    # pinv is (n x m)
    out_rows = tl.arange(0, BLOCK_N)  # n
    out_cols = tl.arange(0, BLOCK_M)  # m
    PINV = tl.zeros([BLOCK_N, BLOCK_M], dtype=tl.float32)

    for j in tl.static_range(0, BLOCK_N):
        if j < n:
            mask_j = cols[None, :] == j
            w_j = tl.sum(tl.where(mask_j, W, 0.0), axis=1)  # [BLOCK_M] = U_raw
            sj = tl.sqrt(tl.sum(w_j * w_j, axis=0))
            is_valid = sj > thr

            # pinv contribution = (1/sj) * v_j @ u_j^T
            # where u_j = w_j / sj, so (1/sj) * u_j = w_j / sj^2
            inv_sj_sq = tl.where(is_valid, 1.0 / (sj * sj + 1e-38), 0.0)

            # V[:, j]
            vmask_j = vcols[None, :] == j
            v_j = tl.sum(tl.where(vmask_j, V, 0.0), axis=1)  # [BLOCK_N]

            # Outer: v_j[:, None] * (w_j * inv_sj_sq)[None, :] -> [BLOCK_N, BLOCK_M]
            PINV += v_j[:, None] * (w_j * inv_sj_sq)[None, :]

    # Store output (n x m)
    tl.store(
        OUT_ptr + out_offset + out_rows[:, None] * m + out_cols[None, :],
        PINV,
        mask=(out_rows[:, None] < n) & (out_cols[None, :] < m),
    )


@libentry()
@triton.jit
def _eye_init_kernel(
    V_ptr,
    C,
    v_batch_stride,
    BLOCK: tl.constexpr,
):
    """Write the C x C identity matrix into the accumulated rotation buffer V."""
    batch_idx = tl.program_id(0)
    pid_r = tl.program_id(1)

    rows = pid_r * BLOCK + tl.arange(0, BLOCK)
    base = V_ptr + batch_idx * v_batch_stride

    for c0 in tl.range(0, C, BLOCK):
        cols = c0 + tl.arange(0, BLOCK)
        val = tl.where(rows[:, None] == cols[None, :], 1.0, 0.0)
        tl.store(
            base + rows[:, None] * C + cols[None, :],
            val,
            mask=(rows[:, None] < C) & (cols[None, :] < C),
        )


@libentry()
@triton.jit
def _jacobi_round_kernel(
    W_ptr,
    V_ptr,
    R,
    C,
    w_batch_stride,
    v_batch_stride,
    round_idx,
    ring,
    BLOCK_R: tl.constexpr,
    BLOCK_C: tl.constexpr,
):
    """One round of a parallel one-sided Jacobi sweep.

    Column pairs are formed with the circle method: the last player of an
    even-sized field is fixed while the remaining `ring` players rotate. Every
    round therefore yields disjoint pairs, so all pairs in a round can be
    rotated concurrently, and `ring` rounds cover all C*(C-1)/2 pairs exactly
    once.
    """
    batch_idx = tl.program_id(0)
    pair_idx = tl.program_id(1)

    # Circle-method pairing. `ring` == n_even - 1, the fixed player is `ring`.
    if pair_idx == 0:
        p = ring
        q = round_idx % ring
    else:
        p = (round_idx + pair_idx) % ring
        # round_idx - pair_idx >= -ring, so one +ring makes the modulo positive.
        q = (round_idx - pair_idx + ring) % ring

    if (p < C) & (q < C):
        w_base = W_ptr + batch_idx * w_batch_stride
        v_base = V_ptr + batch_idx * v_batch_stride

        # Gram elements of the column pair, reduced over all R rows.
        alpha = tl.zeros([], dtype=tl.float32)
        beta = tl.zeros([], dtype=tl.float32)
        gamma = tl.zeros([], dtype=tl.float32)
        for r0 in tl.range(0, R, BLOCK_R):
            rows = r0 + tl.arange(0, BLOCK_R)
            rmask = rows < R
            w_p = tl.load(w_base + rows * C + p, mask=rmask, other=0.0)
            w_q = tl.load(w_base + rows * C + q, mask=rmask, other=0.0)
            alpha += tl.sum(w_p * w_p, axis=0)
            beta += tl.sum(w_q * w_q, axis=0)
            gamma += tl.sum(w_p * w_q, axis=0)

        # Jacobi rotation that zeroes the off-diagonal Gram entry.
        scale = tl.maximum(alpha, beta) + 1e-30
        should_rotate = tl.abs(gamma) > 1e-10 * scale
        diff = beta - alpha
        tau = diff / (2.0 * gamma + 1e-30)
        sign_tau = tl.where(tau >= 0.0, 1.0, -1.0)
        t = sign_tau / (tl.abs(tau) + tl.sqrt(tau * tau + 1.0))
        c = 1.0 / tl.sqrt(1.0 + t * t)
        s = t * c
        c = tl.where(should_rotate, c, 1.0)
        s = tl.where(should_rotate, s, 0.0)

        # Apply the rotation to columns p, q of W (R rows).
        for r0 in tl.range(0, R, BLOCK_R):
            rows = r0 + tl.arange(0, BLOCK_R)
            rmask = rows < R
            w_p = tl.load(w_base + rows * C + p, mask=rmask, other=0.0)
            w_q = tl.load(w_base + rows * C + q, mask=rmask, other=0.0)
            tl.store(w_base + rows * C + p, c * w_p - s * w_q, mask=rmask)
            tl.store(w_base + rows * C + q, s * w_p + c * w_q, mask=rmask)

        # Accumulate the same rotation into V (C rows).
        for r0 in tl.range(0, C, BLOCK_C):
            rows = r0 + tl.arange(0, BLOCK_C)
            rmask = rows < C
            v_p = tl.load(v_base + rows * C + p, mask=rmask, other=0.0)
            v_q = tl.load(v_base + rows * C + q, mask=rmask, other=0.0)
            tl.store(v_base + rows * C + p, c * v_p - s * v_q, mask=rmask)
            tl.store(v_base + rows * C + q, s * v_p + c * v_q, mask=rmask)


@libentry()
@triton.jit
def _column_norm_kernel(
    W_ptr,
    S_ptr,
    R,
    C,
    w_batch_stride,
    BLOCK_R: tl.constexpr,
):
    """Singular values: sigma_j = ||W[:, j]|| once the sweeps have converged."""
    batch_idx = tl.program_id(0)
    j = tl.program_id(1)

    if j < C:
        w_base = W_ptr + batch_idx * w_batch_stride
        acc = tl.zeros([], dtype=tl.float32)
        for r0 in tl.range(0, R, BLOCK_R):
            rows = r0 + tl.arange(0, BLOCK_R)
            rmask = rows < R
            w = tl.load(w_base + rows * C + j, mask=rmask, other=0.0)
            acc += tl.sum(w * w, axis=0)
        tl.store(S_ptr + batch_idx * C + j, tl.sqrt(acc))


@libentry()
@triton.jit
def _sigma_max_kernel(
    S_ptr,
    SMAX_ptr,
    C,
    BLOCK_C: tl.constexpr,
):
    """Per-batch largest singular value, used to build the rank cutoff."""
    batch_idx = tl.program_id(0)

    # Singular values are non-negative, so 0.0 is a valid reduction identity.
    mx = tl.zeros([], dtype=tl.float32)
    for c0 in tl.range(0, C, BLOCK_C):
        cols = c0 + tl.arange(0, BLOCK_C)
        cmask = cols < C
        s = tl.load(S_ptr + batch_idx * C + cols, mask=cmask, other=0.0)
        mx = tl.maximum(mx, tl.max(s, axis=0))
    tl.store(SMAX_ptr + batch_idx, mx)


@libentry()
@triton.jit
def _pinv_reconstruct_kernel(
    V_ptr,
    W_ptr,
    S_ptr,
    SMAX_ptr,
    OUT_ptr,
    R,
    C,
    atol_val,
    rtol_val,
    v_batch_stride,
    w_batch_stride,
    out_batch_stride,
    BLOCK_I: tl.constexpr,
    BLOCK_L: tl.constexpr,
    BLOCK_J: tl.constexpr,
):
    """pinv = V @ diag(1/sigma_filt) @ U^T, tiled over the (C x R) output.

    With U[:, j] = W[:, j] / sigma_j the contraction collapses to
    pinv[i, l] = sum_j V[i, j] * W[l, j] / sigma_j^2, so U is never materialized.
    """
    batch_idx = tl.program_id(0)
    pid_i = tl.program_id(1)
    pid_l = tl.program_id(2)

    offs_i = pid_i * BLOCK_I + tl.arange(0, BLOCK_I)
    offs_l = pid_l * BLOCK_L + tl.arange(0, BLOCK_L)

    smax = tl.load(SMAX_ptr + batch_idx)
    thr = tl.maximum(atol_val, smax * rtol_val)

    v_base = V_ptr + batch_idx * v_batch_stride
    w_base = W_ptr + batch_idx * w_batch_stride

    acc = tl.zeros([BLOCK_I, BLOCK_L], dtype=tl.float32)
    for j0 in tl.range(0, C, BLOCK_J):
        offs_j = j0 + tl.arange(0, BLOCK_J)
        jmask = offs_j < C

        sj = tl.load(S_ptr + batch_idx * C + offs_j, mask=jmask, other=0.0)
        is_valid = sj > thr
        inv_sj_sq = tl.where(is_valid, 1.0 / (sj * sj + 1e-38), 0.0)

        v = tl.load(
            v_base + offs_i[:, None] * C + offs_j[None, :],
            mask=(offs_i[:, None] < C) & jmask[None, :],
            other=0.0,
        )
        w = tl.load(
            w_base + offs_l[:, None] * C + offs_j[None, :],
            mask=(offs_l[:, None] < R) & jmask[None, :],
            other=0.0,
        )
        # allow_tf32=False: TF32 keeps only ~10 mantissa bits, which loses far
        # more precision than the float32 tolerance the pinv tests assert.
        acc += tl.dot(v * inv_sj_sq[None, :], tl.trans(w), allow_tf32=False)

    tl.store(
        OUT_ptr + batch_idx * out_batch_stride + offs_i[:, None] * R + offs_l[None, :],
        acc,
        mask=(offs_i[:, None] < C) & (offs_l[None, :] < R),
    )


def _blocked_pinv(W: torch.Tensor, batch: int, R: int, C: int, atol_val, rtol_val):
    """Pseudoinverse of a (batch, R, C) stack with R >= C, kept in global memory.

    W is rotated in place and must already be a private float32 copy.
    Returns the (batch, C, R) pseudoinverse.
    """
    device = W.device

    V = torch.empty(batch, C, C, dtype=torch.float32, device=device)

    # Row-block sizes for the streaming reductions; tuned only to keep a full
    # warp busy while bounding register use, and independent of the shape.
    BLOCK_R = 128
    BLOCK_C = 128

    eye_blocks = triton.cdiv(C, BLOCK_C)
    _eye_init_kernel[(batch, eye_blocks)](V, C, C * C, BLOCK=BLOCK_C)

    # Pad to an even field so the circle method yields disjoint pairs.
    n_even = C if C % 2 == 0 else C + 1
    ring = n_even - 1
    n_pairs = n_even // 2

    for _sweep in range(_BLOCKED_NUM_SWEEPS):
        for round_idx in range(ring):
            _jacobi_round_kernel[(batch, n_pairs)](
                W,
                V,
                R,
                C,
                R * C,
                C * C,
                round_idx,
                ring,
                BLOCK_R=BLOCK_R,
                BLOCK_C=BLOCK_C,
            )

    S = torch.empty(batch, C, dtype=torch.float32, device=device)
    _column_norm_kernel[(batch, C)](W, S, R, C, R * C, BLOCK_R=BLOCK_R)

    SMAX = torch.empty(batch, dtype=torch.float32, device=device)
    _sigma_max_kernel[(batch,)](S, SMAX, C, BLOCK_C=BLOCK_C)

    out = torch.empty(batch, C, R, dtype=torch.float32, device=device)

    # tl.dot requires tiles of at least 16 along every axis.
    BLOCK_I = 32
    BLOCK_L = 32
    BLOCK_J = 32
    grid = (batch, triton.cdiv(C, BLOCK_I), triton.cdiv(R, BLOCK_L))
    _pinv_reconstruct_kernel[grid](
        V,
        W,
        S,
        SMAX,
        out,
        R,
        C,
        atol_val,
        rtol_val,
        C * C,
        R * C,
        C * R,
        BLOCK_I=BLOCK_I,
        BLOCK_L=BLOCK_L,
        BLOCK_J=BLOCK_J,
    )
    return out


def linalg_pinv(
    A: torch.Tensor,
    *,
    atol: float = None,
    rtol: float = None,
    hermitian: bool = False,
) -> torch.Tensor:
    """Compute the Moore-Penrose pseudoinverse using one-sided Jacobi SVD.

    Args:
        A: Input tensor of shape (*, m, n).
        atol: Absolute tolerance for singular value thresholding.
        rtol: Relative tolerance (default: max(m,n) * eps, or 0 when atol > 0).
        hermitian: Ignored; the SVD path yields the same pseudoinverse for
            hermitian input, it just does not exploit the structure.

    Returns:
        Pseudoinverse of shape (*, n, m).
    """
    logger.debug("GEMS LINALG_PINV")

    assert A.dtype in (
        torch.float32,
        torch.float64,
    ), f"linalg_pinv: expected float32 or float64, got {A.dtype}"

    if not A.is_contiguous():
        A = A.contiguous()

    orig_shape = A.shape
    m = orig_shape[-2]
    n = orig_shape[-1]
    k = min(m, n)

    # Flatten batch dimensions
    if A.dim() == 2:
        A_work = A.unsqueeze(0)
    else:
        A_work = A
    batch_shape = A_work.shape[:-2]
    batch = 1
    for d in batch_shape:
        batch *= d
    A_flat = A_work.reshape(batch, m, n)

    # Threshold follows torch semantics: cutoff = max(atol, rtol * sigma_max),
    # and rtol falls back to 0 when only a positive atol is given.
    atol_val = 0.0 if atol is None else float(atol)
    if rtol is None:
        eps = torch.finfo(A.dtype).eps
        rtol_val = 0.0 if atol_val > 0.0 else float(max(m, n)) * eps
    else:
        rtol_val = float(rtol)

    compute_dtype = A.dtype

    if m > _FUSED_MAX_DIM or n > _FUSED_MAX_DIM:
        # Blocked path. One-sided Jacobi orthogonalizes columns, so it wants at
        # least as many rows as columns; for wide inputs use
        # pinv(A) = pinv(A^T)^T to get there.
        if m < n:
            W = A_flat.transpose(-2, -1).contiguous().to(torch.float32)
            R, C = n, m
            transposed = True
        else:
            # .to() is a no-op for float32 input, so clone to keep the caller's
            # tensor safe from the in-place rotations.
            W = A_flat.to(torch.float32).clone()
            R, C = m, n
            transposed = False

        out_f32 = _blocked_pinv(W, batch, R, C, atol_val, rtol_val)
        if transposed:
            out_f32 = out_f32.transpose(-2, -1).contiguous()
    else:
        # Determine block sizes (must be powers of 2 >= dimension)
        BLOCK_M = triton.next_power_of_2(m)
        BLOCK_N = triton.next_power_of_2(n)
        BLOCK_K = triton.next_power_of_2(k)

        # Number of Jacobi sweeps - balance convergence vs compile time
        # O(n^2/2 * sweeps) loop iterations are statically unrolled
        if k <= 4:
            NUM_SWEEPS = 10
        elif k <= 8:
            NUM_SWEEPS = 8
        else:
            NUM_SWEEPS = 5

        # Compute in float32 for the kernel
        A_f32 = A_flat.float() if A.dtype != torch.float32 else A_flat

        out_f32 = torch.empty(batch, n, m, dtype=torch.float32, device=A.device)

        grid = (batch,)
        _jacobi_pinv_kernel[grid](
            A_f32,
            out_f32,
            m,
            n,
            k,
            m * n,  # a_batch_stride
            n * m,  # out_batch_stride
            atol_val,
            rtol_val,
            NUM_SWEEPS=NUM_SWEEPS,
            BLOCK_M=BLOCK_M,
            BLOCK_N=BLOCK_N,
            BLOCK_K=BLOCK_K,
        )

    if compute_dtype != torch.float32:
        out = out_f32.to(compute_dtype)
    else:
        out = out_f32

    # Reshape to original batch shape + (n, m)
    out_shape = list(orig_shape[:-2]) + [n, m]
    return out.reshape(out_shape)
