# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import get_tuned_config
from flag_gems.utils import libentry
from flag_gems.utils.limits import get_dtype_min

logger = logging.getLogger(__name__)


def max_pool1d_output_size(
    in_size: int,
    kernel_size: int,
    stride: int,
    padding: int,
    dilation: int,
    ceil_mode: bool = False,
) -> int:
    effective_kernel_size = (kernel_size - 1) * dilation + 1
    numerator = in_size + 2 * padding - effective_kernel_size
    if ceil_mode:
        output_size = (numerator + stride - 1) // stride + 1
        # PyTorch-compatible adjustment for ceil_mode
        if (output_size - 1) * stride >= in_size + padding:
            output_size -= 1
    else:
        output_size = numerator // stride + 1

    return output_size


@libentry()
@triton.autotune(
    configs=get_tuned_config("max_pool1d_with_indices"),
    key=["out_l", "kernel_l", "stride_l"],
)
@triton.jit
def max_pool1d_forward_kernel(
    input_ptr,
    output_ptr,
    indices_ptr,
    # Input tensor strides
    in_stride_nc,
    in_stride_l,
    # Input/Output shapes
    in_l,
    out_l,
    # Pooling parameters
    kernel_l: tl.constexpr,
    stride_l: tl.constexpr,
    padding_l: tl.constexpr,
    dilation_l: tl.constexpr,
    # Meta-parameters for tiling
    BLOCK_L: tl.constexpr,
):
    pid_nc = tl.program_id(0)
    pid_l = tl.program_id(1)

    l_out_offsets = pid_l * BLOCK_L + tl.arange(0, BLOCK_L)

    dtype = input_ptr.type.element_ty
    min_val = get_dtype_min(dtype)
    max_val_acc = tl.full((BLOCK_L,), min_val, dtype=dtype)
    max_idx_acc = tl.full((BLOCK_L,), -1, dtype=tl.int64)

    input_base_ptr = input_ptr + pid_nc * in_stride_nc

    for kl in tl.static_range(0, kernel_l):
        l_in = l_out_offsets * stride_l - padding_l + kl * dilation_l
        in_mask = (l_in >= 0) & (l_in < in_l)
        input_offset = l_in * in_stride_l
        current_val = tl.load(
            input_base_ptr + input_offset, mask=in_mask, other=min_val
        )
        current_idx = l_in

        is_new_max = current_val > max_val_acc
        max_val_acc = tl.where(is_new_max, current_val, max_val_acc)
        max_idx_acc = tl.where(is_new_max & in_mask, current_idx, max_idx_acc)

    out_base_ptr = output_ptr + pid_nc * out_l
    indices_base_ptr = indices_ptr + pid_nc * out_l

    out_mask = l_out_offsets < out_l
    tl.store(out_base_ptr + l_out_offsets, max_val_acc, mask=out_mask)
    tl.store(indices_base_ptr + l_out_offsets, max_idx_acc, mask=out_mask)


def _parse_pool_params(kernel_size, stride, padding, dilation):
    def _single(value, name):
        if isinstance(value, (list, tuple)):
            if len(value) != 1:
                raise ValueError(f"{name} must be a single int for 1D pooling")
            return int(value[0])
        return int(value)

    kernel_l = _single(kernel_size, "kernel_size")

    if stride is None or (isinstance(stride, (list, tuple)) and len(stride) == 0):
        stride_l = kernel_l
    else:
        stride_l = _single(stride, "stride")

    padding_l = _single(padding, "padding")
    dilation_l = _single(dilation, "dilation")

    if kernel_l <= 0:
        raise ValueError(f"kernel_size must be positive, but got {kernel_l}")
    if stride_l <= 0:
        raise ValueError(f"stride must be positive, but got {stride_l}")
    if padding_l < 0:
        raise ValueError(f"padding must be non-negative, but got {padding_l}")
    if dilation_l <= 0:
        raise ValueError(f"dilation must be positive, but got {dilation_l}")

    return kernel_l, stride_l, padding_l, dilation_l


def max_pool1d_with_indices(
    input: torch.Tensor,
    kernel_size,
    stride=None,
    padding=0,
    dilation=1,
    ceil_mode=False,
):
    logger.debug("GEMS MAX_POOL1D_WITH_INDICES")

    kernel_l, stride_l, padding_l, dilation_l = _parse_pool_params(
        kernel_size, stride, padding, dilation
    )

    # Input may be (C, L) or (N, C, L). Normalize to 3D for the kernel launch.
    squeeze_batch = input.dim() == 2
    if squeeze_batch:
        input = input.unsqueeze(0)

    input = input.contiguous()
    in_n, in_c, in_l = input.shape
    out_l = max_pool1d_output_size(
        in_l, kernel_l, stride_l, padding_l, dilation_l, ceil_mode
    )

    output = torch.empty((in_n, in_c, out_l), device=input.device, dtype=input.dtype)
    indices = torch.empty((in_n, in_c, out_l), device=input.device, dtype=torch.int64)

    if output.numel() != 0:
        grid = lambda meta: (
            in_n * in_c,
            triton.cdiv(out_l, meta["BLOCK_L"]),
        )

        max_pool1d_forward_kernel[grid](
            input,
            output,
            indices,
            input.stride(1),
            input.stride(2),
            in_l,
            out_l,
            kernel_l,
            stride_l,
            padding_l,
            dilation_l,
        )

    if squeeze_batch:
        output = output.squeeze(0)
        indices = indices.squeeze(0)

    return output, indices
