# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.ops.vector_norm import vector_norm
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def _native_norm_l2_kernel(X, Out, M, BLOCK_SIZE: tl.constexpr):
    """Single-block L2 norm of a contiguous full reduction.

    `native_norm` always reduces the whole tensor, so the partial-then-final
    two-kernel scheme in `vector_norm` is pure overhead here: for small inputs
    the second launch costs as much as the reduction itself. One block covers
    the whole tensor below the cutoff used by the caller.
    """
    offset = tl.arange(0, BLOCK_SIZE)
    mask = offset < M
    inp_dtype = X.type.element_ty
    if inp_dtype == tl.float64:
        acc_dtype = tl.float64
    else:
        acc_dtype = tl.float32
    x = tl.load(X + offset, mask=mask, other=0.0).to(acc_dtype)
    tl.store(Out, tl.sqrt(tl.sum(x * x)))


# Largest element count handled by the fused single-block kernel. Below this
# the fused kernel beats the two-kernel scheme by ~1.5-2x (the saved launch
# dominates); above it the two-kernel scheme wins because one block can no
# longer hide the load latency. The value also keeps BLOCK_SIZE within
# triton's maximum tensor numel.
_FUSED_MAX_NUMEL = 16384


def native_norm(self, p=2):
    """
    Compute the p-norm over all elements of the input tensor.

    Args:
        self: Input tensor
        p: The order of norm (default: 2)

    Returns:
        A scalar tensor containing the p-norm
    """
    logger.debug("GEMS NATIVE_NORM")

    # Validate dtype
    if self.dtype not in [torch.float16, torch.float32, torch.bfloat16, torch.float64]:
        raise NotImplementedError(f"native_norm not implemented for {self.dtype}")

    # native_norm is a full-tensor reduction to a scalar. The fused kernel
    # needs a contiguous buffer, and a small input is exactly the case where
    # the two-kernel scheme is worth avoiding, so route that case first and
    # fall through to vector_norm otherwise.
    if float(p) == 2.0 and self.numel() <= _FUSED_MAX_NUMEL:
        x = self.contiguous()
        out = torch.empty([], dtype=self.dtype, device=x.device)
        with torch_device_fn.device(x.device):
            _native_norm_l2_kernel[(1,)](
                x, out, x.numel(), BLOCK_SIZE=triton.next_power_of_2(x.numel())
            )
        return out

    # Delegate to vector_norm with dim=None (full reduction), keepdim=False.
    return vector_norm(self, ord=p, dim=None, keepdim=False, dtype=self.dtype)
