# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as tle

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def _nested_to_padded_tensor_kernel(
    values,  # 1D flat values buffer of the nested tensor
    offsets,  # [batch] int64 - element offset of each component in values
    sizes,  # [batch, ndim] int64 - per-component sizes (dim0 is row count)
    output,  # output tensor, flattened
    trailing_prod,  # product of trailing dims (elements per row)
    ndim,  # number of dims per component
    stride_out_b,  # stride of batch dim in output (in elements)
    BLOCK_SIZE: tl.constexpr,
):
    """Copy each ragged component into its padded slot of the output.

    Grid is (batch, num_chunks). Program (b, c) copies chunk c of the valid
    (non-padding) region of component b from the flat values buffer into the
    output. Padding positions are pre-filled on the host, so this kernel only
    writes the valid elements and skips chunks that lie entirely in padding.
    """
    pid_b = tle.program_id(axis=0)
    pid_c = tle.program_id(axis=1)

    rows_b = tl.load(sizes + pid_b * ndim)
    offset_b = tl.load(offsets + pid_b)

    valid_elements = rows_b * trailing_prod
    chunk_start = pid_c * BLOCK_SIZE

    # Early exit if this chunk is entirely within the padding region.
    if chunk_start >= valid_elements:
        return

    offs = chunk_start + tl.arange(0, BLOCK_SIZE)
    mask = offs < valid_elements

    src_off = offset_b + offs
    dst_off = pid_b * stride_out_b + offs

    vals = tl.load(values + src_off, mask=mask)
    tl.store(output + dst_off, vals, mask=mask)


def nested_to_padded_tensor(self, padding, output_size=None):
    """Convert a nested (ragged) tensor to a padded dense tensor.

    Args:
        self: nested tensor whose components share trailing dims but vary
            along dim 0.
        padding: scalar value used to fill unoccupied positions.
        output_size: optional explicit padded shape; when omitted the padded
            shape is inferred as (batch, max_rows, *trailing).

    Returns:
        Dense padded tensor.
    """
    logger.debug("GEMS NESTED_TO_PADDED_TENSOR")

    # self._nested_tensor_size() is a CPU int64 tensor (aten contract), so the
    # per-component row counts and the padded shape are read straight off it.
    # Deriving them from the device copy instead would cost one D2H sync per
    # .item() (twice per call here), which dominates the whole operator for the
    # small, launch-bound inputs this op is used with.
    sizes_cpu = self._nested_tensor_size()
    values = self.values()

    batch = sizes_cpu.shape[0]
    ndim = sizes_cpu.shape[1]

    trailing_shape = [int(sizes_cpu[0, i]) for i in range(1, ndim)]
    trailing_prod = 1
    for s in trailing_shape:
        trailing_prod *= s

    if output_size is None:
        max_rows = int(sizes_cpu[:, 0].max())
        out_shape = [batch, max_rows] + trailing_shape
    else:
        out_shape = [int(x) for x in output_size]
        max_rows = out_shape[1]

    sizes = sizes_cpu.to(values.device)
    offsets = self._nested_tensor_storage_offsets().to(values.device)

    # Allocate the padded output and pre-fill every position with `padding`;
    # the kernel then overwrites only the valid (non-padding) elements.
    out = torch.full(
        out_shape, float(padding), dtype=values.dtype, device=values.device
    )

    # BLOCK_SIZE=1024 balances occupancy and memory throughput for the
    # contiguous per-component copies of typical trailing-dim sizes.
    BLOCK_SIZE = 1024
    max_chunks = (max_rows * trailing_prod + BLOCK_SIZE - 1) // BLOCK_SIZE
    grid = (batch, max_chunks)

    _nested_to_padded_tensor_kernel[grid](
        values,
        offsets,
        sizes,
        out,
        trailing_prod,
        ndim,
        out.stride(0),
        BLOCK_SIZE=BLOCK_SIZE,
    )

    return out
