# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def _row_indices_copy_kernel(
    src_ptr,
    dst_ptr,
    layout_ptr,  # flat sizes followed by flat strides of the logical shape
    n_elements,
    RANK_DYN: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    # The source buffer (``row_indices()``) is always stored row-major
    # contiguous over its logical shape (verified for plain and batched
    # CSC/BSC), so a flat unit stride reads it correctly regardless of rank --
    # using ``stride(0)`` here would only be right for rank 1 and read out of
    # bounds for batched shapes like (2, 6) with stride (6, 1). ``out`` may
    # arrive non-contiguous (ATen accepts it and honours its strides), so its
    # flat offset is decoded against the full stride vector in a RANK_DYN-trip
    # loop; for a contiguous destination the loop multiplies every stride by 1
    # and the decomposition drops out.
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    flat_offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = flat_offsets < n_elements

    vals = tl.load(src_ptr + flat_offsets, mask=mask)

    cur = tl.where(mask, flat_offsets, 0).to(tl.int64)
    dst_offsets = tl.zeros((BLOCK_SIZE,), dtype=tl.int64)
    for i in tl.static_range(RANK_DYN - 1, -1, -1):
        dim_size = tl.load(layout_ptr + i).to(tl.int64)
        dim_stride = tl.load(layout_ptr + RANK_DYN + i).to(tl.int64)
        dst_offsets += (cur % dim_size) * dim_stride
        cur = cur // dim_size
    tl.store(dst_ptr + dst_offsets, vals, mask=mask)


def _row_indices_copy_impl(self: torch.Tensor, *, out=None):
    # Extract the row_indices buffer of a column-compressed sparse tensor
    # (sparse_csc / sparse_bsc) and return a contiguous strided copy.
    if self.layout not in (torch.sparse_csc, torch.sparse_bsc):
        raise RuntimeError(
            "row_indices expected sparse column compressed tensor layout but got "
            f"{str(self.layout).replace('torch.', '')}"
        )

    src = self.row_indices()
    # The row_indices buffer is 1-D; the copy must produce a contiguous tensor
    # whose dtype matches the index dtype (int32 or int64).
    if out is not None:
        if out.dtype != src.dtype:
            raise RuntimeError(
                f"Expected out tensor to have dtype {src.dtype}, but got {out.dtype} instead"
            )
        # PyTorch resizes mismatched-shape outs to the required shape.
        if out.numel() != src.numel() or out.shape != src.shape:
            out.resize_(src.shape)
        dst = out
    else:
        # Allocate via ``empty_strided`` with contiguous strides to bypass the
        # GEMS ``aten::empty.memory_format`` override, which launches a Triton
        # zero-init kernel. The copy kernel overwrites every element under a
        # bounds mask, so an uninitialized allocation is safe.
        out_shape = tuple(src.shape)
        contig_strides = []
        stride = 1
        for dim_sz in reversed(out_shape):
            contig_strides.append(stride)
            stride *= dim_sz
        contig_strides.reverse()
        dst = torch.empty_strided(
            out_shape, contig_strides, dtype=src.dtype, device=src.device
        )

    n_elements = src.numel()
    if n_elements == 0:
        return dst

    # Build the flat layout vector (sizes followed by strides of the logical
    # shape) used by the kernel to map flat offsets to element addresses.
    # ``row_indices()`` is always stored row-major contiguous (plain and
    # batched CSC/BSC), so the source side reads with a flat unit stride and
    # only the destination decomposition is needed here. The destination's
    # real strides (contiguous or not) are read as pure metadata; host-side
    # ``.contiguous()`` materialization is deliberately avoided.
    layout = [int(d) for d in dst.shape] + [int(s) for s in dst.stride()]
    if dst.dim() == 0:
        # A 0-dim destination has no strides to decompose.
        layout = [1, 1]
    rank = len(layout) // 2
    layout_buf = torch.tensor(layout, dtype=torch.int64, device=src.device)
    # A larger block keeps the launch grid small (<= a few blocks) for the
    # buffer sizes typical of sparse index arrays, reducing launch overhead
    # relative to the amount of data actually copied.
    BLOCK_SIZE = 4096
    grid = (triton.cdiv(n_elements, BLOCK_SIZE),)
    _row_indices_copy_kernel[grid](
        src, dst, layout_buf, n_elements, RANK_DYN=rank, BLOCK_SIZE=BLOCK_SIZE
    )
    return dst


def row_indices_copy(self: torch.Tensor):
    logger.debug("GEMS ROW_INDICES_COPY")
    return _row_indices_copy_impl(self)


def row_indices_copy_out(self: torch.Tensor, *, out: torch.Tensor):
    logger.debug("GEMS ROW_INDICES_COPY_OUT")
    return _row_indices_copy_impl(self, out=out)
