# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils.random_utils import (
    philox_backend_seed_offset,
    uint_to_uniform_float,
)

logger = logging.getLogger(__name__)

UNROLL = tl.constexpr(4)
EVAL_BLOCK_SIZE = 2048
EVAL_NUM_WARPS = 4


@triton.jit(do_not_specialize=["lower", "upper"])
def rrelu_eval_kernel(
    x_ptr,
    out_ptr,
    n_elements,
    lower,
    upper,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0.0)
    # Evaluation mode uses the constant slope (lower + upper) / 2.
    slope = (lower.to(tl.float32) + upper.to(tl.float32)) * 0.5
    x_f32 = x.to(tl.float32)
    out = tl.where(x_f32 >= 0, x_f32, x_f32 * slope)
    tl.store(out_ptr + offsets, out.to(x.dtype), mask=mask)


@triton.jit(do_not_specialize=["lower", "upper", "philox_seed", "philox_offset"])
def rrelu_train_kernel(
    x_ptr,
    out_ptr,
    n_elements,
    lower,
    upper,
    philox_seed,
    philox_offset,
    BLOCK: tl.constexpr,
):
    philox_seed = philox_seed.to(tl.int64)
    philox_offset = philox_offset.to(tl.int64)
    c0 = (philox_offset & 0xFFFFFFFF).to(tl.uint32)
    c1 = ((philox_offset >> 32) & 0xFFFFFFFF).to(tl.uint32)
    i4 = tl.program_id(0) * BLOCK + tl.arange(0, BLOCK)
    c0 += i4
    _O = c0 * 0
    r0, r1, r2, r3 = tl.philox(philox_seed, c0, c1, _O, _O)

    u0 = uint_to_uniform_float(r0)
    u1 = uint_to_uniform_float(r1)
    u2 = uint_to_uniform_float(r2)
    u3 = uint_to_uniform_float(r3)

    lower_f = lower.to(tl.float32)
    upper_f = upper.to(tl.float32)

    off_0 = tl.program_id(0) * BLOCK * UNROLL + tl.arange(0, BLOCK)
    off_1 = off_0 + BLOCK
    off_2 = off_1 + BLOCK
    off_3 = off_2 + BLOCK

    x0 = tl.load(x_ptr + off_0, mask=off_0 < n_elements, other=0.0)
    x1 = tl.load(x_ptr + off_1, mask=off_1 < n_elements, other=0.0)
    x2 = tl.load(x_ptr + off_2, mask=off_2 < n_elements, other=0.0)
    x3 = tl.load(x_ptr + off_3, mask=off_3 < n_elements, other=0.0)

    # RReLU: out = x for x >= 0, otherwise x * u where u ~ U(lower, upper).
    y0 = tl.where(x0 >= 0, x0, x0 * (lower_f + u0 * (upper_f - lower_f)))
    y1 = tl.where(x1 >= 0, x1, x1 * (lower_f + u1 * (upper_f - lower_f)))
    y2 = tl.where(x2 >= 0, x2, x2 * (lower_f + u2 * (upper_f - lower_f)))
    y3 = tl.where(x3 >= 0, x3, x3 * (lower_f + u3 * (upper_f - lower_f)))

    tl.store(out_ptr + off_0, y0, mask=off_0 < n_elements)
    tl.store(out_ptr + off_1, y1, mask=off_1 < n_elements)
    tl.store(out_ptr + off_2, y2, mask=off_2 < n_elements)
    tl.store(out_ptr + off_3, y3, mask=off_3 < n_elements)


def _rrelu_train_(A, lower, upper, generator=None):
    n_elements = A.numel()
    if n_elements == 0:
        return A
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK"] * UNROLL),)
    increment = triton.cdiv(n_elements, UNROLL)
    philox_seed, philox_offset = philox_backend_seed_offset(
        increment, generator=generator
    )
    with torch_device_fn.device(A.device):
        rrelu_train_kernel[grid](
            A,
            A,
            n_elements,
            float(lower),
            float(upper),
            philox_seed,
            philox_offset,
            # 1D elementwise RReLU kernel; 1024 keeps blocks warp-aligned for
            # peak bandwidth on the random-slope path.
            BLOCK=1024,
        )
    return A


def _rrelu_eval_(A, lower, upper):
    n_elements = A.numel()
    if n_elements == 0:
        return A
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(A.device):
        rrelu_eval_kernel[grid](
            A,
            A,
            n_elements,
            float(lower),
            float(upper),
            BLOCK_SIZE=EVAL_BLOCK_SIZE,
            num_warps=EVAL_NUM_WARPS,
        )
    return A


def rrelu_(
    A,
    lower=0.125,
    upper=0.33333333333333331,
    training=False,
    generator=None,
):
    logger.debug("GEMS RRELU_")
    if training:
        return _rrelu_train_(A, lower, upper, generator)
    return _rrelu_eval_(A, lower, upper)
