# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(is_tensor=[True, True, False], promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def softshrink_backward_kernel(grad_output, self, lambd):
    # PyTorch semantics: grad flows where |self| > lambd; `not (|self| <= lambd)`
    # matches aten's comparison predicate including NaN propagation.
    return tl.where(~(tl.abs(self) <= lambd), grad_output, 0)


def softshrink_backward(grad_output, self, lambd):
    logger.debug("GEMS SOFTSHRINK_BACKWARD")
    grad_input = softshrink_backward_kernel(grad_output, self, lambd)
    return grad_input
