# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

logger = logging.getLogger(__name__)


# sym_size returns the shape of a tensor as a list of integers
# Since this is a metadata operation, we don't need a Triton kernel
# The shape is metadata that can be retrieved directly from the tensor
def sym_size(A: torch.Tensor):
    """Return the size of a tensor as a list of integers.

    Matches the ``aten::sym_size`` default-overload semantics
    (``Tensor self`` -> ``SymInt[]``).

    Args:
        A: Input tensor

    Returns:
        list of integers representing the tensor shape
    """
    logger.debug("GEMS SYM_SIZE")
    return list(A.shape)


def sym_size_int(A: torch.Tensor, dim: int):
    """Return the size of one dimension.

    Matches the ``aten::sym_size.int`` overload
    (``Tensor self, int dim`` -> ``SymInt``).
    """
    logger.debug("GEMS SYM_SIZE_INT")
    return A.shape[dim]
