# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
import warnings

import torch
import triton
import triton.language as tl

from flag_gems.ops.contiguous import contiguous
from flag_gems.ops.copy import copy_
from flag_gems.ops.sum import sum_dim
from flag_gems.utils import libentry, libtuner

logger = logging.getLogger(__name__)


def trilinear_get_configs():
    return [
        triton.Config({"BLOCK_SIZE": 256}, num_warps=4, num_stages=3),
        triton.Config({"BLOCK_SIZE": 512}, num_warps=4, num_stages=3),
        triton.Config({"BLOCK_SIZE": 1024}, num_warps=4, num_stages=3),
    ]


@libentry()
@libtuner(
    configs=trilinear_get_configs(),
    key=["n_elements"],
    strategy=["align32"],
    warmup=5,
    rep=5,
)
@triton.jit
def trilinear_kernel(
    i1_ptr,
    i2_ptr,
    i3_ptr,
    output_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    i1 = tl.load(i1_ptr + offsets, mask=mask, other=0.0)
    i2 = tl.load(i2_ptr + offsets, mask=mask, other=0.0)
    i3 = tl.load(i3_ptr + offsets, mask=mask, other=0.0)
    out = i1 * i2 * i3
    tl.store(output_ptr + offsets, out, mask=mask)


def _apply_expand(t, expand):
    """Insert size-1 dims at the positions listed in ``expand`` (aten semantics)."""
    for d in expand:
        t = t.unsqueeze(d)
    return t


def _trilinear_product(i1, i2, i3, expand1, expand2, expand3):
    """Broadcast the three inputs and compute their elementwise product on-device
    with the Triton ``trilinear_kernel`` (no torch elementwise-mul fallback)."""
    a = _apply_expand(i1, expand1)
    b = _apply_expand(i2, expand2)
    c = _apply_expand(i3, expand3)

    shape = torch.broadcast_shapes(a.shape, b.shape, c.shape)
    a = a.broadcast_to(shape)
    b = b.broadcast_to(shape)
    c = c.broadcast_to(shape)
    # Host-function convention: route layout normalization through the FlagGems
    # contiguous op instead of calling tensor.contiguous() directly.
    a = contiguous(a) if not a.is_contiguous() else a
    b = contiguous(b) if not b.is_contiguous() else b
    c = contiguous(c) if not c.is_contiguous() else c

    prod = torch.empty(shape, dtype=a.dtype, device=a.device)
    n_elements = prod.numel()
    if n_elements > 0:
        grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)  # noqa: E731
        trilinear_kernel[grid](a, b, c, prod, n_elements)
    return prod


def _trilinear_compute(i1, i2, i3, expand1, expand2, expand3, sumdim):
    prod = _trilinear_product(i1, i2, i3, expand1, expand2, expand3)
    if sumdim:
        # Reduce the summed dims through the FlagGems sum kernel.
        prod = sum_dim(prod, dim=list(sumdim), keepdim=False)
    return prod


def _trilinear(i1, i2, i3, expand1, expand2, expand3, sumdim, unroll_dim=1):
    """Compute the trilinear product exp(A)-style 3-way tensor product.

    Broadcasts ``i1``/``i2``/``i3`` (after applying the ``expand*`` unsqueeze
    lists) to a common shape, multiplies them elementwise with a Triton kernel,
    and sums over ``sumdim``. ``unroll_dim`` does not affect the mathematical
    result and is accepted for aten signature compatibility.
    """
    logger.debug("GEMS _TRILINEAR")
    if not (
        isinstance(i1, torch.Tensor)
        and isinstance(i2, torch.Tensor)
        and isinstance(i3, torch.Tensor)
    ):
        raise TypeError("_trilinear expects three tensor inputs")
    if not (i1.device == i2.device == i3.device):
        raise RuntimeError("All tensors must be on the same device")
    return _trilinear_compute(i1, i2, i3, expand1, expand2, expand3, sumdim)


def _trilinear_out(i1, i2, i3, expand1, expand2, expand3, sumdim, unroll_dim=1, *, out):
    """Out variant of :func:`_trilinear` writing the result into ``out``."""
    logger.debug("GEMS _TRILINEAR_OUT")
    if not (
        isinstance(i1, torch.Tensor)
        and isinstance(i2, torch.Tensor)
        and isinstance(i3, torch.Tensor)
    ):
        raise TypeError("_trilinear expects three tensor inputs")
    if not (i1.device == i2.device == i3.device):
        raise RuntimeError("All tensors must be on the same device")
    if out.device != i1.device:
        raise RuntimeError("output must be on the same device as inputs")
    result = _trilinear_compute(i1, i2, i3, expand1, expand2, expand3, sumdim)
    # ATen out contract: resize when the shape differs (matching aten's
    # resize_output semantics), then write through the out tensor's own strides
    # with the FlagGems copy_ instead of tensor.copy_, which would raise for a
    # non-contiguous out.
    if tuple(out.shape) != tuple(result.shape):
        if out.numel() != 0:
            warnings.warn(
                "An output with one or more elements was resized since it had "
                f"shape {list(out.shape)}, which does not match the required "
                f"output shape {list(result.shape)}. This behavior is deprecated, "
                "and in a future PyTorch release outputs will not be resized "
                "unless they have zero elements. You can explicitly reuse an out "
                "tensor t by resizing it, inplace, to zero elements with "
                "t.resize_(0).",
                UserWarning,
                stacklevel=3,
            )
        out.resize_(result.shape)
    copy_(out, result)
    return out
