# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.ops.mean import mean as gems_mean
from flag_gems.ops.sum import sum as gems_sum
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry, libtuner, tl_extra_shim

# x ** p is decomposed as exp2(p * log2(x)): tl_extra_shim.pow is too heavy
exp2 = tl_extra_shim.exp2
log2 = tl_extra_shim.log2
logger = logging.getLogger(__name__)


TRIPLET_MARGIN_LOSS_CONFIGS = runtime.get_tuned_config("triplet_margin_loss") or [
    triton.Config({"BLOCK_M": 8, "BLOCK_D": 64}, num_warps=4),
    triton.Config({"BLOCK_M": 16, "BLOCK_D": 128}, num_warps=4),
    triton.Config({"BLOCK_M": 8, "BLOCK_D": 128}, num_warps=8),
]


@libentry()
@libtuner(configs=TRIPLET_MARGIN_LOSS_CONFIGS, key=["D"])
@triton.jit
def triplet_margin_loss_p1_kernel(
    anchor_ptr,
    positive_ptr,
    negative_ptr,
    out_ptr,
    N,
    D,
    eps,
    margin,
    SWAP: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_D: tl.constexpr,
):
    acc_dtype = (
        tl.float64 if anchor_ptr.type.element_ty == tl.float64 else tl.float32
    )  # noqa: E501
    pid = tl.program_id(0) * BLOCK_M + tl.arange(0, BLOCK_M)[:, None]
    row_mask = pid < N

    acc_ap = tl.zeros([BLOCK_M], dtype=acc_dtype)
    acc_an = tl.zeros([BLOCK_M], dtype=acc_dtype)
    acc_pn = tl.zeros([BLOCK_M], dtype=acc_dtype)

    for start in range(0, D, BLOCK_D):
        cols = start + tl.arange(0, BLOCK_D)[None, :]
        col_mask = cols < D
        mask = row_mask & col_mask
        a = tl.load(anchor_ptr + pid * D + cols, mask=mask, other=0).to(
            acc_dtype
        )  # noqa: E501
        pos = tl.load(positive_ptr + pid * D + cols, mask=mask, other=0).to(
            acc_dtype
        )  # noqa: E501
        neg = tl.load(negative_ptr + pid * D + cols, mask=mask, other=0).to(
            acc_dtype
        )  # noqa: E501

        # ATen applies eps *before* the elementwise abs: it computes the Lp
        # distance of (x1 - x2 + eps), so eps shifts every coordinate rather
        # than being added once to the finished norm.
        diff_ap = tl.abs(a - pos + eps)
        diff_an = tl.abs(a - neg + eps)
        acc_ap += tl.sum(tl.where(mask, diff_ap, 0.0), axis=1)
        acc_an += tl.sum(tl.where(mask, diff_an, 0.0), axis=1)
        if SWAP:
            diff_pn = tl.abs(pos - neg + eps)
            acc_pn += tl.sum(tl.where(mask, diff_pn, 0.0), axis=1)

    dist_ap = acc_ap
    dist_an = acc_an
    if SWAP:
        dist_pn = acc_pn
        dist_an = tl.minimum(dist_an, dist_pn)

    loss = dist_ap - dist_an + margin
    loss = tl.maximum(loss, 0.0)
    tl.store(out_ptr + pid, loss[:, None], row_mask)


@libentry()
@libtuner(configs=TRIPLET_MARGIN_LOSS_CONFIGS, key=["D"])
@triton.jit
def triplet_margin_loss_p2_kernel(
    anchor_ptr,
    positive_ptr,
    negative_ptr,
    out_ptr,
    N,
    D,
    eps,
    margin,
    SWAP: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_D: tl.constexpr,
):
    acc_dtype = (
        tl.float64 if anchor_ptr.type.element_ty == tl.float64 else tl.float32
    )  # noqa: E501
    pid = tl.program_id(0) * BLOCK_M + tl.arange(0, BLOCK_M)[:, None]
    row_mask = pid < N

    acc_ap = tl.zeros([BLOCK_M], dtype=acc_dtype)
    acc_an = tl.zeros([BLOCK_M], dtype=acc_dtype)
    acc_pn = tl.zeros([BLOCK_M], dtype=acc_dtype)

    for start in range(0, D, BLOCK_D):
        cols = start + tl.arange(0, BLOCK_D)[None, :]
        col_mask = cols < D
        mask = row_mask & col_mask
        a = tl.load(anchor_ptr + pid * D + cols, mask=mask, other=0).to(
            acc_dtype
        )  # noqa: E501
        pos = tl.load(positive_ptr + pid * D + cols, mask=mask, other=0).to(
            acc_dtype
        )  # noqa: E501
        neg = tl.load(negative_ptr + pid * D + cols, mask=mask, other=0).to(
            acc_dtype
        )  # noqa: E501

        diff_ap = tl.abs(a - pos + eps)
        diff_an = tl.abs(a - neg + eps)
        acc_ap += tl.sum(tl.where(mask, diff_ap * diff_ap, 0.0), axis=1)
        acc_an += tl.sum(tl.where(mask, diff_an * diff_an, 0.0), axis=1)
        if SWAP:
            diff_pn = tl.abs(pos - neg + eps)
            acc_pn += tl.sum(tl.where(mask, diff_pn * diff_pn, 0.0), axis=1)

    dist_ap = tl.sqrt(acc_ap)
    dist_an = tl.sqrt(acc_an)
    if SWAP:
        dist_pn = tl.sqrt(acc_pn)
        dist_an = tl.minimum(dist_an, dist_pn)

    loss = dist_ap - dist_an + margin
    loss = tl.maximum(loss, 0.0)
    tl.store(out_ptr + pid, loss[:, None], row_mask)


@libentry()
@libtuner(configs=TRIPLET_MARGIN_LOSS_CONFIGS, key=["D"])
@triton.jit
def triplet_margin_loss_general_kernel(
    anchor_ptr,
    positive_ptr,
    negative_ptr,
    out_ptr,
    N,
    D,
    eps,
    p,
    margin,
    SWAP: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_D: tl.constexpr,
):
    acc_dtype = (
        tl.float64 if anchor_ptr.type.element_ty == tl.float64 else tl.float32
    )  # noqa: E501
    p = p.to(acc_dtype)
    pid = tl.program_id(0) * BLOCK_M + tl.arange(0, BLOCK_M)[:, None]
    row_mask = pid < N

    acc_ap = tl.zeros([BLOCK_M], dtype=acc_dtype)
    acc_an = tl.zeros([BLOCK_M], dtype=acc_dtype)
    acc_pn = tl.zeros([BLOCK_M], dtype=acc_dtype)

    for start in range(0, D, BLOCK_D):
        cols = start + tl.arange(0, BLOCK_D)[None, :]
        col_mask = cols < D
        mask = row_mask & col_mask
        a = tl.load(anchor_ptr + pid * D + cols, mask=mask, other=0).to(
            acc_dtype
        )  # noqa: E501
        pos = tl.load(positive_ptr + pid * D + cols, mask=mask, other=0).to(
            acc_dtype
        )  # noqa: E501
        neg = tl.load(negative_ptr + pid * D + cols, mask=mask, other=0).to(
            acc_dtype
        )  # noqa: E501

        diff_ap = tl.abs(a - pos + eps)
        diff_an = tl.abs(a - neg + eps)
        acc_ap += tl.sum(tl.where(mask, exp2(p * log2(diff_ap)), 0.0), axis=1)
        acc_an += tl.sum(tl.where(mask, exp2(p * log2(diff_an)), 0.0), axis=1)
        if SWAP:
            diff_pn = tl.abs(pos - neg + eps)
            acc_pn += tl.sum(
                tl.where(mask, exp2(p * log2(diff_pn)), 0.0), axis=1
            )  # noqa: E501

    inv_p = 1.0 / p
    dist_ap = exp2(inv_p * log2(acc_ap))
    dist_an = exp2(inv_p * log2(acc_an))
    if SWAP:
        dist_pn = exp2(inv_p * log2(acc_pn))
        dist_an = tl.minimum(dist_an, dist_pn)

    loss = dist_ap - dist_an + margin
    loss = tl.maximum(loss, 0.0)
    tl.store(out_ptr + pid, loss[:, None], row_mask)


@libentry()
@libtuner(configs=TRIPLET_MARGIN_LOSS_CONFIGS, key=["D"])
@triton.jit
def triplet_margin_loss_p0_kernel(
    anchor_ptr,
    positive_ptr,
    negative_ptr,
    out_ptr,
    N,
    D,
    eps,
    margin,
    SWAP: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_D: tl.constexpr,
):
    # p = 0 is the "count" norm: ATen returns the number of coordinates whose
    # shifted difference (x1 - x2 + eps) is non-zero.
    acc_dtype = (
        tl.float64 if anchor_ptr.type.element_ty == tl.float64 else tl.float32
    )  # noqa: E501
    pid = tl.program_id(0) * BLOCK_M + tl.arange(0, BLOCK_M)[:, None]
    row_mask = pid < N

    acc_ap = tl.zeros([BLOCK_M], dtype=acc_dtype)
    acc_an = tl.zeros([BLOCK_M], dtype=acc_dtype)
    acc_pn = tl.zeros([BLOCK_M], dtype=acc_dtype)

    for start in range(0, D, BLOCK_D):
        cols = start + tl.arange(0, BLOCK_D)[None, :]
        col_mask = cols < D
        mask = row_mask & col_mask
        a = tl.load(anchor_ptr + pid * D + cols, mask=mask, other=0).to(
            acc_dtype
        )  # noqa: E501
        pos = tl.load(positive_ptr + pid * D + cols, mask=mask, other=0).to(
            acc_dtype
        )  # noqa: E501
        neg = tl.load(negative_ptr + pid * D + cols, mask=mask, other=0).to(
            acc_dtype
        )  # noqa: E501

        nz_ap = (a - pos + eps) != 0.0
        nz_an = (a - neg + eps) != 0.0
        acc_ap += tl.sum(tl.where(mask & nz_ap, 1.0, 0.0), axis=1)
        acc_an += tl.sum(tl.where(mask & nz_an, 1.0, 0.0), axis=1)
        if SWAP:
            nz_pn = (pos - neg + eps) != 0.0
            acc_pn += tl.sum(tl.where(mask & nz_pn, 1.0, 0.0), axis=1)

    dist_ap = acc_ap
    dist_an = acc_an
    if SWAP:
        dist_pn = acc_pn
        dist_an = tl.minimum(dist_an, dist_pn)

    loss = dist_ap - dist_an + margin
    loss = tl.maximum(loss, 0.0)
    tl.store(out_ptr + pid, loss[:, None], row_mask)


@libentry()
@libtuner(configs=TRIPLET_MARGIN_LOSS_CONFIGS, key=["D"])
@triton.jit
def triplet_margin_loss_inf_kernel(
    anchor_ptr,
    positive_ptr,
    negative_ptr,
    out_ptr,
    N,
    D,
    eps,
    margin,
    SWAP: tl.constexpr,
    IS_MAX: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_D: tl.constexpr,
):
    # p = +inf -> max coordinate distance; p = -inf -> min coordinate distance.
    acc_dtype = (
        tl.float64 if anchor_ptr.type.element_ty == tl.float64 else tl.float32
    )  # noqa: E501
    pid = tl.program_id(0) * BLOCK_M + tl.arange(0, BLOCK_M)[:, None]
    row_mask = pid < N

    if IS_MAX:
        # abs values are >= 0, so 0 is a safe lower bound for masked lanes.
        init = 0.0
    else:
        init = float("inf")
    acc_ap = tl.full([BLOCK_M], init, dtype=acc_dtype)
    acc_an = tl.full([BLOCK_M], init, dtype=acc_dtype)
    acc_pn = tl.full([BLOCK_M], init, dtype=acc_dtype)

    for start in range(0, D, BLOCK_D):
        cols = start + tl.arange(0, BLOCK_D)[None, :]
        col_mask = cols < D
        mask = row_mask & col_mask
        a = tl.load(anchor_ptr + pid * D + cols, mask=mask, other=0).to(
            acc_dtype
        )  # noqa: E501
        pos = tl.load(positive_ptr + pid * D + cols, mask=mask, other=0).to(
            acc_dtype
        )  # noqa: E501
        neg = tl.load(negative_ptr + pid * D + cols, mask=mask, other=0).to(
            acc_dtype
        )  # noqa: E501

        diff_ap = tl.abs(a - pos + eps)
        diff_an = tl.abs(a - neg + eps)
        if IS_MAX:
            acc_ap = tl.maximum(
                acc_ap, tl.max(tl.where(mask, diff_ap, init), axis=1)
            )  # noqa: E501
            acc_an = tl.maximum(
                acc_an, tl.max(tl.where(mask, diff_an, init), axis=1)
            )  # noqa: E501
        else:
            acc_ap = tl.minimum(
                acc_ap, tl.min(tl.where(mask, diff_ap, init), axis=1)
            )  # noqa: E501
            acc_an = tl.minimum(
                acc_an, tl.min(tl.where(mask, diff_an, init), axis=1)
            )  # noqa: E501
        if SWAP:
            diff_pn = tl.abs(pos - neg + eps)
            if IS_MAX:
                acc_pn = tl.maximum(
                    acc_pn, tl.max(tl.where(mask, diff_pn, init), axis=1)
                )  # noqa: E501
            else:
                acc_pn = tl.minimum(
                    acc_pn, tl.min(tl.where(mask, diff_pn, init), axis=1)
                )  # noqa: E501

    dist_ap = acc_ap
    dist_an = acc_an
    if SWAP:
        dist_pn = acc_pn
        dist_an = tl.minimum(dist_an, dist_pn)

    loss = dist_ap - dist_an + margin
    loss = tl.maximum(loss, 0.0)
    tl.store(out_ptr + pid, loss[:, None], row_mask)


def triplet_margin_loss(
    anchor,
    positive,
    negative,
    margin=1.0,
    p=2.0,
    eps=1e-6,
    swap=False,
    reduction="mean",
):
    logger.debug("GEMS TRIPLET_MARGIN_LOSS")

    # reduction may come as an aten integer (0=none, 1=mean, 2=sum) or a string
    if isinstance(reduction, int):
        reduction = ["none", "mean", "sum"][reduction]

    # Match ATen's input contract: same-rank broadcastable shapes are valid and
    # mixed input dtypes follow normal type promotion. Broadcast first, then
    # promote every operand to the common dtype so the kernel sees one dtype and
    # the output uses the promoted dtype.
    out_dtype = torch.promote_types(
        torch.promote_types(anchor.dtype, positive.dtype), negative.dtype
    )
    anchor, positive, negative = torch.broadcast_tensors(anchor, positive, negative)
    anchor = anchor.to(out_dtype).contiguous()
    positive = positive.to(out_dtype).contiguous()
    negative = negative.to(out_dtype).contiguous()

    out_shape = anchor.shape[:-1]
    D = anchor.shape[-1] if anchor.ndim > 0 else 1
    N = anchor.numel() // D if D > 0 else anchor.numel()

    out = torch.empty(out_shape, dtype=out_dtype, device=anchor.device)

    if D == 0:
        # Empty feature dimension: every Lp distance is 0, so each sample's loss
        # collapses to clamp_min(margin, 0), matching ATen.
        out.fill_(max(float(margin), 0.0))
    elif N > 0:
        grid = lambda meta: (triton.cdiv(N, meta["BLOCK_M"]),)  # noqa: E731

        with torch_device_fn.device(anchor.device):
            if p == 1.0:
                triplet_margin_loss_p1_kernel[grid](
                    anchor,
                    positive,
                    negative,
                    out,
                    N,
                    D,
                    eps,
                    margin,
                    SWAP=swap,
                )
            elif p == 2.0:
                triplet_margin_loss_p2_kernel[grid](
                    anchor,
                    positive,
                    negative,
                    out,
                    N,
                    D,
                    eps,
                    margin,
                    SWAP=swap,
                )
            elif p == 0.0:
                triplet_margin_loss_p0_kernel[grid](
                    anchor,
                    positive,
                    negative,
                    out,
                    N,
                    D,
                    eps,
                    margin,
                    SWAP=swap,
                )
            elif p == float("inf"):
                triplet_margin_loss_inf_kernel[grid](
                    anchor,
                    positive,
                    negative,
                    out,
                    N,
                    D,
                    eps,
                    margin,
                    SWAP=swap,
                    IS_MAX=True,
                )
            elif p == float("-inf"):
                triplet_margin_loss_inf_kernel[grid](
                    anchor,
                    positive,
                    negative,
                    out,
                    N,
                    D,
                    eps,
                    margin,
                    SWAP=swap,
                    IS_MAX=False,
                )
            else:
                triplet_margin_loss_general_kernel[grid](
                    anchor,
                    positive,
                    negative,
                    out,
                    N,
                    D,
                    eps,
                    p,
                    margin,
                    SWAP=swap,
                )

    # Reductions are routed through FlagGems' own reduction operators rather
    # than native host-side Tensor.mean()/.sum(), per the host-function
    # convention.
    if reduction == "mean":
        return gems_mean(out)
    elif reduction == "sum":
        return gems_sum(out)
    return out
