# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

"""
weight_int4pack_mm: Int4 packed weight matrix multiplication.

Conventions (self-consistent across kernel, tests, and reference):
  - A (self):     activation tensor of shape (M, K), dtype fp16/bf16/fp32.
  - mat2:         int4 packed weights of shape (N, K//2), dtype uint8.
                  Each byte packs two adjacent int4 values:
                    low  nibble (bits 0-3)  = weight[n, 2*j]     (even column)
                    high nibble (bits 4-7)  = weight[n, 2*j+1]   (odd column)
                  This packing matches _convert_weight_to_int4pack.
  - qGroupSize:   group size along the K dimension for quantization.
                  K must be divisible by qGroupSize.
  - qScaleAndZeros: shape (K//qGroupSize, N, 2), dtype same as A.
                    Last dim: index 0 = scale, index 1 = zero_point.
  - Output:       tensor of shape (M, N), dtype same as A.
                  Computes C = A @ dequant(W).T, where dequant(W) has
                  shape (N, K) after unpacking and dequantizing mat2.

Implementation:
  The Triton kernel fuses int4 unpacking and dequantization directly into
  the GEMM main loop, so the (N, K) float weight matrix is never
  materialized in global memory. The K contraction is split into two
  interleaved streams -- even columns come from the low nibble of each
  packed byte, odd columns from the high nibble -- which lets the kernel
  work on the packed (N, K//2) layout with no interleaving. Because
  qGroupSize is even, the even/odd pair sharing a packed byte always falls
  in the same quantization group, so a single scale/zero load serves both.
"""

import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def weight_int4pack_mm_kernel(
    A_ptr,
    B_ptr,
    SZ_ptr,
    C_ptr,
    M,
    N,
    K,
    qGroupSize,
    stride_am,
    stride_ak,
    stride_bn,
    stride_bk,
    stride_sz_g,
    stride_sz_n,
    stride_sz_c,
    stride_cm,
    stride_cn,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    BLOCK_K2: tl.constexpr,
    GROUP_M: tl.constexpr,
):
    """Fused int4 dequantize + GEMM.

    Computes C = A @ dequant(W).T where W (N, K) is unpacked and dequantized
    on the fly from the packed uint8 tensor B (N, K//2). The contraction over
    K is performed in packed steps of BLOCK_K2 columns; each step handles the
    even columns (low nibble) and odd columns (high nibble) as two tl.dot
    accumulations, avoiding any explicit interleaving.
    """
    pid = tl.program_id(0)
    num_pid_m = tl.cdiv(M, BLOCK_M)
    num_pid_n = tl.cdiv(N, BLOCK_N)
    num_pid_in_group = GROUP_M * num_pid_n
    group_id = pid // num_pid_in_group
    first_pid_m = group_id * GROUP_M
    group_size_m = tl.minimum(num_pid_m - first_pid_m, GROUP_M)
    pid_m = first_pid_m + (pid % group_size_m)
    pid_n = (pid % num_pid_in_group) // group_size_m

    offs_m = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    offs_n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    offs_k2 = tl.arange(0, BLOCK_K2)

    m_mask = offs_m < M
    n_mask = offs_n < N

    # K//2: number of packed columns.
    K2 = K // 2

    acc = tl.zeros((BLOCK_M, BLOCK_N), dtype=tl.float32)

    for start_k2 in range(0, K2, BLOCK_K2):
        pk = start_k2 + offs_k2  # packed-column index, length BLOCK_K2
        k2_mask = pk < K2

        # Even/odd real-K positions sharing each packed byte.
        even_k = 2 * pk
        odd_k = even_k + 1

        # Load A even/odd tiles: (BLOCK_M, BLOCK_K2).
        a_even_ptrs = A_ptr + offs_m[:, None] * stride_am + even_k[None, :] * stride_ak
        a_odd_ptrs = A_ptr + offs_m[:, None] * stride_am + odd_k[None, :] * stride_ak
        a_load_mask = m_mask[:, None] & k2_mask[None, :]
        a_even = tl.load(a_even_ptrs, mask=a_load_mask, other=0.0)
        a_odd = tl.load(a_odd_ptrs, mask=a_load_mask, other=0.0)

        # Load packed weight tile transposed to (BLOCK_K2, BLOCK_N).
        b_ptrs = B_ptr + pk[:, None] * stride_bk + offs_n[None, :] * stride_bn
        b_load_mask = k2_mask[:, None] & n_mask[None, :]
        b_packed = tl.load(b_ptrs, mask=b_load_mask, other=0)
        b_packed = b_packed.to(tl.int32)
        low = (b_packed & 0xF).to(tl.float32)  # even columns
        high = ((b_packed >> 4) & 0xF).to(tl.float32)  # odd columns

        # Group index for scale/zero. qGroupSize is even, so the even/odd pair
        # shares a group -> a single load serves both nibbles.
        g = even_k // qGroupSize  # (BLOCK_K2,)
        sz_scale_ptrs = (
            SZ_ptr + g[:, None] * stride_sz_g + offs_n[None, :] * stride_sz_n
        )
        sz_zero_ptrs = sz_scale_ptrs + stride_sz_c
        sz_mask = k2_mask[:, None] & n_mask[None, :]
        scale = tl.load(sz_scale_ptrs, mask=sz_mask, other=0.0).to(tl.float32)
        zero = tl.load(sz_zero_ptrs, mask=sz_mask, other=0.0).to(tl.float32)

        # Dequantize: (BLOCK_K2, BLOCK_N).
        w_even = (low - zero) * scale
        w_odd = (high - zero) * scale

        acc += tl.dot(
            a_even.to(tl.float32), w_even, out_dtype=tl.float32, allow_tf32=True
        )
        acc += tl.dot(
            a_odd.to(tl.float32), w_odd, out_dtype=tl.float32, allow_tf32=True
        )

    acc = acc.to(C_ptr.dtype.element_ty)
    c_ptrs = C_ptr + offs_m[:, None] * stride_cm + offs_n[None, :] * stride_cn
    c_mask = m_mask[:, None] & n_mask[None, :]
    tl.store(c_ptrs, acc, mask=c_mask)


def weight_int4pack_mm(
    A: torch.Tensor,
    mat2: torch.Tensor,
    qGroupSize: int,
    qScaleAndZeros: torch.Tensor,
) -> torch.Tensor:
    """Int4 packed weight matrix multiplication.

    Args:
        A:              Activation tensor of shape (M, K), floating point dtype.
        mat2:           Int4 packed weight tensor of shape (N, K//2), dtype uint8.
                        Byte-pair packing: low nibble = even column, high nibble = odd column.
        qGroupSize:     Group size along K dimension. Must evenly divide K.
        qScaleAndZeros: Scale and zero points of shape (K//qGroupSize, N, 2),
                        dtype same as A. Last dim: [scale, zero].

    Returns:
        Output tensor of shape (M, N), dtype same as A.
    """
    logger.debug("GEMS _WEIGHT_INT4PACK_MM")

    M, K = A.shape
    N = mat2.shape[0]
    K_half = mat2.shape[1]
    assert K == K_half * 2, (
        f"mat2 shape[1] ({K_half}) must equal K//2 where K={K} (from A), "
        f"got K_half * 2 = {K_half * 2} != K={K}"
    )
    assert (
        K % qGroupSize == 0
    ), f"K ({K}) must be divisible by qGroupSize ({qGroupSize})"
    assert qGroupSize % 2 == 0, f"qGroupSize ({qGroupSize}) must be even"
    assert mat2.dtype == torch.uint8, f"mat2 must be uint8, got {mat2.dtype}"
    assert A.dtype.is_floating_point, f"A must be a floating point type, got {A.dtype}"

    A = A.contiguous()
    mat2 = mat2.contiguous()
    qScaleAndZeros = qScaleAndZeros.contiguous()

    out = torch.empty((M, N), dtype=A.dtype, device=A.device)

    # BLOCK sizes chosen for the small-to-medium GEMM shapes this op targets
    # (M<=512, N<=1024, K<=2048); BLOCK_K2 steps over packed (K//2) columns.
    BLOCK_M = 64
    BLOCK_N = 64
    BLOCK_K2 = 32
    GROUP_M = 8

    grid = lambda META: (
        triton.cdiv(M, META["BLOCK_M"]) * triton.cdiv(N, META["BLOCK_N"]),
    )

    with torch_device_fn.device(A.device):
        weight_int4pack_mm_kernel[grid](
            A,
            mat2,
            qScaleAndZeros,
            out,
            M,
            N,
            K,
            qGroupSize,
            A.stride(0),
            A.stride(1),
            mat2.stride(0),
            mat2.stride(1),
            qScaleAndZeros.stride(0),
            qScaleAndZeros.stride(1),
            qScaleAndZeros.stride(2),
            out.stride(0),
            out.stride(1),
            BLOCK_M=BLOCK_M,
            BLOCK_N=BLOCK_N,
            BLOCK_K2=BLOCK_K2,
            GROUP_M=GROUP_M,
        )

    return out
